### PR TITLE
Bug fixes and improvements

### LINKED ISSUE #723: [Bug]: request control
### Describe the bug

request control event is preventing my friends to drive my personal vehicles and always teleports it away. also, i was playing with a guy in his MC bus, and we went into sparrow, as soon as we got out of kosatka, the sparrow exploded.

### Steps To Reproduce

Settings > Notifications > Request control (checked both notify and logs)

### Expected Behavior

guess it shouldnt do that.

### Screenshots and/or Logs

```
<
[12-17-2022-22-50-42_cout.log](https://github.com/YimMenu/YimMenu/files/10260268/12-17-2022-22-50-42_cout.log)
>
```

### Store

Epic Games

### Additional context

it also seems to happen with vehicle kick protection.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #726: [Bug]: No Idle Kick does not work.
### Describe the bug

As the title describes, No Idle Kick does not work.

### Steps To Reproduce

1. Start menu and click self.
2. Check off No Idle Kick
3. Just wait for it.

### Expected Behavior

Should be able to prevent game from kicking you when idle.

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

This is the nightly build I used.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #813: [Bug]: Job load times out
### Describe the bug

When YimMenu users start jobs, they cannot start and are excluded from the session.

### Steps To Reproduce

1.YimMenu inject
2.invite friends to job
3.start job
4.job times out

### Expected Behavior

job starts

### Screenshots and/or Logs

_No response_

### Store

Epic Games

### Additional context

- I tried it by myself using 2 computers and 2 accounts.
- I tried with a combination of Epic Games version and Rockstar Launcher version,
- I turned off all the protection items, but it didn't change.
- Unloading YimMenu from either PC allowed the job to start.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #899: [Bug]: Protections: Blocked request control event by [player in the same lobby]
### Describe the bug

Playing Casino Heist (Big Con) Gruppe Sechs. After arriving at the location, it goes black screen and loads indefinitely.

This error shown by all players in the lobby.

### Steps To Reproduce

Get a friend to start the heist
Reach the spot (in any way)

### Expected Behavior

It should load just fine.

### Screenshots and/or Logs
[cout.log](https://github.com/YimMenu/YimMenu/files/10475265/cout.log)

gambar

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #901: [Bug]: #602 introduced a bug with vehicles spawned as attachments.
### Describe the bug

https://github.com/YimMenu/YimMenu/pull/602/commits/697f8be05a9768619c672a1cd997ee07e3ac53af#diff-8cc7b0ec458e888abba72604fc6516c21d0da3f6bfd4c65c4bc33b31160769d7R134

If you set this to true, the code for attempting to get into vehicles will see these as vehicles the player can get into. If you use the test cases from the original repository you took the code from, there should be a mech or something that Lima_Bean made that constantly caused issues and we had to develop around. The player would constantly try to get into the tank legs. I don't see the purpose for why you would want collision on for these attachments, as it would probably lag the game, but that's not my problem.

### Steps To Reproduce

F

### Expected Behavior

F

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

F

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #953: [Bug]: failed to start freemode missions/other freemode missions won't start in a session
### Describe the bug

i tried to start a freemode mission from missions window but it won't run.also i tried to turn someone into beast and it said "failed to start hunt the beast event".at first i thought someone else blocking the events but that happened in any session i joined even in solo/friend sessions.i turned my protections off just in case but still the same issue happens.also while i have yim loaded any freemode mission in the session won't start

### Steps To Reproduce

1.go to missions window
2.select any mission
3.mission won't start neither other missions

### Expected Behavior

supposed to run a freemode mission

### Screenshots and/or Logs

```
<paste your logs here>
```
Untitled

### Store

Epic Games

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #968: [Bug]: cant launch heist(or setup) with friends
### Describe the bug

let a friend join my heist setup to do it together.
if im not wrong it was the one you use the facility for (Act 2: The Bogdan Problem).
he gets stuck in an infinite loop when he accepts the invite. --> https://ibb.co/vXYg9zG

after some time loading, the joining cancels and gives this error on the screen of the player that was joining --> https://ibb.co/9w3PpV6

after this, you cant really play heists anymore (havnt tested with missions). you can invite random people to your heist, but you cant start it. once you press start, you load into the map with your team. the second you can move, you get an error that says: you have been kicked from the mission, not enough players (like someone left), but nobody has left. --> https://ibb.co/D5Jgm5c.

some methods that seems to fix it are;

- when the friend you invite gets in infinite joining screen, unloading the menu fixes it.
(dont know if it wil work while he is frozen, but joining the new invite again works.)
- when you get the error with "kicked from mission, not enough players", you need to restart GTA to fix that.
even after unloading the menu it keeps crashing your heists

when you inject mid heist nothing happens. but at the end after the "succes" screen we both got the black screen.
we were supposed to be put back in the lobby. (however the messages below(who left and joined) still showed up).

i havent had these problems with random players tho, so maybe that helps a bit

### Steps To Reproduce

.

### Expected Behavior

should not happen, the game should let you play together.

### Screenshots and/or Logs

[https://ibb.co/vXYg9zG]
[https://ibb.co/9w3PpV6]
[https://ibb.co/D5Jgm5c]

### Store

Steam

### Additional context

build 1.66

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by maybegreat48**
* Fixed various bugs
* Added countermeasures to prevent detections from a certain P2C
* Added ability to hide yourself from the freemode playerlist (effect can't be observed locally)
* Improved Kick From Interior
* Added a script launcher to debug

Fixes #968 
Fixes #953 
Fixes #901 
Fixes #899 
Fixes #813 
Fixes #726 
Fixes #723 
RID join works again

### CODE REVIEW

**Review by Yimura — DISMISSED** [review]

File: src/native_hooks/native_hooks.cpp [hunk 1]
```diff
@@ -108,6 +108,7 @@ namespace big
 		add_native_detour(0xD1110739EEADB592, all_scripts::NETWORK_TRY_TO_SET_THIS_SCRIPT_IS_NETWORK_SCRIPT);
 		add_native_detour(0xADF692B254977C0C, all_scripts::SET_CURRENT_PED_WEAPON);
 		add_native_detour(0xFE99B66D079CF6BC, all_scripts::DISABLE_CONTROL_ACTION);
+		add_native_detour(0xFE99B66D079CF6BC, all_scripts::HUD_FORCE_WEAPON_WHEEL);
```
Comment (Aure7138) [inline src/native_hooks/native_hooks.cpp]: 0xEB354E5376BC81A7

**Review by Yimura — DISMISSED** [review]

File: src/hooking.cpp [hunk 2]
```diff
@@ -102,6 +102,8 @@ namespace big
 
 		detour_hook_helper::add<hooks::receive_pickup>("RPI", g_pointers->m_receive_pickup);
 
+		detour_hook_helper::add<hooks::write_player_camera_data_node>("RPI", g_pointers->m_write_player_camera_data_node);
+
```
Comment (Seanghost117) [inline src/hooking.cpp:106]: RPI -> WPCDN

**Review by Yimura — APPROVED** [review]
