### PR TITLE
fix: Made breakup conditional (being host)

### LINKED ISSUE #1430: [Bug]: Breakup kick in reaction settings
### Describe the bug

When any player who has been blocked from the session tries to join our session again, the menu sends him a breakup kick.
If I'm not mistaken, this kick type no longer works (because it doesn't show up under the kick tab).

### Steps To Reproduce

Select and block a player you don't want to join your session.

Wait for the player to join your server again (if he joins)

Observe the warning.

### Expected Behavior

If breakup kick is not used, another effective method can be tried.

### Screenshots and/or Logs

[23:31:20.9201127][WARN/reaction.cpp:25] Received TSE Sender Mismatch from Olxxxxx (220493859)
[23:33:49.6632492][WARN/assign_physical_index.cpp:116] Sending Breakup Kick due to block join failure...

### Store

Epic Games

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by Tayipc38**
Since breakup is now only possible when host, I've adjusted the usage of it.

Closes #1430

### CODE REVIEW

**Review by Yimura — CHANGES_REQUESTED** [review]
Host check for breakup kick can maybe be moved into the command.

File: src/hooks/player_management/assign_physical_index.cpp [hunk 1]
```diff
@@ -109,13 +109,23 @@ namespace big
...
+							dynamic_cast<player_command*>(command::get(RAGE_JOAAT("breakup")))->call(plyr, {});
+							g_notification_service->push_warning("Block Join",
+							    std::format("Block Join method failed for {}, sending breakup kick instead...",
+							        plyr->get_net_data()->m_name));
+							LOG(WARNING) << "Sending Breakup Kick due to block join failure... ";
+						}
+						else
+						{
+							g_notification_service->push_warning("Block Join",
+							    std::format("Block Join method failed for {}, can't send breakup without host...",
```
Comment (maybegreat48) [inline src/hooks/player_management/assign_physical_index.cpp]: You can send a desync here

File: src/hooks/protections/receive_net_message.cpp [hunk 2]
```diff
@@ -117,7 +117,12 @@ namespace big
 					player->is_spammer = true;
 					if (g.session.kick_chat_spammers)
 					{
-						dynamic_cast<player_command*>(command::get(RAGE_JOAAT("breakup")))->call(player, {});
+						if(g_player_service->get_self()->is_host())
+							dynamic_cast<player_command*>(command::get(RAGE_JOAAT("breakup")))->call(player, {}),
+							NETWORK::NETWORK_SESSION_KICK_PLAYER(player->id());
```
Comment (maybegreat48) [inline src/hooks/protections/receive_net_message.cpp]: `NETWORK_SESSION_KICK_PLAYER` only works when host, and can replace the breakup kick

Comment (Tayipc38) [reply src/hooks/protections/receive_net_message.cpp]: Indeed, I put both in just in case. They are both within that if check.

Comment (Yimura) [reply src/hooks/protections/receive_net_message.cpp]: However if a player wants to use breakup kick for the cheating leave message it might be best to leave it in as an option.

Maybe we can make a host kick command with a switch case depending on what the preferred kick method is?

File: src/views/players/player/player_kick.cpp [hunk 3]
```diff
@@ -12,9 +12,16 @@ namespace big
 				return gta_util::get_network()->m_game_session_ptr->is_host();
 			};
 
-			//components::player_command_button<"breakup">(g_player_service->get_selected());
-			//ImGui::SameLine();
-			//components::command_checkbox<"breakupcheating">();
+			if (!g_player_service->get_self()->is_host())
+				ImGui::Text("These kicks require host"), ImGui::BeginDisabled();
```
Comment (tupoy-ya) [inline src/views/players/player/player_kick.cpp]: Why not just do `ImGui::BeginDisabled(!g_player_service->get_self()->is_host());`?
Also why hide the information text about kicks requiring host when host?

File: src/views/network/view_session.cpp [hunk 4]
```diff
@@ -126,9 +126,15 @@ namespace big
 		}
 
 		components::sub_title("Lobby Lock");
+		if (!g_player_service->get_self()->is_host())
+			ImGui::BeginDisabled();
```
Comment (tupoy-ya) [inline src/views/network/view_session.cpp]: Why not just do `ImGui::BeginDisabled(!g_player_service->get_self()->is_host());`?

File: src/views/players/player/player_kick.cpp [hunk 5]
```diff
@@ -12,9 +12,16 @@ namespace big
...
+			
+			components::button("Host kick", []{NETWORK::NETWORK_SESSION_KICK_PLAYER(g_player_service->get_selected()->id());}),
```
Comment (tupoy-ya) [inline src/views/players/player/player_kick.cpp]: This should be a command.

File: src/hooks/protections/receive_net_message.cpp (hunk 2 above)
Comment (maybegreat48) [reply src/hooks/protections/receive_net_message.cpp]: > They are both within that if check.

Didn't see the comma in the end

File: src/views/players/player/player_kick.cpp (hunk 3 above)
Comment (Tayipc38) [reply src/views/players/player/player_kick.cpp]: The menu is often used by people that know little to nothing about how the game works. An UI that is little more telling goes a long way. Also didn't know BeginDisabled took arguments lol.

File: src/backend/looped/session/auto_kick_host.cpp [hunk 6]
```diff
@@ -14,7 +14,9 @@ namespace big
 			g_player_service->iterate([](auto& plyr) {
 				if (plyr.second->is_host())
 				{
-					dynamic_cast<player_command*>(command::get(RAGE_JOAAT("breakup")))->call(plyr.second, {});
+					dynamic_cast<player_command*>(command::get(RAGE_JOAAT("bailkick")))->call(plyr.second, {});
```
Comment (Rxann) [inline src/backend/looped/session/auto_kick_host.cpp:17]: isn't there new way to call commands?

Comment (Tayipc38) [reply src/backend/looped/session/auto_kick_host.cpp:17]: There was a PR for that although im not sure if its merged yet.

**Review by Yimura — APPROVED** [review]

**Review by Yimura — APPROVED** [review]
