### PR TITLE
Many different fixes

### LINKED ISSUE #2325: [Bug]: Translation issues
### Describe the bug

1.Custom Weapon‘s translation dose not work
image
I found it in en_US.json, but it is not displaying correctly.

### Steps To Reproduce

1.Go to Self-Weapons-Custom Weapons

### Expected Behavior

Translation shows correctly.

### Logs and/or screenshots

```
[23:49:57.8977750][INFO/main.cpp:65] Yim's Menu Initializing
[23:49:57.8983535][INFO/main.cpp:66] Git Info
	Branch:	master
	Hash:	352878b8b9f1639f3643d3a5691d9331acc8fa38
	Date:	Sun Oct 22 00:10:46 2023
[23:49:57.8983738][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[23:49:57.8986014][INFO/main.cpp:69] Thread pool initialized.
[23:49:57.9032163][INFO/main.cpp:72] Settings Loaded.
[23:49:57.9032206][DEBUG/thread_pool.cpp:95] Thread 1028 executing settings.cpp:12
[23:49:57.9039973][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[23:49:57.9040099][INFO/pointers.cpp:1752] Loading pointers instance from cache
[23:49:57.9040111][INFO/pointers.cpp:1761] Pointers cache: Loading 208 fields from the cache
[23:49:57.9040213][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[23:49:57.9042566][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[23:49:57.9042605][INFO/pointers.cpp:1752] Loading pointers instance from cache
[23:49:57.9042625][INFO/pointers.cpp:1761] Pointers cache: Loading 5 fields from the cache
[23:49:57.9042977][INFO/main.cpp:75] Pointers initialized.
[23:49:57.9045243][INFO/main.cpp:78] Byte Patch Manager initialized.
[23:49:58.5434039][INFO/main.cpp:81] Renderer initialized.
[23:49:58.7935629][INFO/main.cpp:85] Fiber pool initialized.
[23:49:59.4290195][INFO/main.cpp:88] Translation Service initialized.
[23:49:59.4457369][INFO/main.cpp:91] Hooking initialized.
[23:49:59.4551709][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[23:49:59.4551838][INFO/gta_data_service.cpp:172] Loading 1029 peds from cache.
[23:49:59.4558142][INFO/gta_data_service.cpp:190] Loading 810 vehicles from cache.
[23:49:59.4561040][INFO/gta_data_service.cpp:207] Loading 117 weapons from cache.
[23:49:59.4561088][INFO/gta_data_service.cpp:208] Loading 378 weapon components from cache.
[23:49:59.4561222][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[23:49:59.4605720][DEBUG/thread_pool.cpp:95] Thread 22092 executing player_database_service.cpp:285
[23:49:59.4611850][INFO/main.cpp:111] Registered service instances...
[23:49:59.4613044][INFO/main.cpp:132] Scripts registered.
[23:49:59.5355909][INFO/main.cpp:135] Hooking enabled.
[23:49:59.5419054][INFO/main.cpp:138] Dynamic native hooker initialized.
[23:49:59.6048479][INFO/log.cpp:17] sch.lua: sch-lua v2.03 仅供个人测试和学习使用,禁止商用
[23:49:59.6059787][INFO/lua_module.cpp:226] Loaded sch.lua
[23:49:59.6061950][INFO/main.cpp:141] Lua manager initialized.
[23:49:59.6991069][INFO/backend.cpp:51] Starting script: Self
[23:49:59.6991236][INFO/backend.cpp:76] Starting script: Weapons
[23:49:59.6991297][INFO/backend.cpp:99] Starting script: Vehicles
[23:49:59.6991380][INFO/backend.cpp:115] Starting script: Miscellaneous
[23:49:59.6991634][INFO/backend.cpp:136] Starting script: Remote
[23:49:59.6991683][INFO/backend.cpp:151] Starting script: Ls customs
[23:49:59.6991699][INFO/backend.cpp:163] Starting script: Rainbow paint
[23:49:59.6991724][INFO/backend.cpp:175] Starting script: Disable Control Action
[23:49:59.6991748][INFO/backend.cpp:188] Starting script: World
[23:49:59.7212517][INFO/tunables_service.cpp:36] Loading tunables from cache
[23:50:22.2798158][DEBUG/thread_pool.cpp:95] Thread 17476 executing translation_service.cpp:95

```

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on (https://github.com/YimMenu/YimMenu/actions/runs/6599932915)

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #2666: [Bug]: Name don't appear with  ( announce in chat ) option
### Describe the bug

the name don't appear in the chat with most reaction in ( announce in chat )

### Steps To Reproduce

go to online 
enable announce in chat option 
error

### Expected Behavior

.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #2668: [Bug]: Custom weapon names are not translated in the menu
### Describe the bug

https://prnt.sc/J_RzU4uPHdtB

### Steps To Reproduce

use eyes and look

### Expected Behavior

Should be translated to proper language

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

Newest nightly build

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #2719: [Improvement]: Some settings should not be saved
### Which feature

All settings that are session/world related, e.g.: Riot Mode, Never Wanted (for all), etc.

### Reason

I enabled Riot Mode, crashed a bit later (unrelated). And then I forgot that option - for the next hours. I even played missions with it. After a bunch modders in freemode attacked me out of nowhere and even crashed me twice for no obvious reason I remembered this setting. So I assume Riot Mode does send out some request that their menu blocked & notified them. Because I wasn't doing anything at all and only I got that much attacked.
So my proposal:
Don't save such settings.
Reset them with every new session.

### Additional context

_No response_

### LINKED ISSUE #2722: [Bug]: It could be Rapid Fire causing no response
### Describe the bug

When Rapid Fire enabled and u r shooting. after a while, game will  no response

### Steps To Reproduce

1.turn on Rapid Fire
2.shoot insanely
3.no response

### Expected Behavior

does not lead to no response

### Logs and/or screenshots

EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x20FA243C040
RCX: 0xFFFFFFFF9638D000
RDX: 0x20FA127F0B8
RBX: 0x20FA127F080
RSI: 0x20FA127F0B8
RDI: 0x1
RSP: 0xFF4FD9ECB8
RBP: 0xFF4FD9EE50
R8:  0x20FA243C040
R9:  0xFFFFFFFF9638D000
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x162BAD3 0x7FF74679BAD3
[1]	GTA5.exe+0x100CAE6 0x7FF74617CAE6
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x20F30583F70
RCX: 0xB9
RDX: 0x20FA127F080
RBX: 0x20FA127F080
RSI: 0x20FA127F0B8
RDI: 0x1
RSP: 0xFF4FD9ECB8
RBP: 0xFF4FD9EE50
R8:  0x20FA243C040
R9:  0xFFFFFFFF9638D000
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x162BAF4 0x7FF74679BAF4
[1]	GTA5.exe+0x100CAE6 0x7FF74617CAE6
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x45279DFB
RCX: 0x20F30583F70
RDX: 0x20FA2AFCF60
RBX: 0x20FA127F080
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F54E 0x7FF74617F54E
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x44CAAC6F
RCX: 0x20F30583F70
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F557 0x7FF74617F557
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x41CF0AEC
RCX: 0x20F30583F70
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F55E 0x7FF74617F55E
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x0
RCX: 0x20F30583F70
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F565 0x7FF74617F565
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x45279DFB
RCX: 0x20F30583F70
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F56B 0x7FF74617F56B
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x44CAAC6F
RCX: 0x20F30583F70
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F572 0x7FF74617F572
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x41CF0AEC
RCX: 0x20F30583F70
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F579 0x7FF74617F579
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x0
RCX: 0x20F30583F70
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F580 0x7FF74617F580
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x0
RCX: 0x20F30583F70
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F583 0x7FF74617F583
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x476BF155
RCX: 0x20F30583F70
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F58B 0x7FF74617F58B
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x476BF101
RCX: 0x20F30583F06
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F5A1 0x7FF74617F5A1
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x476BF101
RCX: 0x20F30583F06
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F5C6 0x7FF74617F5C6
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x476BF101
RCX: 0x20F30583F06
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F5CB 0x7FF74617F5CB
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x476BF101
RCX: 0x20F30583F06
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F5D0 0x7FF74617F5D0
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x476BF101
RCX: 0x20F30583F06
RDX: 0x20FA2AFCF60
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F5E5 0x7FF74617F5E5
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x30000
RCX: 0x74
RDX: 0x3A830000
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F5FC 0x7FF74617F5FC
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x30000
RCX: 0x74
RDX: 0x3A830000
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F605 0x7FF74617F605
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x30000
RCX: 0x74
RDX: 0x3A830000
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F60D 0x7FF74617F60D
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x30000
RCX: 0x74
RDX: 0x3A830000
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F612 0x7FF74617F612
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x30000
RCX: 0x74
RDX: 0x3A830000
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F61B 0x7FF74617F61B
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x30000
RCX: 0x74
RDX: 0x3A830000
RBX: 0x20FA2AFCF60
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F624 0x7FF74617F624
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x3DCCCCCD
RCX: 0x74
RDX: 0x3A830000
RBX: 0x20FA127F080
RSI: 0x20FA127F0B8
RDI: 0x20F30583F70
RSP: 0xFF4FD9EC80
RBP: 0xFF4FD9EE50
R8:  0xFF4FD9F0A0
R9:  0xFF4FD9EDE0
R10: 0x20FA129BD30
R11: 0x20F30583F70
R12: 0xFF4FD9F130
R13: 0x0
R14: 0x20FA127F0B0
R15: 0xFF4FD9F0A0
Dumping stacktrace:
[0]	GTA5.exe+0x100F634 0x7FF74617F634
[1]	GTA5.exe+0x100CB2B 0x7FF74617CB2B
[2]	GTA5.exe+0x102DBC8 0x7FF74619DBC8
[3]	GTA5.exe+0x102D4A9 0x7FF74619D4A9
[4]	GTA5.exe+0xC9B306 0x7FF745E0B306
[5]	GTA5.exe+0xCAA2F6 0x7FF745E1A2F6
[6]	GTA5.exe+0x89AF48 0x7FF745A0AF48
[7]	GTA5.exe+0x7A64A1 0x7FF7459164A1
[8]	GTA5.exe+0x93CA27 0x7FF745AACA27
[9]	GTA5.exe+0x575454 0x7FF7456E5454
[10]	GTA5.exe+0x1FF058 0x7FF74536F058
[11]	GTA5.exe+0x27BC2 0x7FF745197BC2
[12]	GTA5.exe+0x21283 0x7FF745191283
[13]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x4320
RCX: 0x20FA127F080
RDX: 0x20F30583F70
RBX: 0x20FA127F080
RSI: 0x0
RDI: 0x0
RSP: 0xFF4FD9B9B0
RBP: 0xFF4FD9BAB0
R8:  0x20F956B6D70
R9:  0x0
R10: 0x394F415C
R11: 0xFF4FD9FCA8
R12: 0x0
R13: 0x0
R14: 0x20FA127F0C8
R15: 0x0
Dumping stacktrace:
[0]	GTA5.exe+0x1043FEB 0x7FF7461B3FEB
[1]	GTA5.exe+0x10443C1 0x7FF7461B43C1
[2]	GTA5.exe+0x1044F04 0x7FF7461B4F04
[3]	GTA5.exe+0x93CA4A 0x7FF745AACA4A
[4]	GTA5.exe+0x575454 0x7FF7456E5454
[5]	GTA5.exe+0x1FF058 0x7FF74536F058
[6]	GTA5.exe+0x27BC2 0x7FF745197BC2
[7]	GTA5.exe+0x21283 0x7FF745191283
[8]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[9]	GTA5.exe+0x1494 0x7FF745171494
[10]	GTA5.exe+0x130538F 0x7FF74647538F
[11]	GTA5.exe+0x1821344 0x7FF746991344
[12]	KERNEL32.DLL BaseThreadInitThunk
[13]	ntdll.dll RtlUserThreadStart
[14]	GTA5.exe+0x1494 0x7FF745171494
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0xFFFFFFFFFE38D000
RCX: 0x20FA129BD30
RDX: 0xFFFFFFFF8E340000
RBX: 0xFFFFFFFFFE38D000
RSI: 0x0
RDI: 0x0
RSP: 0xFF4FD9B9A8
RBP: 0xFF4FD9BAB0
R8:  0x40
R9:  0x20FA2243F70
R10: 0x20FA129BD30
R11: 0xFFFFFFFFFE38D000
R12: 0x0
R13: 0x0
R14: 0x20FA127F0C8
R15: 0x0
Dumping stacktrace:
[0]	GTA5.exe+0x162529B 0x7FF74679529B
[1]	GTA5.exe+0x1043FFD 0x7FF7461B3FFD
[2]	GTA5.exe+0x10443C1 0x7FF7461B43C1
[3]	GTA5.exe+0x1044F04 0x7FF7461B4F04
[4]	GTA5.exe+0x93CA4A 0x7FF745AACA4A
[5]	GTA5.exe+0x575454 0x7FF7456E5454
[6]	GTA5.exe+0x1FF058 0x7FF74536F058
[7]	GTA5.exe+0x27BC2 0x7FF745197BC2
[8]	GTA5.exe+0x21283 0x7FF745191283
[9]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[10]	GTA5.exe+0x1494 0x7FF745171494
[11]	GTA5.exe+0x130538F 0x7FF74647538F
[12]	GTA5.exe+0x1821344 0x7FF746991344
[13]	KERNEL32.DLL BaseThreadInitThunk
[14]	ntdll.dll RtlUserThreadStart
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x20F385D0F70
RCX: 0x20FA129BD30
RDX: 0xFFFFFFFF8E340000
RBX: 0xFFFFFFFFFE38D000
RSI: 0x0
RDI: 0x0
RSP: 0xFF4FD9B9A8
RBP: 0xFF4FD9BAB0
R8:  0x40
R9:  0x20FA2243F70
R10: 0x20FA129BD30
R11: 0xFFFFFFFFFE38D000
R12: 0x0
R13: 0x0
R14: 0x20FA127F0C8
R15: 0x0
Dumping stacktrace:
[0]	GTA5.exe+0x16252C1 0x7FF7467952C1
[1]	GTA5.exe+0x1043FFD 0x7FF7461B3FFD
[2]	GTA5.exe+0x10443C1 0x7FF7461B43C1
[3]	GTA5.exe+0x1044F04 0x7FF7461B4F04
[4]	GTA5.exe+0x93CA4A 0x7FF745AACA4A
[5]	GTA5.exe+0x575454 0x7FF7456E5454
[6]	GTA5.exe+0x1FF058 0x7FF74536F058
[7]	GTA5.exe+0x27BC2 0x7FF745197BC2
[8]	GTA5.exe+0x21283 0x7FF745191283
[9]	GTA5.exe+0x162EEC0 0x7FF74679EEC0
[10]	GTA5.exe+0x1494 0x7FF745171494
[11]	GTA5.exe+0x130538F 0x7FF74647538F
[12]	GTA5.exe+0x1821344 0x7FF746991344
[13]	KERNEL32.DLL BaseThreadInitThunk
[14]	ntdll.dll RtlUserThreadStart
[15]	GTA5.exe+0x130538F 0x7FF74647538F
[16]	GTA5.exe+0x1821344 0x7FF746991344
[17]	KERNEL32.DLL BaseThreadInitThunk
[18]	ntdll.dll RtlUserThreadStart
[19]	GTA5.exe+0x130538F 0x7FF74647538F
[20]	GTA5.exe+0x1821344 0x7FF746991344
[21]	KERNEL32.DLL BaseThreadInitThunk
[22]	ntdll.dll RtlUserThreadStart
--------End of exception--------

### Store

Steam

### Language

Simplified Chinese

### YimMenu Language

Chinese (CN)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #2724: [Bug]: Invalid character output error
### Describe the bug

When you click 'Forced Update Language', there is an error in choosing to participate in a session that is filled with unknown numbers or letters or disappears.

image
There appears to be a problem with the session switcher

### Steps To Reproduce

1. Force update language
2. Network > session switch 

### Expected Behavior

Bad character output and mess up

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Language

Korean

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [x] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #2739: [Bug]: Request Model Bypass
### Describe the bug

Something broke or was not tested enough since both the vehicle xml, the map xml and an anim system with props that I am making to implement it in yimmenu stopped working when implementing this PR, the objects that need the bypass simply Now they don't charge anymore.

### Steps To Reproduce

1.- Go to online.
2.- Use xml vehicles or xml maps
3.- Objects that cannot be used without bypass will not load

### Expected Behavior

You should be able to spawn objects that need to be bypassed with world_model::spawn

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

Example not working with the new implementation:
image

Example working before new implementation:
image

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by Yimura**
Fixes #2739
Fixes #2724
Fixes #2722
Fixes #2719
Fixes #2668
Fixes #2325
Fixes #2666 (untested)

### CODE REVIEW

**Review by gir489returns — APPROVED** [review]

**Comment by lonelybud** [comment]
is the new "invalid weapon type" crash giving false positives?

**Comment by Yimura** [comment]
> is the new "invalid weapon type" crash giving false positives?

Don't know, is it for you?

Also off-topic for this PR as well.

File: src/backend/looped/weapons/rapid_fire.cpp [hunk 1]
```diff
@@ -10,11 +10,29 @@ namespace big
...
+		const std::size_t m_tick_rate = 5u;
+		std::size_t m_current_tick = 0;
+
+		/**
+		 * @brief We have to limit the fire rate for some shotguns as they can fill the bullet pool and crash the game.
+		 * 
+		 * @return true 
+		 * @return false 
+		 */
+		inline bool can_shoot()
```
Comment (gir489returns) [inline src/backend/looped/weapons/rapid_fire.cpp:22]: This could be optomized to:

```
inline bool can_shoot()
{
    bool result = (m_current_tick == 0);
    m_current_tick = (m_current_tick + 1) % m_tick_rate;
    return result;
}
```

**Review by gir489returns — CHANGES_REQUESTED** [review]

**Review by gir489returns — APPROVED** [review]

**Comment by xiaoxiao921** [comment]
> is the new "invalid weapon type" crash giving false positives?

Hey, the next time you say such thing this make sure you are actually copy pasting the code correctly
