### PR TITLE
fix(GTADataService): not skipping bad dlcs

### LINKED ISSUE #2037: [Bug]: Unable to spawn Arbiter GT
### Describe the bug

When attempting to use the Spawn Vehicle feature, the Arbiter GT appears in the list as a valid vehicle, however you cannot preview it or spawn it, despite it being a valid vehicle.

### Steps To Reproduce

1. Go to Spawn Vehicle.
2. Select Arbiter GT.
3. Bug appears.

### Expected Behavior

Should be able to preview and spawn the Arbiter GT.

### Logs and/or screenshots

[vehicles.zip](https://github.com/YimMenu/YimMenu/files/12448114/vehicles.zip)

https://github.com/YimMenu/YimMenu/assets/100792176/201aad0b-546c-4410-a542-c98f3c97da71

### Store

Rockstar

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #2047: GTA data service isn't skipping bad DLC
Regression introduced in #1635

https://github.com/YimMenu/YimMenu/blob/e58f9610b37847974c69324e89b6353973edac3f/src/services/gta_data/gta_data_service.cpp#L270-L282

### PR DESCRIPTION
**Pull request by Yimura**
Closes #2037 
Closes #2047

### CODE REVIEW

**Comment by gir489returns** [comment]
image

[18:33:55.8990202][INFO/yim_fipackfile.cpp:125] gta_folder: E:\Program Files\Rockstar Games\Grand Theft Auto V
[18:33:56.4613467][DEBUG/gta_data_service.cpp:286] Bad DLC, skipping...
Vehicles: 770
Previous: 815 vehicles from cache.
Delta: 45

Seems to be excluding a lot more than just the 5 cars that we shouldn't spawn.

**Comment by Yimura** [comment]
Looking into it

File: src/util/protection.cpp [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
... RAGE_JOAAT("h4_prop_weed_01_row"), RAGE_JOAAT("urbanweeds02_l1"), RAGE_JOAAT("proc_forest_grass01"), RAGE_JOAAT("prop_small_bushyba"), RAGE_JOAAT("v_res_d_dildo_a"), RAGE_JOAAT("v_res_d_dildo_b"), RAGE_JOAAT("v_res_d_dildo_c"), RAGE_JOAAT("v_res_d_dildo_d"), RAGE_JOAAT("v_res_d_dildo_e"), RAGE_JOAAT("v_res_d_dildo_f"), RAGE_JOAAT("v_res_skateboard"), RAGE_JOAAT("prop_battery_01"), RAGE_JOAAT("prop_barbell_01"), RAGE_JOAAT("prop_barbell_02"), RAGE_JOAAT("prop_bandsaw_01"), RAGE_JOAAT("prop_bbq_3"), RAGE_JOAAT("v_med_curtainsnewcloth2"), RAGE_JOAAT("bh1_07_flagpoles"), 92962485, RAGE_JOAAT("proc_dry_plants_01"), RAGE_JOAAT("proc_leafyplant_01"), RAGE_JOAAT("proc_grassplantmix_02"), RAGE_JOAAT("proc_dryplantsgrass_01"), RAGE_JOAAT("proc_dryplantsgrass_02"), RAGE_JOAAT("proc_dryplantsgrass_02"), RAGE_JOAAT("proc_grasses01"), RAGE_JOAAT("prop_dryweed_002_a"), RAGE_JOAAT("prop_fernba"), RAGE_JOAAT("prop_weed_001_aa"), RAGE_JOAAT("urbangrnfrnds_01"), RAGE_JOAAT("urbanweeds01"), RAGE_JOAAT("prop_dandy_b"), RAGE_JOAAT("v_proc2_temp"), RAGE_JOAAT("prop_fernbb"), RAGE_JOAAT("proc_drygrassfronds01"), RAGE_JOAAT("prop_log_ae"), RAGE_JOAAT("prop_grass_da"), RAGE_JOAAT("prop_fragtest_cnst_04")};
```
Comment (gir489returns) [inline src/util/protection.cpp:7]: Change this to a constexpr auto without brackets just like crash_vehicles for consistency, and to allow the compiler to figure it out on its own.

File: src/util/protection.cpp [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+			return false;
+		if (!model_info::is_model_of_type(model, eModelType::Object, eModelType::Time, eModelType::Weapon, eModelType::Destructable, eModelType::WorldObject, eModelType::Sprinkler, eModelType::Unk65, eModelType::Plant, eModelType::LOD, eModelType::Unk132, eModelType::Building))
+			return true;
+		for (auto iterator : crash_objects)
+			if (iterator == model)
+				return true;
+		return false;
+	}
+
+	constexpr uint32_t crash_peds[] = {RAGE_JOAAT("slod_human"), RAGE_JOAAT("slod_small_quadped"), RAGE_JOAAT("slod_large_quadped")};
```
Comment (gir489returns) [inline src/util/protection.cpp:20]: Change this to a constexpr auto without brackets just like crash_vehicles for consistency, and to allow the compiler to figure it out on its own.

File: src/util/protection.cpp [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+	{
+		for (auto iterator : crash_vehicles)
+			if (iterator == model)
+				return true;
+		if (!model_info::is_model_of_type(model, eModelType::Vehicle, eModelType::Unk133))
+			return true;
+		return false;
+	}
+
+	constexpr uint32_t valid_player_models[] = {
```
Comment (gir489returns) [inline src/util/protection.cpp:42]: Change this to a constexpr auto without brackets just like crash_vehicles for consistency, and to allow the compiler to figure it out on its own, also chose to either have a giant one-line list, or each model on a new line for every list on the sheet here.

**Review by gir489returns — CHANGES_REQUESTED** [review]
Optional changes if you agree, apply it.

File: src/util/protection.cpp (hunk 1 above)
Comment (Yimura) [reply src/util/protection.cpp:8]: Yeah the compiler didn't like my opinion when I did that because of the type mismatch with the random signed int in there.

**Comment by gir489returns** [comment]
Previous Vehicles : 815
New Vehicles: 810 
Delta: 5

PR certified.
