### PR TITLE
General fixes

### LINKED ISSUE #1182: [Bug]: Game crash/freeze in ped preview
### Describe the bug

game crashes/freezes when preview the "slod" peds in spawn ped menu.

### Steps To Reproduce

go to world ,spawn ped ,preview the last peds "slod human" etc...

### Expected Behavior

not to freeze/crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Rockstar

### Additional context

other peds dont crash,only the last 3 or 4 named "slod"

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #1188: [Bug]: override color hud not working properly
### Describe the bug

when i toggled on the hud color override every icon went black and some text not even appearing (even after i change colors) and restarting gta fixes it

### Steps To Reproduce

self
override hud color
try changing it
that is how it happend

### Expected Behavior

change color

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

using latest version (the one on releases)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #1228: [Bug]: Bug when the menu announces a breakup kick, etc., the chat continues not to be displayed
### Describe the bug

When the reaction settings enable Announce in the chat for a breakup kick, etc. at the time of connection and before the player spawns, the menu sees the kick of one player to another and announces it in the chat, but for the user of this menu, the chat is no longer displayed and the field disappears in order to write in chat. Sometimes this happens even after the player has spawned.

### Steps To Reproduce

1. Enable Announce in chat for Breakup Kick or something like that.
2. Connect to the session.
3. Before you see your character, the menu will see the cheater in the game and announce him in the chat.
4. Chat stops displaying and working for the menu user.
Although this can sometimes happen even when your character is already displayed and the chat is not displayed because no one has written to the chat for a long time. And after the announcement of the cheater, kick, the bug is repeated.
Edit: Although this can be fixed by writing 2 times in the chat through the menu itself in the Session section in the corresponding input. Then the chat becomes visible and usable again. But this is more of a crutch than a solution to the problem.

### Expected Behavior

The chat should work even after the announcement of the cheater

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### LINKED ISSUE #1248: [Bug]: incorrect hotkeys
### Describe the bug

i was playing and when i click u it opens the commands menu, which is set as 0 for me, and also i have set tp to waypoint at F6 and when i click F6 it toggle/untoggle super run

### Steps To Reproduce

go to settings-hotkeys
set a hotkey (example tp to waypoint at F6)
set a waypoint on the map
press F6
super run toggles/untoggles

### Expected Behavior

should tp me to waypoint

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

working on build 958463d of yimmenu

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by maybegreat48**
* Made the GTA data cache much more efficient (and going online doesn't crash anymore after updating the cache in SP)
* Replaced most instances of replay interface with pools
* Redesigned HUD color override 
* Orbital drone now works in SP
* Fixed a potential bug where the pointer cache could become corrupted after Rockstar launcher updates
* More miscellaneous fixes 

Fixes #1248 
Fixes #1228 (finally!)
Fixes #1188 
Fixes #1182

### CODE REVIEW

File: src/util/vehicle.hpp [hunk 1]
```diff
@@ -107,38 +107,33 @@ namespace big::vehicle
 	{
 		if (const auto replay = *g_pointers->m_gta.m_replay_interface; replay)
```
Comment (Yimura) [inline src/util/vehicle.hpp]: Is this still supposed to be checked against the replay interface? Is it just a sanity check?

Comment (maybegreat48) [reply src/util/vehicle.hpp]: Nope, just didn't see that

**Review by Yimura — APPROVED** [review]
I haven't seen anything else that sticks out so looks good to me.
