### PR TITLE
Closes #2152

### LINKED ISSUE #2152: [Bug]: "Exception while trying to call x native" on any blackscreen
### Describe the bug

When i exit the kosatka without any scripts loaded, errors come in the console

### Steps To Reproduce

Idk if its for everyone but go in kosatka / set spawnpoint there
Exit via ladder in the room where the planning screen is

### Expected Behavior

No error

### Logs and/or screenshots

[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x997ABD671D25CA0B native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x5E9564D8246B909A native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xD80958FC74E988A6 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xDC16122C7A20C933 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x767FBC2AC802EF3D native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.

### Store

Steam

### Additional context

Error

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by gir489returns**
Reduces natives called in hotkey_service::wndproc to prevent collisions.

### CODE REVIEW

File: src/backend/commands/self/suicide.cpp [hunk 1]
```diff
@@ -9,7 +9,10 @@ namespace big
 
 		virtual void execute(const command_arguments&, const std::shared_ptr<command_context> ctx) override
 		{
+			auto godmode_backup = g.self.god_mode;
+			g.self.god_mode     = false;
 			ENTITY::SET_ENTITY_HEALTH(self::ped, 0, 0);
+			g.self.god_mode = godmode_backup;
```
Comment (Yimura) [inline src/backend/commands/self/suicide.cpp]: This function works just fine without disabling godmode, any reason why this is needed?

Comment (gir489returns) [reply src/backend/commands/self/suicide.cpp:15]: What are you talking about? I added a hook to SET_ENTITY_HEALTH that sets the 2nd parameter to the player's max health if g.self.god_mode is on, did you even look at the entire commit?

**Review by Yimura — APPROVED** [review]
