### PR TITLE
Kick player if Block Join fails

### LINKED ISSUE #1278: [Request]: Auto breakup kick if block join doesn't work
### Problem

Toxic bots aka fineMarciaGTA keep joining my lobby, yim tries to block them, but i guess it doesn't work.

### Solution

Auto breakup kicking the people who get past the block join.

### Reason

It would enhance my gta user experience 

### Additional context

I may try to code this in idk

### PR DESCRIPTION
**Pull request by Rxann**
This PR edits the assign_physical_index function to kick the player if block join fails (maybe).
The code compiled by I could not get the chance to test if it really works. I will try.

closes #1278

### CODE REVIEW

File: src/hooks/player_management/assign_physical_index.cpp [hunk 1]
```diff
@@ -46,6 +47,18 @@ namespace big
 		g_player_service->player_join(player);
 		if (net_player_data)
 		{
+			auto bplyr = g_player_service->get_by_id(net_player_data->m_gamer_handle.m_rockstar_id);
+			if (bplyr)
+			{
+				if (bplyr->block_join)
+				{
+					((player_command*)(command::get(RAGE_JOAAT("breakup"))))->call(bplyr, {});
```
Comment (Yimura) [inline src/hooks/player_management/assign_physical_index.cpp]: Use dynamic_cast<player_command*> instead of a C style cast.

Are the that many brackets needed?

**Review by Yimura — CHANGES_REQUESTED** [review]

File: src/hooks/player_management/assign_physical_index.cpp [hunk 2]
```diff
@@ -52,10 +52,10 @@ namespace big
 			{
 				if (bplyr->block_join)
 				{
-					((player_command*)(command::get(RAGE_JOAAT("breakup"))))->call(bplyr, {});
+					dynamic_cast<player_command*>(command::get(RAGE_JOAAT("breakup")))->call(bplyr, {});
 					g_notification_service->push("Player Kicked due to Block Join bypass",
 					    std::format("{} was kicked", net_player_data->m_name));
-					LOG(WARNING) << net_player_data->m_name << "(" << net_player_data->m_gamer_handle.m_rockstar_id << ") has been kicked(breakup) due to block join bypass"
+					LOG(WARNING) << net_player_data->m_name << "(" << net_player_data->m_gamer_handle.m_rockstar_id << ") has been kicked(breakup) due to block join bypass";
```
Comment (Yimura) [inline src/hooks/player_management/assign_physical_index.cpp]: Could you maybe rewrite this text? Nobody will understand why a bypass is needed. Maybe say like "Block join method failed, sending breakup kick instead."

**Review by Yimura — CHANGES_REQUESTED** [review]

File: src/hooks/player_management/assign_physical_index.cpp (hunk 2 above)
Comment (Rxann) [reply src/hooks/player_management/assign_physical_index.cpp]: Alright, I will do this

**Comment by Rxann** [comment]
Is this better?

**Comment by Rxann** [comment]
I think this should be good, i don't know though

**Comment by Rxann** [comment]
merge when?

File: src/hooks/player_management/assign_physical_index.cpp [hunk 3]
```diff
@@ -46,6 +47,18 @@ namespace big
 		g_player_service->player_join(player);
 		if (net_player_data)
 		{
+			auto bplyr = g_player_service->get_by_id(net_player_data->m_gamer_handle.m_rockstar_id);
```
Comment (tupoy-ya) [inline src/hooks/player_management/assign_physical_index.cpp]: You need to use `player->m_player_id` for this function.
Use `g_player_service->get_by_rid` for RID.

File: src/hooks/player_management/assign_physical_index.cpp [hunk 4]
```diff
@@ -46,6 +47,18 @@ namespace big
...
+			if (bplyr)
+			{
+				if (bplyr->block_join)
```
Comment (tupoy-ya) [inline src/hooks/player_management/assign_physical_index.cpp]: I would move it further in the file here:
https://github.com/YimMenu/YimMenu/blob/636a5d194d2d6c837c21975cd9a0cc3accd0f5af/src/hooks/player_management/assign_physical_index.cpp#L92-L97

**Review by tupoy-ya — CHANGES_REQUESTED** [review]

**Comment by Rxann** [comment]
@tupoy-ya is this what you mentioned?

**Comment by tupoy-ya** [comment]
> @tupoy-ya is this what you mentioned?

Yes, but a player_ptr already exists here:
https://github.com/YimMenu/YimMenu/blob/636a5d194d2d6c837c21975cd9a0cc3accd0f5af/src/hooks/player_management/assign_physical_index.cpp#L92-L97

So i don't see a need to get it twice and should move the kick code there.

Don't forget to test your code before it is merged, nobody will do it for you.

EDIT: You broke it back again.

**Comment by Rxann** [comment]
Yeah i'm editing on my phone right now 💀💀💀💀

**Comment by Rxann** [comment]
Can I undo a commit?

**Comment by tupoy-ya** [comment]
Just change it when you will actually be able to test it.

You can revert your commit if you want to, unless it's a question about how to revert it.

**Comment by Rxann** [comment]
Yeah I need to know how to revert it if you could provide me the steps

EDIT: I have reverted it I believe

**Comment by Rxann** [comment]
I also have one question, why should the code be going inside the fiber pool? I could be totally looking at it wrong, but I don't understand why this code would not go with the admin check for example?

**Comment by Rxann** [comment]
I have limited time, so this is the best I could get this code to. It works though so.

File: src/hooks/player_management/assign_physical_index.cpp [hunk 5]
```diff
@@ -76,7 +77,19 @@ namespace big
...
 
-			auto id = player->m_player_id;
+			auto id    = player->m_player_id;
+			auto bplyr = g_player_service->get_by_id(net_player_data->m_gamer_handle.m_rockstar_id);
+			if (bplyr)
+			{
+				if (bplyr->block_join)
+				{
+					dynamic_cast<player_command*>(command::get(RAGE_JOAAT("breakup")))->call(bplyr, {});
+					g_notification_service->push("Block Join Try 2",
```
Comment (Yimura) [inline src/hooks/player_management/assign_physical_index.cpp]: Code looks good, I'd just put the title of the notification as "Block Join".

**Review by Yimura — CHANGES_REQUESTED** [review]

**Comment by tupoy-ya** [comment]
Made i PR fixing it here: https://github.com/Rxann/YimMenu/pull/1.

**Comment by Rxann** [comment]
@Yimura do you think the code should be put inside the fiber pool queue job? like in the pr that @tupoy-ya made?

**Comment by Yimura** [comment]
> @Yimura do you think the code should be put inside the fiber pool queue job? like in the pr that @tupoy-ya made?

No the breakup command doesn't "need" to be ran in a fiber job however he did it so you don't fetch the player_ptr twice.
The player is already being fetch inside the fiber pool job why bother fetching it again outside of it. (That's probably his thought process.)

It's probably best to merge his PR because his code is better optimized.

As a different solution you can maybe fetch the player outside of the fiber pool and pass that to the fiber job instead of only the player ID. And then do your thing outside of the fiber pool. (And removing the fetch of the player inside of the fiber pool job)

```cpp
auto id    = player->m_player_id;
auto plyr = g_player_service->get_by_id(id);
if (plyr)
{
	if (plyr->block_join)
	{
		dynamic_cast<player_command*>(command::get(RAGE_JOAAT("breakup")))->call(plyr, {});
		g_notification_service->push("Block Join",
			std::format("Block Join method failed for {}, sending breakup kick instead...", net_player_data->m_name));
		LOG(WARNING) << "Sending Breakup Kick due to block join failure... ";
	}
}

g_fiber_pool->queue_job([plyr ] {
	if (plyr->get_net_data()->m_gamer_handle.m_rockstar_id != 0)
	{
		if (auto entry = g_player_database_service->get_player_by_rockstar_id(
				plyr->get_net_data()->m_gamer_handle.m_rockstar_id))
		{
			plyr->is_modder         = entry->is_modder;
			plyr->block_join        = entry->block_join;
			plyr->block_join_reason = plyr->block_join_reason;

			if (strcmp(plyr->get_name(), entry->name.data()))
			{
				g_notification_service->push("PLAYERS"_T.data(),
					std::vformat("PLAYER_CHANGED_NAME"_T, std::make_format_args(entry->name, plyr->get_name())));
				entry->name = plyr->get_name();
				g_player_database_service->save();
			}
		}
	}
});
```

Also `player_service::get_by_id` takes a player ID not a Rockstar ID.

**Comment by Rxann** [comment]
Alright, I will merge his pr then test it

**Comment by Rxann** [comment]
@tupoy-ya 's code has been implemented and I have tested it.

**Review by Yimura — APPROVED** [review]
