### PR TITLE
(fix) Seatbelt values are set to opposite

### LINKED ISSUE #2082: [Bug]: the seat belt does not work
### Describe the bug

The seat belt doesn't work, the motorcycle hits an obstacle, the character still falls off the car, is my method of operation wrong? Or do I need to trigger a pre-condition to use my seat belt? My version is [c459ccc]

### Steps To Reproduce

the seat belt does not work, the motorcycle crashes into the obstacle, the character will still fall from the vehicle

### Expected Behavior

After starting this feature, the character should not fall off the car

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by NjuuOwO**
Fix #2082

### CODE REVIEW

File: src/backend/looped/vehicle/seatbelt.cpp [hunk 1]
```diff
@@ -10,13 +10,13 @@ namespace big
...
 			PED::SET_PED_CONFIG_FLAG(self::ped, 32, false);
-			PED::SET_PED_CAN_BE_KNOCKED_OFF_VEHICLE(self::ped, false);
+			PED::SET_PED_CAN_BE_KNOCKED_OFF_VEHICLE(self::ped, 1);
 		}
 
 		virtual void on_disable() override
 		{
 			PED::SET_PED_CONFIG_FLAG(self::ped, 32, true);
-			PED::SET_PED_CAN_BE_KNOCKED_OFF_VEHICLE(self::ped, true);
+			PED::SET_PED_CAN_BE_KNOCKED_OFF_VEHICLE(self::ped, 0);
```
Comment (Yimura) [inline src/backend/looped/vehicle/seatbelt.cpp]: They are boolean values, use `true/false` instead of `1/0`.

**Review by Yimura — CHANGES_REQUESTED** [review]

File: src/backend/looped/vehicle/seatbelt.cpp (hunk 1 above)
Comment (NjuuOwO) [reply src/backend/looped/vehicle/seatbelt.cpp]: > They are boolean values, use `true/false` instead of `1/0`.

`SET_​PED_​CAN_​BE_​KNOCKED_​OFF_​VEHICLE(Ped ped, int state)`
It's an integer and these are the 4 states:

```
enum eKnockOffVehicle
{
	KNOCKOFFVEHICLE_DEFAULT,
	KNOCKOFFVEHICLE_NEVER,
	KNOCKOFFVEHICLE_EASY,
	KNOCKOFFVEHICLE_HARD
};
```

Comment (xiaoxiao921) [reply src/backend/looped/vehicle/seatbelt.cpp]: Then define the enum and use it? instead of hardcoding a 0

File: src/core/enums.hpp [hunk 2]
```diff
@@ -143,6 +143,14 @@ namespace big
 		UNK2                 = 1 << 16
 	};
 
+	enum eKnockOffVehicle
```
Comment (gir489returns) [inline src/core/enums.hpp:146]: You have to strongly type the enum to the parameter instance type or class keyword, or else you are just creating an enum type.

**Review by gir489returns — CHANGES_REQUESTED** [review]

File: src/core/enums.hpp (hunk 2 above)
Comment (NjuuOwO) [reply src/core/enums.hpp]: Oh, thanks for explaining.
And shouldn't this enum be in `/gta/enums.hpp`?

Comment (gir489returns) [reply src/core/enums.hpp:146]: If the enumeration comes from GTA itself it should.

**Review by Yimura — CHANGES_REQUESTED** [review]
Waiting for the changes from @gir489returns to be implemented then it'll be ready to be merged.

**Comment by NjuuOwO** [comment]
I guess it should be done like that

**Comment by gir489returns** [comment]
You also didn't move it to the GTA enums class like you said you were going to.

File: src/core/enums.hpp [hunk 3]
```diff
@@ -143,6 +143,14 @@ namespace big
...
 	};
 
+	enum class eKnockOffVehicle
+	{
+		KNOCKOFFVEHICLE_DEFAULT,
+		KNOCKOFFVEHICLE_NEVER,
+		KNOCKOFFVEHICLE_EASY,
+		KNOCKOFFVEHICLE_HARD
+	};
+
```
Comment (Yimura) [inline src/core/enums.hpp]: enum hasn't been moved.

**Review by Yimura — CHANGES_REQUESTED** [review]

**Review by Yimura — APPROVED** [review]
