### PR TITLE
Fixed commands not working in single player.

### LINKED ISSUE #2955: [Bug]: Problem with Vehicle spawning
### Describe the bug

When I go to my YimMenu I go to the Vehicle section, and I can’t spawn a vehicle because it says “No vehicle in the register”

### Steps To Reproduce

When I go to my YimMenu I go to the Vehicle section, and I can’t spawn a vehicle because it says “No vehicle in the register”

### Expected Behavior

Help me solve the problem, I want to spawn cars without problems

### Logs and/or screenshots

```
![изображение_2024-04-20_185357634](https://github.com/YimMenu/YimMenu/assets/167634793/d79f6312-3f6f-45b2-919f-ba318ebfbbcf)

<paste your logs here>
```

### Store

Steam

### Language

Russian

### YimMenu Language

Русский (RU)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by gir489returns**
Closes #2955

### CODE REVIEW

File: src/services/players/player.cpp [hunk 1]
```diff
@@ -127,7 +127,7 @@ namespace big
 
 	uint8_t player::id() const
 	{
-		return m_net_game_player == nullptr ? -1 : m_net_game_player->m_player_id;
+		return m_net_game_player == nullptr ? self::id : m_net_game_player->m_player_id;
 	}
```
Comment (Yimura) [inline src/services/players/player.cpp]: Wouldn't this change certain behaviour even if it's not our player object (for example when our target leaves online which may then end up targeting ourselves).

Comment (gir489returns) [reply src/services/players/player.cpp:131]: Interesting point, but it should still fail safe instead of use undefined behavior. If that happens, and we revert it to how it was before (if is online, and m_net_game_player  is nullptr) then we would return -1, and the command would run like how it was before, where it would just spawn a car at 0,0,0.

**Review by Yimura — APPROVED** [review]
