### PR TITLE
Misc stuff

### LINKED ISSUE #3142: [Bug]: Found a crash
### Describe the bug

I am able to reproduce the crash.

### Steps To Reproduce

1. First, you need to find Trevor's model 'player_two' and then click the 'Change Player Model' button.
2. Then I applied the naked Trevor skin to myself through the 'Outfit Editor'. I will attach the JSON file.
3. Next, you need to select in the ped spawner Online/Self, choose a weapon, for example, an RPG and Invincible, and spawn it for everyone by clicking 'Spawn Ped'
4. Thus, you spawned Trevor with your naked skin and then ran to the nearest Trevor and waited for him to kill you (this will happen very quickly)
5. After death, you enter a loading screen, but before it finishes, a crash occurs

### Expected Behavior

No crash

### Logs

[trevor.json.txt](https://github.com/YimMenu/YimMenu/files/15354244/trevor.json.txt)
[cout.log](https://github.com/YimMenu/YimMenu/files/15354269/cout.log)
Do not pay attention to the fact that this is not the original .dll in the logs. The crash occurs the same way with the original

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #3436: [Bug]: Fix buttons not being recognised by WndProc callback but are supported through ImGui::Hotkey
### Describe the bug

The ImGui::Hotkey has support for the mouse buttons, however our WndProc hook does not pick up on these.

People will usually make YimMenu unusable trying to set one of the buttons on their mouse to open and close the menu overlay.

### Steps To Reproduce

1. Go to hotkey tab under settings
2. Change hotkey to one of the mouse buttons
3. Observe that the menu overlay cannot be closed after setting this button and on next inject the menu cannot be opened.

### Expected Behavior

Either we remove support for these buttons from the ImGui::Hotkey or we find a proper way of capture and sending them through the WndProc callback.

### Logs

None.

### Screenshots / Video

_No response_

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

See #3116, #3420; there are plenty of other examples of users making it so they can't open and close the menu anymore.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #3490: [Bug]: Gravity Gun breaking
### Describe the bug

I have no idea why and how but sometimes the gravity gun stops working. It doesnt tell stuff like "target is not an entity" etc up top it just doesnt do aynthing anymore. sometimes removing custom gun and then switching again makes it work again but now its just completly broken

### Steps To Reproduce

1. Activate gravity gun
2. use it
3. Broken

### Expected Behavior

1. Use it
2. be happy :3

### Logs

No log from this incident

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by Mr-X-GTA**
Depends on https://github.com/Yimura/GTAV-Classes/pull/184

Fixes https://github.com/YimMenu/YimMenu/issues/3490
Fixes https://github.com/YimMenu/YimMenu/issues/3436
Fixes https://github.com/YimMenu/YimMenu/issues/3142

### CODE REVIEW

File: src/views/network/view_player_database.cpp [hunk 1]
```diff
@@ -228,14 +228,9 @@ namespace big
 					ImGui::SliderInt("VIEW_NET_PLAYER_DB_PREFERENCE"_T.data(), &current_player->join_redirect_preference, 1, 10);
 				}
 
-				bool joinable =
-				    player_database_service::is_joinable_session(current_player->session_type, current_player->game_mode);
-
-				ImGui::BeginDisabled(!joinable);
```
Comment (Yahud1) [inline src/views/network/view_player_database.cpp]: Maybe it's worth adding an input inside the player tracking which will be set to 45 seconds by default? so that there would be an opportunity to change the delay from 45 seconds to 1 for example. you can add a description that changing the value from 45 seconds to something else will be undesirable. because until 45 seconds pass we won't know whether this player is in the session or he is already in a mission or something else. and we will have to constantly return to singleplayer. this closes #3488

**Review by Yimura — DISMISSED** [review]

File: src/views/network/view_player_database.cpp [hunk 2]
```diff
@@ -228,14 +228,9 @@ namespace big
...
 				components::button("JOIN_SESSION"_T, [] {
 					session::join_by_rockstar_id(current_player->rockstar_id);
 				});
-				ImGui::EndDisabled();
```
Comment (gir489returns) [inline src/views/network/view_player_database.cpp:238]: #3488 is an invalid issue, please walk these changes back.

**Review by gir489returns — CHANGES_REQUESTED** [review]

**Review by gir489returns — APPROVED** [review]
