### PR TITLE
Hotfix outfit random component crash

### LINKED ISSUE #1118: [Bug]: random outfit crash
### Describe the bug

random outfit crash

### Steps To Reproduce

outfit editor
random

### Expected Behavior

no crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Store

Steam

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### PR DESCRIPTION
**Pull request by Aure7138**
Reimplement SET_PED_RANDOM_COMPONENT_VARIATION with SET_PED_COMPONENT_VARIATION

fixes #1118

The original random component crashes after about 20 clicks, this fix I tested works fine for me

### CODE REVIEW

File: src/views/settings/view_outfit_editor.cpp [hunk 1]
```diff
@@ -4,6 +4,12 @@
 
 namespace big
 {
+	static int range(int lower_bound, int upper_bound)
+	{
+		std::srand(std::chrono::system_clock::now().time_since_epoch().count());
```
Comment (Yimura) [inline src/views/settings/view_outfit_editor.cpp]: Setting the seed every time you call it?

image

File: src/views/settings/view_outfit_editor.cpp [hunk 2]
```diff
@@ -4,6 +4,12 @@
...
+		return rand() % (upper_bound - lower_bound + 1) + lower_bound;
```
Comment (Yimura) [inline src/views/settings/view_outfit_editor.cpp]: You're settings the seed for the `std` version of rand and then here you're using the C version of `rand`.

Use `std::rand` instead of `::rand`.

**Review by Yimura — CHANGES_REQUESTED** [review]

File: src/views/settings/view_outfit_editor.cpp (hunk 2 above)
Comment (Aure7138) [reply src/views/settings/view_outfit_editor.cpp]: you're right, changed

File: src/views/settings/view_outfit_editor.cpp (hunk 1 above)
Comment (Aure7138) [reply src/views/settings/view_outfit_editor.cpp]: Ah, yeah, I moved it into main

**Review by Yimura — APPROVED** [review]
