### PR TITLE
increase navigation_struct name size

### LINKED ISSUE #2852: [Bug]: Clicking on a spoofed host player instantly freeze and crashes the game
### Describe the bug

Click on regular (without any mod menu) host player has no effect. If player has spoofed his host token GTA instantly freeze and crashes.

### Steps To Reproduce

1. Launch GTA V
2. Go to Story Mode
3. Inject YimMenu.dll by Xenos
4. Play freemode any possible way
5. Open Yim Menu HUD, click on spoofed host
6. Get crashed

### Expected Behavior

Works normally

### Logs and/or screenshots
<
```
[08:19:38.1412473][INFO/main.cpp:156] Settings Loaded and logger initialized.
[08:19:38.1419862][INFO/main.cpp:158] Yim's Menu Initializing
[08:19:38.1419919][INFO/main.cpp:159] Git Info
	Branch:	master
	Hash:	dd679010b759b8e43d076e236ab2a9ce00f4ddae
	Date:	Thu Mar 21 23:04:40 2024
[08:19:38.1421722][INFO/main.cpp:171] Windows 10 Pro Version 22H2 (OS Build 19045.4170)
[08:19:38.1565043][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[08:19:38.1566499][INFO/main.cpp:179] Thread pool initialized.
[08:19:38.1679575][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[08:19:38.1680001][INFO/pointers.cpp:1838] Loading pointers instance from cache
[08:19:38.1680024][INFO/pointers.cpp:1847] Pointers cache: Loading 217 fields from the cache
[08:19:38.1680325][DEBUG/module.cpp:55] Waiting for socialclub.dll...
[08:19:38.1759161][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[08:19:38.1759287][INFO/pointers.cpp:1838] Loading pointers instance from cache
[08:19:38.1759307][INFO/pointers.cpp:1847] Pointers cache: Loading 5 fields from the cache
[08:19:38.1759706][INFO/main.cpp:182] Pointers initialized.
[08:19:38.1759755][INFO/main.cpp:189] Disabled anticheat gameskeleton.
[08:19:38.1761340][INFO/main.cpp:192] Byte Patch Manager initialized.
[08:19:38.1853827][INFO/main.cpp:195] Renderer initialized.
[08:19:38.2595638][INFO/main.cpp:199] Fiber pool initialized.
[08:19:38.2753520][INFO/main.cpp:202] HTTP Client initialized.
[08:19:38.7899627][DEBUG/thread_pool.cpp:96] Thread 10492 executing font_mgr.cpp:103
[08:19:38.7924207][INFO/main.cpp:205] Translation Service initialized.
[08:19:38.8916552][INFO/main.cpp:208] Hooking initialized.
[08:19:38.9264478][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[08:19:38.9264656][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[08:19:38.9270373][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[08:19:38.9274843][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[08:19:38.9274869][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[08:19:38.9275109][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[08:19:38.9410488][DEBUG/thread_pool.cpp:96] Thread 13152 executing player_database_service.cpp:285
[08:19:38.9412422][INFO/main.cpp:229] Registered service instances...
[08:19:38.9418171][INFO/main.cpp:250] Scripts registered.
[08:19:38.9706903][INFO/main.cpp:253] Hooking enabled.
[08:19:38.9738460][INFO/main.cpp:256] Dynamic native hooker initialized.
[08:19:38.9805653][INFO/main.cpp:260] Lua manager initialized.
[08:19:39.0222744][INFO/backend.cpp:53] Starting script: Self
[08:19:39.0223042][INFO/backend.cpp:78] Starting script: Weapons
[08:19:39.0226799][INFO/backend.cpp:101] Starting script: Vehicles
[08:19:39.0227299][INFO/backend.cpp:117] Starting script: Miscellaneous
[08:19:39.0227752][INFO/backend.cpp:138] Starting script: Remote
[08:19:39.0227832][INFO/backend.cpp:153] Starting script: Ls customs
[08:19:39.0227878][INFO/backend.cpp:165] Starting script: Rainbow paint
[08:19:39.0227944][INFO/backend.cpp:177] Starting script: Disable Control Action
[08:19:39.0228020][INFO/backend.cpp:190] Starting script: World
[08:19:39.0435919][INFO/tunables_service.cpp:36] Loading tunables from cache
[08:20:00.4534644][INFO/queue_dependency.cpp:63] Blocking AC Verifier 9621f0
[08:20:00.4535689][INFO/queue_dependency.cpp:63] Blocking AC Verifier a668ec
[08:20:00.4540788][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f774
[08:20:00.4540990][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f6fc
[08:20:00.4626448][INFO/queue_dependency.cpp:63] Blocking AC Verifier 5ca880
[08:20:32.4726362][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f724
[08:20:32.4726994][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f74c
[08:20:32.4727341][INFO/queue_dependency.cpp:63] Blocking AC Verifier 318b98
[08:20:32.4765639][INFO/queue_dependency.cpp:63] Blocking AC Verifier 335458
[08:20:32.4766345][INFO/queue_dependency.cpp:63] Blocking AC Verifier 335430
[08:20:32.4766694][INFO/queue_dependency.cpp:63] Blocking AC Verifier 4012b8
[08:20:32.4790746][INFO/queue_dependency.cpp:63] Blocking AC Verifier 45acf4
[08:20:32.4792904][INFO/queue_dependency.cpp:63] Blocking AC Verifier 459f38
[08:20:53.5141353][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: MM; DATA: "mmList":"417070584465706C6F796D656E74436C69656E742E646C6C00|475441352E65786500|"
[08:20:53.5142239][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: MM; DATA: "mmList":"5465787453686170696E672E646C6C00|"
[08:21:38.4305988][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[08:21:38.4309022][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":427951988,"type":3136273443,"cat":654913086,"pt":574618152,"slot":0
[08:22:17.2614937][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[08:22:26.4943952][WARN/reaction.cpp:60] Received Modder Detection from Bogdan14062015 (222764275)
[08:22:32.6891234][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF7C9150000 Size: 67215872
ntdll.dll Base Address: 0x7FFAB1BF0000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFAB1160000 Size: 513536
KERNELBASE.dll Base Address: 0x7FFAAF750000 Size: 1255936
apphelp.dll Base Address: 0x7FFAAC830000 Size: 319488
AcLayers.DLL Base Address: 0x7FFA8B760000 Size: 175104
msvcrt.dll Base Address: 0x7FFAB07F0000 Size: 477184
USER32.dll Base Address: 0x7FFAB1820000 Size: 584704
win32u.dll Base Address: 0x7FFAAF5D0000 Size: 42496
GDI32.dll Base Address: 0x7FFAB07C0000 Size: 57856
gdi32full.dll Base Address: 0x7FFAAF400000 Size: 672768
msvcp_win.dll Base Address: 0x7FFAAFB50000 Size: 344064
ucrtbase.dll Base Address: 0x7FFAAFA50000 Size: 735744
SHELL32.dll Base Address: 0x7FFAB0890000 Size: 5921280
SHLWAPI.dll Base Address: 0x7FFAB16F0000 Size: 182784
ADVAPI32.dll Base Address: 0x7FFAB1750000 Size: 434176
sechost.dll Base Address: 0x7FFAB1000000 Size: 422400
RPCRT4.dll Base Address: 0x7FFAB15C0000 Size: 922624
bcrypt.dll Base Address: 0x7FFAAFBF0000 Size: 102912
sfc.dll Base Address: 0x1ECEC4A0000 Size: 0
WINSPOOL.DRV Base Address: 0x7FFA9EED0000 Size: 389632
combase.dll Base Address: 0x7FFAB0460000 Size: 2324480
shcore.dll Base Address: 0x7FFAB02C0000 Size: 476672
sfc_os.DLL Base Address: 0x7FFA8C8A0000 Size: 28672
AcGenral.DLL Base Address: 0x7FFA94FA0000 Size: 243200
ole32.dll Base Address: 0x7FFAB00A0000 Size: 833024
USERENV.dll Base Address: 0x7FFAAF150000 Size: 108032
MPR.dll Base Address: 0x7FFA9E450000 Size: 71168
SspiCli.dll Base Address: 0x7FFAAF180000 Size: 123904
IMM32.DLL Base Address: 0x7FFAB12F0000 Size: 125440
PSAPI.DLL Base Address: 0x7FFAAFC20000 Size: 2048
WS2_32.dll Base Address: 0x7FFAB1B40000 Size: 275456
CRYPT32.dll Base Address: 0x7FFAAF2A0000 Size: 1094656
VERSION.dll Base Address: 0x7FFAA94F0000 Size: 10752
WINTRUST.dll Base Address: 0x7FFAAF600000 Size: 293888
OLEAUT32.dll Base Address: 0x7FFAB1220000 Size: 608768
WININET.dll Base Address: 0x7FFA9F1F0000 Size: 2019840
WINMM.dll Base Address: 0x7FFAA61F0000 Size: 81408
MF.dll Base Address: 0x7FFA781A0000 Size: 340992
MFPlat.DLL Base Address: 0x7FFA8E0B0000 Size: 1409024
cfgmgr32.dll Base Address: 0x7FFAAF700000 Size: 219136
msdmo.dll Base Address: 0x7FFAA3F20000 Size: 13312
MFReadWrite.dll Base Address: 0x7FFA88360000 Size: 918016
PROPSYS.dll Base Address: 0x7FFAAA840000 Size: 631296
DSOUND.dll Base Address: 0x7FFA92E00000 Size: 380928
WTSAPI32.dll Base Address: 0x7FFAAAB30000 Size: 37888
d3d9.dll Base Address: 0x7FFA78340000 Size: 1371648
D3DCOMPILER_43.dll Base Address: 0x7FFA796C0000 Size: 2423296
DINPUT8.dll Base Address: 0x7FFA92BC0000 Size: 169472
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFAAFC30000 Size: 887808
IPHLPAPI.DLL Base Address: 0x7FFAAE650000 Size: 166400
powrprof.dll Base Address: 0x7FFAAF100000 Size: 70656
winmmbase.dll Base Address: 0x7FFA9F9E0000 Size: 95232
kernel.appcore.dll Base Address: 0x7FFAADB00000 Size: 16384
dwmapi.dll Base Address: 0x7FFAACCC0000 Size: 98816
windows.storage.dll Base Address: 0x7FFAAD140000 Size: 5853184
Wldp.dll Base Address: 0x7FFAAEC00000 Size: 96768
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFA82BA0000 Size: 96256
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFAA3440000 Size: 48128
d3dx9_43.dll Base Address: 0x7FFA83090000 Size: 2280960
OPENGL32.dll Base Address: 0x7FFA91760000 Size: 909312
GLU32.dll Base Address: 0x7FFA92A20000 Size: 122880
bink2w64.dll Base Address: 0x7FFA8DA80000 Size: 307712
MFCORE.DLL Base Address: 0x7FFA82220000 Size: 3960320
ksuser.dll Base Address: 0x7FFAA1660000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFAAEB70000 Size: 10752
UMPDC.dll Base Address: 0x7FFAAF0E0000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFAAF670000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFA8E360000 Size: 105472
MSASN1.dll Base Address: 0x7FFAAED90000 Size: 34816
inputhost.dll Base Address: 0x7FFAA3180000 Size: 976384
wintypes.dll Base Address: 0x7FFAABAA0000 Size: 487424
CoreMessaging.dll Base Address: 0x7FFAAC4D0000 Size: 607744
CoreUIComponents.dll Base Address: 0x7FFAAC170000 Size: 1795072
ntmarta.dll Base Address: 0x7FFAAE3B0000 Size: 140288
dbghelp.dll Base Address: 0x7FFAAD8E0000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFA967C0000 Size: 136704
CRYPTSP.dll Base Address: 0x7FFAAEB50000 Size: 46080
uxtheme.dll Base Address: 0x7FFAAC9D0000 Size: 382976
rsaenh.dll Base Address: 0x7FFAAE290000 Size: 142336
clbcatq.dll Base Address: 0x7FFAB10A0000 Size: 437760
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFA7D910000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFAB1AE0000 Size: 269312
Normaliz.dll Base Address: 0x7FFAB1150000 Size: 512
WINHTTP.dll Base Address: 0x7FFAA8DC0000 Size: 845312
Secur32.dll Base Address: 0x7FFA9EEC0000 Size: 11264
VCRUNTIME140.dll Base Address: 0x7FFAAABF0000 Size: 73728
MSVCP140.dll Base Address: 0x7FFA94520000 Size: 340480
VCRUNTIME140_1.dll Base Address: 0x7FFAAC7E0000 Size: 15360
NSI.dll Base Address: 0x7FFAB01D0000 Size: 7680
dhcpcsvc6.DLL Base Address: 0x7FFAA8FD0000 Size: 23552
dhcpcsvc.DLL Base Address: 0x7FFAA9650000 Size: 61440
amsi.dll Base Address: 0x7FFA9C150000 Size: 62464
profapi.dll Base Address: 0x7FFAAF1D0000 Size: 88064
MpOav.dll Base Address: 0x7FFA9BFE0000 Size: 212992
mswsock.dll Base Address: 0x7FFAAE960000 Size: 331776
napinsp.dll Base Address: 0x7FFA9F790000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFAA3CD0000 Size: 66048
wshbth.dll Base Address: 0x7FFA93280000 Size: 43008
NLAapi.dll Base Address: 0x7FFAAAB50000 Size: 68608
DNSAPI.dll Base Address: 0x7FFAAE690000 Size: 600576
winrnr.dll Base Address: 0x7FFAA6180000 Size: 32768
dxcore.dll Base Address: 0x7FFAA6670000 Size: 150016
D3D11.DLL Base Address: 0x7FFAAACC0000 Size: 1853440
dxgi.dll Base Address: 0x7FFAADB50000 Size: 614912
DEVOBJ.dll Base Address: 0x7FFAAEF60000 Size: 132608
D3D10_1.DLL Base Address: 0x7FFAA3390000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFAA66D0000 Size: 7680
MSCTF.dll Base Address: 0x7FFAB19C0000 Size: 864768
textinputframework.dll Base Address: 0x7FFAA3BD0000 Size: 722944
WINSTA.dll Base Address: 0x7FFAAF080000 Size: 190976
aticfx64.dll Base Address: 0x7FFAA6370000 Size: 1123840
atiuxp64.dll Base Address: 0x7FFAA5F50000 Size: 190464
atidxx64.dll Base Address: 0x7FFAA3F80000 Size: 11699712
amdihk64.dll Base Address: 0x7FFAA27A0000 Size: 117248
rasadhlp.dll Base Address: 0x7FFAA1BF0000 Size: 7168
fwpuclnt.dll Base Address: 0x7FFAA2270000 Size: 283648
D3DSCache.dll Base Address: 0x7FFAA15C0000 Size: 94208
twinapi.appcore.dll Base Address: 0x7FFAA8780000 Size: 1457664
HID.DLL Base Address: 0x7FFAADAD0000 Size: 20480
MMDevApi.dll Base Address: 0x7FFAA84C0000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFA8D7A0000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFA9CD30000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFAACA90000 Size: 31744
Windows.UI.dll Base Address: 0x7FFAA3DA0000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFAA8990000 Size: 450048
avrt.dll Base Address: 0x7FFAA9560000 Size: 5632
imagehlp.dll Base Address: 0x7FFAB1800000 Size: 45056
gpapi.dll Base Address: 0x7FFAADB20000 Size: 69120
cryptnet.dll Base Address: 0x7FFAA6630000 Size: 135168
WINNSI.DLL Base Address: 0x7FFAAA790000 Size: 11776
socialclub.dll Base Address: 0x7FFA87A50000 Size: 2692608
chrome_elf.dll Base Address: 0x7FFA876E0000 Size: 901120
libcef.dll Base Address: 0x7FFA52830000 Size: 151009280
COMDLG32.dll Base Address: 0x7FFAB01E0000 Size: 684032
NETAPI32.dll Base Address: 0x7FFA9E2D0000 Size: 47616
UIAutomationCore.DLL Base Address: 0x7FFA8E640000 Size: 2040832
OLEACC.dll Base Address: 0x7FFA9F8D0000 Size: 260608
DWrite.dll Base Address: 0x7FFA98260000 Size: 1601024
ncrypt.dll Base Address: 0x7FFAAEC70000 Size: 102400
urlmon.dll Base Address: 0x7FFAA2320000 Size: 1281536
USP10.dll Base Address: 0x7FFAA60D0000 Size: 512
dxva2.dll Base Address: 0x7FFA8FBA0000 Size: 96256
wevtapi.dll Base Address: 0x7FFAAA470000 Size: 296960
CRYPTUI.dll Base Address: 0x7FFA794C0000 Size: 246272
ESENT.dll Base Address: 0x7FFAA0DD0000 Size: 2585088
COMCTL32.dll Base Address: 0x7FFAA6840000 Size: 560128
srvcli.dll Base Address: 0x7FFAA22F0000 Size: 54272
iertutil.dll Base Address: 0x7FFAA2A30000 Size: 551424
netutils.dll Base Address: 0x7FFAAE760000 Size: 19456
credui.dll Base Address: 0x7FFA8FB80000 Size: 55808
DSROLE.DLL Base Address: 0x7FFAAAAF0000 Size: 7680
WKSCLI.DLL Base Address: 0x7FFAAE3F0000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFA9D6C0000 Size: 61440
NTASN1.dll Base Address: 0x7FFAAEC30000 Size: 81408
FirewallAPI.dll Base Address: 0x7FFAADE80000 Size: 329728
fwbase.dll Base Address: 0x7FFAADE40000 Size: 151552
FWPolicyIOMgr.dll Base Address: 0x7FFAA0020000 Size: 205824
wdmaud.drv Base Address: 0x7FFAA3F30000 Size: 193024
msacm32.drv Base Address: 0x7FFAAA1D0000 Size: 17920
MSACM32.dll Base Address: 0x7FFAA60B0000 Size: 74240
midimap.dll Base Address: 0x7FFAA7E80000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFA93CC0000 Size: 42496
wbemprox.dll Base Address: 0x7FFA9E470000 Size: 27648
wbemcomn.dll Base Address: 0x7FFAA0CA0000 Size: 328704
wbemsvc.dll Base Address: 0x7FFA9CB10000 Size: 7168
fastprox.dll Base Address: 0x7FFA9CF90000 Size: 708608
mfsrcsnk.dll Base Address: 0x7FFA86590000 Size: 1873408
CompPkgSup.DLL Base Address: 0x7FFAA2520000 Size: 152576
Windows.Media.dll Base Address: 0x7FFA66B70000 Size: 5271040
Windows.ApplicationModel.dll Base Address: 0x7FFA98840000 Size: 556544
mp3dmod.dll Base Address: 0x7FFAA34B0000 Size: 58880
AppXDeploymentClient.dll Base Address: 0x7FFAA9370000 Size: 658432
TextShaping.dll Base Address: 0x7FFAA0490000 Size: 304640
YimMenu.dll Base Address: 0x7FFA7CF00000 Size: 7955968
D3DCOMPILER_47.dll Base Address: 0x7FFAAAF30000 Size: 3396608
MSVCP140_2.dll Base Address: 0x7FFAA0B90000 Size: 196096
winbrand.dll Base Address: 0x7FFAAAC40000 Size: 161280
xinput1_4.dll Base Address: 0x7FFAA3460000 Size: 30208
schannel.DLL Base Address: 0x7FFAAE1A0000 Size: 486400
mskeyprotect.dll Base Address: 0x7FFA9A0D0000 Size: 44544
ncryptsslp.dll Base Address: 0x7FFA9A3A0000 Size: 78848
toxmod.dll Base Address: 0x7FFAA3480000 Size: 106496
opusenc.dll Base Address: 0x7FFAAA1C0000 Size: 32768
fvad.dll Base Address: 0x7FFAA7360000 Size: 14848
libcurl.dll Base Address: 0x7FFA9E0B0000 Size: 367616
opus.dll Base Address: 0x7FFA99200000 Size: 311296
zlib1.dll Base Address: 0x7FFAA3370000 Size: 54784
Dumping registers:
RAX: 0x0
RCX: 0x1EC8B250000
RDX: 0x7FF7CBAC8DA0
RBX: 0x9E6EB4D3C8
RSI: 0x7FF7CBAC5DD0
RDI: 0x12
RSP: 0x9E6EB4CBA8
RBP: 0x7FF7CBAC8DA0
R8:  0x7FF7CBAC5DD0
R9:  0x5DD
R10: 0x1EC8C315C80
R11: 0x7FF7CBAC8DA0
R12: 0x7FF7CBADB8F0
R13: 0x0
R14: 0x1EC8B364D60
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x1A2CF8 0x7FFA7D0A2CF8
[1]	GTA5.exe+0x16D79BA 0x7FF7CA8279BA
[2]	GTA5.exe+0x16CF250 0x7FF7CA81F250
[3]	GTA5.exe+0x16D490C 0x7FF7CA82490C
[4]	GTA5.exe+0x13FCC39 0x7FF7CA54CC39
[5]	GTA5.exe+0x16D4A39 0x7FF7CA824A39
[6]	GTA5.exe+0x13FD016 0x7FF7CA54D016
[7]	YimMenu.dll+0x1A1B90 0x7FFA7D0A1B90
[8]	GTA5.exe+0x13FD0C9 0x7FF7CA54D0C9
[9]	GTA5.exe+0x13FCDE2 0x7FF7CA54CDE2
[10]	GTA5.exe+0x1427AB7 0x7FF7CA577AB7
[11]	GTA5.exe+0x10C6D98 0x7FF7CA216D98
[12]	GTA5.exe+0x162FA85 0x7FF7CA77FA85
[13]	GTA5.exe+0x162F2B7 0x7FF7CA77F2B7
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------

[08:23:00.2348378][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[08:23:00.2349170][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":427951988,"type":3136273443,"cat":654913086,"pt":574688461,"slot":0
[08:24:04.5184810][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[08:24:04.5185898][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":427951988,"type":3136273443,"cat":654913086,"pt":574729597,"slot":0
[08:25:40.1651542][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[08:25:49.4697423][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":427951988,"type":3136273443,"cat":654913086,"pt":574788055,"slot":0
[08:26:04.6270672][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[08:26:33.1093707][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":427951988,"type":3136273443,"cat":654913086,"pt":574831479,"slot":0
[08:26:33.4416423][DEBUG/script_function.cpp:35] Found pattern RSD in script PauseMenu_Multiplayer
[08:26:44.0537791][WARN/reaction.cpp:60] Received Modder Detection from ArtemMladshii (203196251)
[08:26:44.0538620][WARN/notify.hpp:67] Blocked invalid sector position (sector node) X: 0 Y: 25056 player_sector_pos_x: 33.0725 player_sector_pos_y: 47.5648 crash from ArtemMladshii (203196251)
[08:26:44.0538708][WARN/reaction.cpp:45] ArtemMladshii has been timed out
[08:27:07.8854318][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[08:27:07.8855094][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":427951988,"type":3136273443,"cat":654913086,"pt":574860530,"slot":0
[08:27:18.1458093][WARN/reaction.cpp:60] Received Modder Detection from realjusjay (79535972)
[08:27:20.1587155][WARN/reaction.cpp:60] Received Modder Detection from realjusjay (79535972)
[08:27:46.0127942][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":427951988,"type":3136273443,"cat":654913086,"pt":574887785,"slot":0
[08:28:04.8707534][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[08:28:06.3854818][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF7C9150000 Size: 67215872
ntdll.dll Base Address: 0x7FFAB1BF0000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFAB1160000 Size: 513536
KERNELBASE.dll Base Address: 0x7FFAAF750000 Size: 1255936
apphelp.dll Base Address: 0x7FFAAC830000 Size: 319488
AcLayers.DLL Base Address: 0x7FFA8B760000 Size: 175104
msvcrt.dll Base Address: 0x7FFAB07F0000 Size: 477184
USER32.dll Base Address: 0x7FFAB1820000 Size: 584704
win32u.dll Base Address: 0x7FFAAF5D0000 Size: 42496
GDI32.dll Base Address: 0x7FFAB07C0000 Size: 57856
gdi32full.dll Base Address: 0x7FFAAF400000 Size: 672768
msvcp_win.dll Base Address: 0x7FFAAFB50000 Size: 344064
ucrtbase.dll Base Address: 0x7FFAAFA50000 Size: 735744
SHELL32.dll Base Address: 0x7FFAB0890000 Size: 5921280
SHLWAPI.dll Base Address: 0x7FFAB16F0000 Size: 182784
ADVAPI32.dll Base Address: 0x7FFAB1750000 Size: 434176
sechost.dll Base Address: 0x7FFAB1000000 Size: 422400
RPCRT4.dll Base Address: 0x7FFAB15C0000 Size: 922624
bcrypt.dll Base Address: 0x7FFAAFBF0000 Size: 102912
sfc.dll Base Address: 0x1ECEC4A0000 Size: 0
WINSPOOL.DRV Base Address: 0x7FFA9EED0000 Size: 389632
combase.dll Base Address: 0x7FFAB0460000 Size: 2324480
shcore.dll Base Address: 0x7FFAB02C0000 Size: 476672
sfc_os.DLL Base Address: 0x7FFA8C8A0000 Size: 28672
AcGenral.DLL Base Address: 0x7FFA94FA0000 Size: 243200
ole32.dll Base Address: 0x7FFAB00A0000 Size: 833024
USERENV.dll Base Address: 0x7FFAAF150000 Size: 108032
MPR.dll Base Address: 0x7FFA9E450000 Size: 71168
SspiCli.dll Base Address: 0x7FFAAF180000 Size: 123904
IMM32.DLL Base Address: 0x7FFAB12F0000 Size: 125440
PSAPI.DLL Base Address: 0x7FFAAFC20000 Size: 2048
WS2_32.dll Base Address: 0x7FFAB1B40000 Size: 275456
CRYPT32.dll Base Address: 0x7FFAAF2A0000 Size: 1094656
VERSION.dll Base Address: 0x7FFAA94F0000 Size: 10752
WINTRUST.dll Base Address: 0x7FFAAF600000 Size: 293888
OLEAUT32.dll Base Address: 0x7FFAB1220000 Size: 608768
WININET.dll Base Address: 0x7FFA9F1F0000 Size: 2019840
WINMM.dll Base Address: 0x7FFAA61F0000 Size: 81408
MF.dll Base Address: 0x7FFA781A0000 Size: 340992
MFPlat.DLL Base Address: 0x7FFA8E0B0000 Size: 1409024
cfgmgr32.dll Base Address: 0x7FFAAF700000 Size: 219136
msdmo.dll Base Address: 0x7FFAA3F20000 Size: 13312
MFReadWrite.dll Base Address: 0x7FFA88360000 Size: 918016
PROPSYS.dll Base Address: 0x7FFAAA840000 Size: 631296
DSOUND.dll Base Address: 0x7FFA92E00000 Size: 380928
WTSAPI32.dll Base Address: 0x7FFAAAB30000 Size: 37888
d3d9.dll Base Address: 0x7FFA78340000 Size: 1371648
D3DCOMPILER_43.dll Base Address: 0x7FFA796C0000 Size: 2423296
DINPUT8.dll Base Address: 0x7FFA92BC0000 Size: 169472
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFAAFC30000 Size: 887808
IPHLPAPI.DLL Base Address: 0x7FFAAE650000 Size: 166400
powrprof.dll Base Address: 0x7FFAAF100000 Size: 70656
winmmbase.dll Base Address: 0x7FFA9F9E0000 Size: 95232
kernel.appcore.dll Base Address: 0x7FFAADB00000 Size: 16384
dwmapi.dll Base Address: 0x7FFAACCC0000 Size: 98816
windows.storage.dll Base Address: 0x7FFAAD140000 Size: 5853184
Wldp.dll Base Address: 0x7FFAAEC00000 Size: 96768
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFA82BA0000 Size: 96256
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFAA3440000 Size: 48128
d3dx9_43.dll Base Address: 0x7FFA83090000 Size: 2280960
OPENGL32.dll Base Address: 0x7FFA91760000 Size: 909312
GLU32.dll Base Address: 0x7FFA92A20000 Size: 122880
bink2w64.dll Base Address: 0x7FFA8DA80000 Size: 307712
MFCORE.DLL Base Address: 0x7FFA82220000 Size: 3960320
ksuser.dll Base Address: 0x7FFAA1660000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFAAEB70000 Size: 10752
UMPDC.dll Base Address: 0x7FFAAF0E0000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFAAF670000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFA8E360000 Size: 105472
MSASN1.dll Base Address: 0x7FFAAED90000 Size: 34816
inputhost.dll Base Address: 0x7FFAA3180000 Size: 976384
wintypes.dll Base Address: 0x7FFAABAA0000 Size: 487424
CoreMessaging.dll Base Address: 0x7FFAAC4D0000 Size: 607744
CoreUIComponents.dll Base Address: 0x7FFAAC170000 Size: 1795072
ntmarta.dll Base Address: 0x7FFAAE3B0000 Size: 140288
dbghelp.dll Base Address: 0x7FFAAD8E0000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFA967C0000 Size: 136704
CRYPTSP.dll Base Address: 0x7FFAAEB50000 Size: 46080
uxtheme.dll Base Address: 0x7FFAAC9D0000 Size: 382976
rsaenh.dll Base Address: 0x7FFAAE290000 Size: 142336
clbcatq.dll Base Address: 0x7FFAB10A0000 Size: 437760
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFA7D910000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFAB1AE0000 Size: 269312
Normaliz.dll Base Address: 0x7FFAB1150000 Size: 512
WINHTTP.dll Base Address: 0x7FFAA8DC0000 Size: 845312
Secur32.dll Base Address: 0x7FFA9EEC0000 Size: 11264
VCRUNTIME140.dll Base Address: 0x7FFAAABF0000 Size: 73728
MSVCP140.dll Base Address: 0x7FFA94520000 Size: 340480
VCRUNTIME140_1.dll Base Address: 0x7FFAAC7E0000 Size: 15360
NSI.dll Base Address: 0x7FFAB01D0000 Size: 7680
dhcpcsvc6.DLL Base Address: 0x7FFAA8FD0000 Size: 23552
dhcpcsvc.DLL Base Address: 0x7FFAA9650000 Size: 61440
amsi.dll Base Address: 0x7FFA9C150000 Size: 62464
profapi.dll Base Address: 0x7FFAAF1D0000 Size: 88064
MpOav.dll Base Address: 0x7FFA9BFE0000 Size: 212992
mswsock.dll Base Address: 0x7FFAAE960000 Size: 331776
napinsp.dll Base Address: 0x7FFA9F790000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFAA3CD0000 Size: 66048
wshbth.dll Base Address: 0x7FFA93280000 Size: 43008
NLAapi.dll Base Address: 0x7FFAAAB50000 Size: 68608
DNSAPI.dll Base Address: 0x7FFAAE690000 Size: 600576
winrnr.dll Base Address: 0x7FFAA6180000 Size: 32768
dxcore.dll Base Address: 0x7FFAA6670000 Size: 150016
D3D11.DLL Base Address: 0x7FFAAACC0000 Size: 1853440
dxgi.dll Base Address: 0x7FFAADB50000 Size: 614912
DEVOBJ.dll Base Address: 0x7FFAAEF60000 Size: 132608
D3D10_1.DLL Base Address: 0x7FFAA3390000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFAA66D0000 Size: 7680
MSCTF.dll Base Address: 0x7FFAB19C0000 Size: 864768
textinputframework.dll Base Address: 0x7FFAA3BD0000 Size: 722944
WINSTA.dll Base Address: 0x7FFAAF080000 Size: 190976
aticfx64.dll Base Address: 0x7FFAA6370000 Size: 1123840
atiuxp64.dll Base Address: 0x7FFAA5F50000 Size: 190464
atidxx64.dll Base Address: 0x7FFAA3F80000 Size: 11699712
amdihk64.dll Base Address: 0x7FFAA27A0000 Size: 117248
rasadhlp.dll Base Address: 0x7FFAA1BF0000 Size: 7168
fwpuclnt.dll Base Address: 0x7FFAA2270000 Size: 283648
D3DSCache.dll Base Address: 0x7FFAA15C0000 Size: 94208
twinapi.appcore.dll Base Address: 0x7FFAA8780000 Size: 1457664
HID.DLL Base Address: 0x7FFAADAD0000 Size: 20480
MMDevApi.dll Base Address: 0x7FFAA84C0000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFA8D7A0000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFA9CD30000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFAACA90000 Size: 31744
Windows.UI.dll Base Address: 0x7FFAA3DA0000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFAA8990000 Size: 450048
avrt.dll Base Address: 0x7FFAA9560000 Size: 5632
imagehlp.dll Base Address: 0x7FFAB1800000 Size: 45056
gpapi.dll Base Address: 0x7FFAADB20000 Size: 69120
cryptnet.dll Base Address: 0x7FFAA6630000 Size: 135168
WINNSI.DLL Base Address: 0x7FFAAA790000 Size: 11776
socialclub.dll Base Address: 0x7FFA87A50000 Size: 2692608
chrome_elf.dll Base Address: 0x7FFA876E0000 Size: 901120
libcef.dll Base Address: 0x7FFA52830000 Size: 151009280
COMDLG32.dll Base Address: 0x7FFAB01E0000 Size: 684032
NETAPI32.dll Base Address: 0x7FFA9E2D0000 Size: 47616
UIAutomationCore.DLL Base Address: 0x7FFA8E640000 Size: 2040832
OLEACC.dll Base Address: 0x7FFA9F8D0000 Size: 260608
DWrite.dll Base Address: 0x7FFA98260000 Size: 1601024
ncrypt.dll Base Address: 0x7FFAAEC70000 Size: 102400
urlmon.dll Base Address: 0x7FFAA2320000 Size: 1281536
USP10.dll Base Address: 0x7FFAA60D0000 Size: 512
dxva2.dll Base Address: 0x7FFA8FBA0000 Size: 96256
wevtapi.dll Base Address: 0x7FFAAA470000 Size: 296960
CRYPTUI.dll Base Address: 0x7FFA794C0000 Size: 246272
ESENT.dll Base Address: 0x7FFAA0DD0000 Size: 2585088
COMCTL32.dll Base Address: 0x7FFAA6840000 Size: 560128
srvcli.dll Base Address: 0x7FFAA22F0000 Size: 54272
iertutil.dll Base Address: 0x7FFAA2A30000 Size: 551424
netutils.dll Base Address: 0x7FFAAE760000 Size: 19456
credui.dll Base Address: 0x7FFA8FB80000 Size: 55808
DSROLE.DLL Base Address: 0x7FFAAAAF0000 Size: 7680
WKSCLI.DLL Base Address: 0x7FFAAE3F0000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFA9D6C0000 Size: 61440
NTASN1.dll Base Address: 0x7FFAAEC30000 Size: 81408
FirewallAPI.dll Base Address: 0x7FFAADE80000 Size: 329728
fwbase.dll Base Address: 0x7FFAADE40000 Size: 151552
FWPolicyIOMgr.dll Base Address: 0x7FFAA0020000 Size: 205824
wdmaud.drv Base Address: 0x7FFAA3F30000 Size: 193024
msacm32.drv Base Address: 0x7FFAAA1D0000 Size: 17920
MSACM32.dll Base Address: 0x7FFAA60B0000 Size: 74240
midimap.dll Base Address: 0x7FFAA7E80000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFA93CC0000 Size: 42496
wbemprox.dll Base Address: 0x7FFA9E470000 Size: 27648
wbemcomn.dll Base Address: 0x7FFAA0CA0000 Size: 328704
wbemsvc.dll Base Address: 0x7FFA9CB10000 Size: 7168
fastprox.dll Base Address: 0x7FFA9CF90000 Size: 708608
mfsrcsnk.dll Base Address: 0x7FFA86590000 Size: 1873408
CompPkgSup.DLL Base Address: 0x7FFAA2520000 Size: 152576
Windows.Media.dll Base Address: 0x7FFA66B70000 Size: 5271040
Windows.ApplicationModel.dll Base Address: 0x7FFA98840000 Size: 556544
mp3dmod.dll Base Address: 0x7FFAA34B0000 Size: 58880
AppXDeploymentClient.dll Base Address: 0x7FFAA9370000 Size: 658432
TextShaping.dll Base Address: 0x7FFAA0490000 Size: 304640
YimMenu.dll Base Address: 0x7FFA7CF00000 Size: 7955968
D3DCOMPILER_47.dll Base Address: 0x7FFAAAF30000 Size: 3396608
MSVCP140_2.dll Base Address: 0x7FFAA0B90000 Size: 196096
winbrand.dll Base Address: 0x7FFAAAC40000 Size: 161280
xinput1_4.dll Base Address: 0x7FFAA3460000 Size: 30208
schannel.DLL Base Address: 0x7FFAAE1A0000 Size: 486400
mskeyprotect.dll Base Address: 0x7FFA9A0D0000 Size: 44544
ncryptsslp.dll Base Address: 0x7FFA9A3A0000 Size: 78848
toxmod.dll Base Address: 0x7FFAA3480000 Size: 106496
opusenc.dll Base Address: 0x7FFAAA1C0000 Size: 32768
fvad.dll Base Address: 0x7FFAA7360000 Size: 14848
libcurl.dll Base Address: 0x7FFA9E0B0000 Size: 367616
opus.dll Base Address: 0x7FFA99200000 Size: 311296
zlib1.dll Base Address: 0x7FFAA3370000 Size: 54784
Dumping registers:
RAX: 0x0
RCX: 0x1EC8B250000
RDX: 0x7FF7CBAC8DA0
RBX: 0x9E6EB4D3C8
RSI: 0x7FF7CBAC5DD0
RDI: 0x12
RSP: 0x9E6EB4CBA8
RBP: 0x7FF7CBAC8DA0
R8:  0x7FF7CBAC5DD0
R9:  0x5DD
R10: 0x1EC8C315C80
R11: 0x7FF7CBAC8DA0
R12: 0x7FF7CBADB8F0
R13: 0x0
R14: 0x1EC8B364D60
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x1A2CF8 0x7FFA7D0A2CF8
[1]	GTA5.exe+0x16D79BA 0x7FF7CA8279BA
[2]	GTA5.exe+0x16CF250 0x7FF7CA81F250
[3]	GTA5.exe+0x16D490C 0x7FF7CA82490C
[4]	GTA5.exe+0x13FCC39 0x7FF7CA54CC39
[5]	GTA5.exe+0x16D4A39 0x7FF7CA824A39
[6]	GTA5.exe+0x13FD016 0x7FF7CA54D016
[7]	YimMenu.dll+0x1A1B90 0x7FFA7D0A1B90
[8]	GTA5.exe+0x13FD0C9 0x7FF7CA54D0C9
[9]	GTA5.exe+0x13FCDE2 0x7FF7CA54CDE2
[10]	GTA5.exe+0x1427AB7 0x7FF7CA577AB7
[11]	GTA5.exe+0x10C6D98 0x7FF7CA216D98
[12]	GTA5.exe+0x162FA85 0x7FF7CA77FA85
[13]	GTA5.exe+0x162F2B7 0x7FF7CA77F2B7
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x7FFA005D8FD1
RCX: 0x1ED64F4CFD8
RDX: 0x9E703FF768
RBX: 0x9E703FF738
RSI: 0x9E703FF768
RDI: 0x1ED64F4CFA8
RSP: 0x9E703FF6D0
RBP: 0x0
R8:  0x1ECEC4F1E00
R9:  0x1
R10: 0x8000
R11: 0x9E703FF670
R12: 0x1B0
R13: 0x0
R14: 0x1ECB8314040
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x1631F0 0x7FFA7D0631F0
[1]	YimMenu.dll+0x5369D5 0x7FFA7D4369D5
[2]	YimMenu.dll+0x161FEF 0x7FFA7D061FEF
[3]	YimMenu.dll+0x17B5B3 0x7FFA7D07B5B3
[4]	GTA5.exe+0x139671E 0x7FF7CA4E671E
[5]	GTA5.exe+0x7EDF51 0x7FF7C993DF51
[6]	GTA5.exe+0x167B7FD 0x7FF7CA7CB7FD
[7]	GTA5.exe+0x167B71A 0x7FF7CA7CB71A
[8]	GTA5.exe+0x1655EE5 0x7FF7CA7A5EE5
[9]	GTA5.exe+0x1656856 0x7FF7CA7A6856
[10]	GTA5.exe+0x165F832 0x7FF7CA7AF832
[11]	GTA5.exe+0x130E95A 0x7FF7CA45E95A
[12]	KERNEL32.DLL BaseThreadInitThunk
[13]	ntdll.dll RtlUserThreadStart
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------

[08:28:06.3860732][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF7C9150000 Size: 67215872
ntdll.dll Base Address: 0x7FFAB1BF0000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFAB1160000 Size: 513536
KERNELBASE.dll Base Address: 0x7FFAAF750000 Size: 1255936
apphelp.dll Base Address: 0x7FFAAC830000 Size: 319488
AcLayers.DLL Base Address: 0x7FFA8B760000 Size: 175104
msvcrt.dll Base Address: 0x7FFAB07F0000 Size: 477184
USER32.dll Base Address: 0x7FFAB1820000 Size: 584704
win32u.dll Base Address: 0x7FFAAF5D0000 Size: 42496
GDI32.dll Base Address: 0x7FFAB07C0000 Size: 57856
gdi32full.dll Base Address: 0x7FFAAF400000 Size: 672768
msvcp_win.dll Base Address: 0x7FFAAFB50000 Size: 344064
ucrtbase.dll Base Address: 0x7FFAAFA50000 Size: 735744
SHELL32.dll Base Address: 0x7FFAB0890000 Size: 5921280
SHLWAPI.dll Base Address: 0x7FFAB16F0000 Size: 182784
ADVAPI32.dll Base Address: 0x7FFAB1750000 Size: 434176
sechost.dll Base Address: 0x7FFAB1000000 Size: 422400
RPCRT4.dll Base Address: 0x7FFAB15C0000 Size: 922624
bcrypt.dll Base Address: 0x7FFAAFBF0000 Size: 102912
sfc.dll Base Address: 0x1ECEC4A0000 Size: 0
WINSPOOL.DRV Base Address: 0x7FFA9EED0000 Size: 389632
combase.dll Base Address: 0x7FFAB0460000 Size: 2324480
shcore.dll Base Address: 0x7FFAB02C0000 Size: 476672
sfc_os.DLL Base Address: 0x7FFA8C8A0000 Size: 28672
AcGenral.DLL Base Address: 0x7FFA94FA0000 Size: 243200
ole32.dll Base Address: 0x7FFAB00A0000 Size: 833024
USERENV.dll Base Address: 0x7FFAAF150000 Size: 108032
MPR.dll Base Address: 0x7FFA9E450000 Size: 71168
SspiCli.dll Base Address: 0x7FFAAF180000 Size: 123904
IMM32.DLL Base Address: 0x7FFAB12F0000 Size: 125440
PSAPI.DLL Base Address: 0x7FFAAFC20000 Size: 2048
WS2_32.dll Base Address: 0x7FFAB1B40000 Size: 275456
CRYPT32.dll Base Address: 0x7FFAAF2A0000 Size: 1094656
VERSION.dll Base Address: 0x7FFAA94F0000 Size: 10752
WINTRUST.dll Base Address: 0x7FFAAF600000 Size: 293888
OLEAUT32.dll Base Address: 0x7FFAB1220000 Size: 608768
WININET.dll Base Address: 0x7FFA9F1F0000 Size: 2019840
WINMM.dll Base Address: 0x7FFAA61F0000 Size: 81408
MF.dll Base Address: 0x7FFA781A0000 Size: 340992
MFPlat.DLL Base Address: 0x7FFA8E0B0000 Size: 1409024
cfgmgr32.dll Base Address: 0x7FFAAF700000 Size: 219136
msdmo.dll Base Address: 0x7FFAA3F20000 Size: 13312
MFReadWrite.dll Base Address: 0x7FFA88360000 Size: 918016
PROPSYS.dll Base Address: 0x7FFAAA840000 Size: 631296
DSOUND.dll Base Address: 0x7FFA92E00000 Size: 380928
WTSAPI32.dll Base Address: 0x7FFAAAB30000 Size: 37888
d3d9.dll Base Address: 0x7FFA78340000 Size: 1371648
D3DCOMPILER_43.dll Base Address: 0x7FFA796C0000 Size: 2423296
DINPUT8.dll Base Address: 0x7FFA92BC0000 Size: 169472
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFAAFC30000 Size: 887808
IPHLPAPI.DLL Base Address: 0x7FFAAE650000 Size: 166400
powrprof.dll Base Address: 0x7FFAAF100000 Size: 70656
winmmbase.dll Base Address: 0x7FFA9F9E0000 Size: 95232
kernel.appcore.dll Base Address: 0x7FFAADB00000 Size: 16384
dwmapi.dll Base Address: 0x7FFAACCC0000 Size: 98816
windows.storage.dll Base Address: 0x7FFAAD140000 Size: 5853184
Wldp.dll Base Address: 0x7FFAAEC00000 Size: 96768
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFA82BA0000 Size: 96256
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFAA3440000 Size: 48128
d3dx9_43.dll Base Address: 0x7FFA83090000 Size: 2280960
OPENGL32.dll Base Address: 0x7FFA91760000 Size: 909312
GLU32.dll Base Address: 0x7FFA92A20000 Size: 122880
bink2w64.dll Base Address: 0x7FFA8DA80000 Size: 307712
MFCORE.DLL Base Address: 0x7FFA82220000 Size: 3960320
ksuser.dll Base Address: 0x7FFAA1660000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFAAEB70000 Size: 10752
UMPDC.dll Base Address: 0x7FFAAF0E0000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFAAF670000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFA8E360000 Size: 105472
MSASN1.dll Base Address: 0x7FFAAED90000 Size: 34816
inputhost.dll Base Address: 0x7FFAA3180000 Size: 976384
wintypes.dll Base Address: 0x7FFAABAA0000 Size: 487424
CoreMessaging.dll Base Address: 0x7FFAAC4D0000 Size: 607744
CoreUIComponents.dll Base Address: 0x7FFAAC170000 Size: 1795072
ntmarta.dll Base Address: 0x7FFAAE3B0000 Size: 140288
dbghelp.dll Base Address: 0x7FFAAD8E0000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFA967C0000 Size: 136704
CRYPTSP.dll Base Address: 0x7FFAAEB50000 Size: 46080
uxtheme.dll Base Address: 0x7FFAAC9D0000 Size: 382976
rsaenh.dll Base Address: 0x7FFAAE290000 Size: 142336
clbcatq.dll Base Address: 0x7FFAB10A0000 Size: 437760
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFA7D910000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFAB1AE0000 Size: 269312
Normaliz.dll Base Address: 0x7FFAB1150000 Size: 512
WINHTTP.dll Base Address: 0x7FFAA8DC0000 Size: 845312
Secur32.dll Base Address: 0x7FFA9EEC0000 Size: 11264
VCRUNTIME140.dll Base Address: 0x7FFAAABF0000 Size: 73728
MSVCP140.dll Base Address: 0x7FFA94520000 Size: 340480
VCRUNTIME140_1.dll Base Address: 0x7FFAAC7E0000 Size: 15360
NSI.dll Base Address: 0x7FFAB01D0000 Size: 7680
dhcpcsvc6.DLL Base Address: 0x7FFAA8FD0000 Size: 23552
dhcpcsvc.DLL Base Address: 0x7FFAA9650000 Size: 61440
amsi.dll Base Address: 0x7FFA9C150000 Size: 62464
profapi.dll Base Address: 0x7FFAAF1D0000 Size: 88064
MpOav.dll Base Address: 0x7FFA9BFE0000 Size: 212992
mswsock.dll Base Address: 0x7FFAAE960000 Size: 331776
napinsp.dll Base Address: 0x7FFA9F790000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFAA3CD0000 Size: 66048
wshbth.dll Base Address: 0x7FFA93280000 Size: 43008
NLAapi.dll Base Address: 0x7FFAAAB50000 Size: 68608
DNSAPI.dll Base Address: 0x7FFAAE690000 Size: 600576
winrnr.dll Base Address: 0x7FFAA6180000 Size: 32768
dxcore.dll Base Address: 0x7FFAA6670000 Size: 150016
D3D11.DLL Base Address: 0x7FFAAACC0000 Size: 1853440
dxgi.dll Base Address: 0x7FFAADB50000 Size: 614912
DEVOBJ.dll Base Address: 0x7FFAAEF60000 Size: 132608
D3D10_1.DLL Base Address: 0x7FFAA3390000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFAA66D0000 Size: 7680
MSCTF.dll Base Address: 0x7FFAB19C0000 Size: 864768
textinputframework.dll Base Address: 0x7FFAA3BD0000 Size: 722944
WINSTA.dll Base Address: 0x7FFAAF080000 Size: 190976
aticfx64.dll Base Address: 0x7FFAA6370000 Size: 1123840
atiuxp64.dll Base Address: 0x7FFAA5F50000 Size: 190464
atidxx64.dll Base Address: 0x7FFAA3F80000 Size: 11699712
amdihk64.dll Base Address: 0x7FFAA27A0000 Size: 117248
rasadhlp.dll Base Address: 0x7FFAA1BF0000 Size: 7168
fwpuclnt.dll Base Address: 0x7FFAA2270000 Size: 283648
D3DSCache.dll Base Address: 0x7FFAA15C0000 Size: 94208
twinapi.appcore.dll Base Address: 0x7FFAA8780000 Size: 1457664
HID.DLL Base Address: 0x7FFAADAD0000 Size: 20480
MMDevApi.dll Base Address: 0x7FFAA84C0000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFA8D7A0000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFA9CD30000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFAACA90000 Size: 31744
Windows.UI.dll Base Address: 0x7FFAA3DA0000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFAA8990000 Size: 450048
avrt.dll Base Address: 0x7FFAA9560000 Size: 5632
imagehlp.dll Base Address: 0x7FFAB1800000 Size: 45056
gpapi.dll Base Address: 0x7FFAADB20000 Size: 69120
cryptnet.dll Base Address: 0x7FFAA6630000 Size: 135168
WINNSI.DLL Base Address: 0x7FFAAA790000 Size: 11776
socialclub.dll Base Address: 0x7FFA87A50000 Size: 2692608
chrome_elf.dll Base Address: 0x7FFA876E0000 Size: 901120
libcef.dll Base Address: 0x7FFA52830000 Size: 151009280
COMDLG32.dll Base Address: 0x7FFAB01E0000 Size: 684032
NETAPI32.dll Base Address: 0x7FFA9E2D0000 Size: 47616
UIAutomationCore.DLL Base Address: 0x7FFA8E640000 Size: 2040832
OLEACC.dll Base Address: 0x7FFA9F8D0000 Size: 260608
DWrite.dll Base Address: 0x7FFA98260000 Size: 1601024
ncrypt.dll Base Address: 0x7FFAAEC70000 Size: 102400
urlmon.dll Base Address: 0x7FFAA2320000 Size: 1281536
USP10.dll Base Address: 0x7FFAA60D0000 Size: 512
dxva2.dll Base Address: 0x7FFA8FBA0000 Size: 96256
wevtapi.dll Base Address: 0x7FFAAA470000 Size: 296960
CRYPTUI.dll Base Address: 0x7FFA794C0000 Size: 246272
ESENT.dll Base Address: 0x7FFAA0DD0000 Size: 2585088
COMCTL32.dll Base Address: 0x7FFAA6840000 Size: 560128
srvcli.dll Base Address: 0x7FFAA22F0000 Size: 54272
iertutil.dll Base Address: 0x7FFAA2A30000 Size: 551424
netutils.dll Base Address: 0x7FFAAE760000 Size: 19456
credui.dll Base Address: 0x7FFA8FB80000 Size: 55808
DSROLE.DLL Base Address: 0x7FFAAAAF0000 Size: 7680
WKSCLI.DLL Base Address: 0x7FFAAE3F0000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFA9D6C0000 Size: 61440
NTASN1.dll Base Address: 0x7FFAAEC30000 Size: 81408
FirewallAPI.dll Base Address: 0x7FFAADE80000 Size: 329728
fwbase.dll Base Address: 0x7FFAADE40000 Size: 151552
FWPolicyIOMgr.dll Base Address: 0x7FFAA0020000 Size: 205824
wdmaud.drv Base Address: 0x7FFAA3F30000 Size: 193024
msacm32.drv Base Address: 0x7FFAAA1D0000 Size: 17920
MSACM32.dll Base Address: 0x7FFAA60B0000 Size: 74240
midimap.dll Base Address: 0x7FFAA7E80000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFA93CC0000 Size: 42496
wbemprox.dll Base Address: 0x7FFA9E470000 Size: 27648
wbemcomn.dll Base Address: 0x7FFAA0CA0000 Size: 328704
wbemsvc.dll Base Address: 0x7FFA9CB10000 Size: 7168
fastprox.dll Base Address: 0x7FFA9CF90000 Size: 708608
mfsrcsnk.dll Base Address: 0x7FFA86590000 Size: 1873408
CompPkgSup.DLL Base Address: 0x7FFAA2520000 Size: 152576
Windows.Media.dll Base Address: 0x7FFA66B70000 Size: 5271040
Windows.ApplicationModel.dll Base Address: 0x7FFA98840000 Size: 556544
mp3dmod.dll Base Address: 0x7FFAA34B0000 Size: 58880
AppXDeploymentClient.dll Base Address: 0x7FFAA9370000 Size: 658432
TextShaping.dll Base Address: 0x7FFAA0490000 Size: 304640
YimMenu.dll Base Address: 0x7FFA7CF00000 Size: 7955968
D3DCOMPILER_47.dll Base Address: 0x7FFAAAF30000 Size: 3396608
MSVCP140_2.dll Base Address: 0x7FFAA0B90000 Size: 196096
winbrand.dll Base Address: 0x7FFAAAC40000 Size: 161280
xinput1_4.dll Base Address: 0x7FFAA3460000 Size: 30208
schannel.DLL Base Address: 0x7FFAAE1A0000 Size: 486400
mskeyprotect.dll Base Address: 0x7FFA9A0D0000 Size: 44544
ncryptsslp.dll Base Address: 0x7FFA9A3A0000 Size: 78848
toxmod.dll Base Address: 0x7FFAA3480000 Size: 106496
opusenc.dll Base Address: 0x7FFAAA1C0000 Size: 32768
fvad.dll Base Address: 0x7FFAA7360000 Size: 14848
libcurl.dll Base Address: 0x7FFA9E0B0000 Size: 367616
opus.dll Base Address: 0x7FFA99200000 Size: 311296
zlib1.dll Base Address: 0x7FFAA3370000 Size: 54784
Dumping registers:
RAX: 0x0
RCX: 0x1EC8B250000
RDX: 0x7FF7CBAC8DA0
RBX: 0x9E6EB4D3C8
RSI: 0x7FF7CBAC5DD0
RDI: 0x12
RSP: 0x9E6EB4CBA8
RBP: 0x7FF7CBAC8DA0
R8:  0x7FF7CBAC5DD0
R9:  0x5DD
R10: 0x1EC8C315C80
R11: 0x7FF7CBAC8DA0
R12: 0x7FF7CBADB8F0
R13: 0x0
R14: 0x1EC8B364D60
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x1A2CF8 0x7FFA7D0A2CF8
[1]	GTA5.exe+0x16D79BA 0x7FF7CA8279BA
[2]	GTA5.exe+0x16CF250 0x7FF7CA81F250
[3]	GTA5.exe+0x16D490C 0x7FF7CA82490C
[4]	GTA5.exe+0x13FCC39 0x7FF7CA54CC39
[5]	GTA5.exe+0x16D4A39 0x7FF7CA824A39
[6]	GTA5.exe+0x13FD016 0x7FF7CA54D016
[7]	YimMenu.dll+0x1A1B90 0x7FFA7D0A1B90
[8]	GTA5.exe+0x13FD0C9 0x7FF7CA54D0C9
[9]	GTA5.exe+0x13FCDE2 0x7FF7CA54CDE2
[10]	GTA5.exe+0x1427AB7 0x7FF7CA577AB7
[11]	GTA5.exe+0x10C6D98 0x7FF7CA216D98
[12]	GTA5.exe+0x162FA85 0x7FF7CA77FA85
[13]	GTA5.exe+0x162F2B7 0x7FF7CA77F2B7
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x7FFA005D8FD1
RCX: 0x1ED64F4CFD8
RDX: 0x9E703FF768
RBX: 0x9E703FF738
RSI: 0x9E703FF768
RDI: 0x1ED64F4CFA8
RSP: 0x9E703FF6D0
RBP: 0x0
R8:  0x1ECEC4F1E00
R9:  0x1
R10: 0x8000
R11: 0x9E703FF670
R12: 0x1B0
R13: 0x0
R14: 0x1ECB8314040
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x1631F0 0x7FFA7D0631F0
[1]	YimMenu.dll+0x5369D5 0x7FFA7D4369D5
[2]	YimMenu.dll+0x161FEF 0x7FFA7D061FEF
[3]	YimMenu.dll+0x17B5B3 0x7FFA7D07B5B3
[4]	GTA5.exe+0x139671E 0x7FF7CA4E671E
[5]	GTA5.exe+0x7EDF51 0x7FF7C993DF51
[6]	GTA5.exe+0x167B7FD 0x7FF7CA7CB7FD
[7]	GTA5.exe+0x167B71A 0x7FF7CA7CB71A
[8]	GTA5.exe+0x1655EE5 0x7FF7CA7A5EE5
[9]	GTA5.exe+0x1656856 0x7FF7CA7A6856
[10]	GTA5.exe+0x165F832 0x7FF7CA7AF832
[11]	GTA5.exe+0x130E95A 0x7FF7CA45E95A
[12]	KERNEL32.DLL BaseThreadInitThunk
[13]	ntdll.dll RtlUserThreadStart
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x1
RCX: 0x7FFA005D8FD1
RDX: 0x9E703FF768
RBX: 0x1ED64F4CF80
RSI: 0x1ED64F4F2C0
RDI: 0x1ED64F516C0
RSP: 0x9E703FF710
RBP: 0x0
R8:  0x1ECEC4F1E00
R9:  0x1
R10: 0x8000
R11: 0x9E703FF670
R12: 0x1B0
R13: 0x0
R14: 0x1ECB8314040
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x536AC2 0x7FFA7D436AC2
[1]	YimMenu.dll+0x161FEF 0x7FFA7D061FEF
[2]	YimMenu.dll+0x17B5B3 0x7FFA7D07B5B3
[3]	GTA5.exe+0x139671E 0x7FF7CA4E671E
[4]	GTA5.exe+0x7EDF51 0x7FF7C993DF51
[5]	GTA5.exe+0x167B7FD 0x7FF7CA7CB7FD
[6]	GTA5.exe+0x167B71A 0x7FF7CA7CB71A
[7]	GTA5.exe+0x1655EE5 0x7FF7CA7A5EE5
[8]	GTA5.exe+0x1656856 0x7FF7CA7A6856
[9]	GTA5.exe+0x165F832 0x7FF7CA7AF832
[10]	GTA5.exe+0x130E95A 0x7FF7CA45E95A
[11]	KERNEL32.DLL BaseThreadInitThunk
[12]	ntdll.dll RtlUserThreadStart
[13]	ntdll.dll RtlUserThreadStart
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------

[08:28:06.3981009][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF7C9150000 Size: 67215872
ntdll.dll Base Address: 0x7FFAB1BF0000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFAB1160000 Size: 513536
KERNELBASE.dll Base Address: 0x7FFAAF750000 Size: 1255936
apphelp.dll Base Address: 0x7FFAAC830000 Size: 319488
AcLayers.DLL Base Address: 0x7FFA8B760000 Size: 175104
msvcrt.dll Base Address: 0x7FFAB07F0000 Size: 477184
USER32.dll Base Address: 0x7FFAB1820000 Size: 584704
win32u.dll Base Address: 0x7FFAAF5D0000 Size: 42496
GDI32.dll Base Address: 0x7FFAB07C0000 Size: 57856
gdi32full.dll Base Address: 0x7FFAAF400000 Size: 672768
msvcp_win.dll Base Address: 0x7FFAAFB50000 Size: 344064
ucrtbase.dll Base Address: 0x7FFAAFA50000 Size: 735744
SHELL32.dll Base Address: 0x7FFAB0890000 Size: 5921280
SHLWAPI.dll Base Address: 0x7FFAB16F0000 Size: 182784
ADVAPI32.dll Base Address: 0x7FFAB1750000 Size: 434176
sechost.dll Base Address: 0x7FFAB1000000 Size: 422400
RPCRT4.dll Base Address: 0x7FFAB15C0000 Size: 922624
bcrypt.dll Base Address: 0x7FFAAFBF0000 Size: 102912
sfc.dll Base Address: 0x1ECEC4A0000 Size: 0
WINSPOOL.DRV Base Address: 0x7FFA9EED0000 Size: 389632
combase.dll Base Address: 0x7FFAB0460000 Size: 2324480
shcore.dll Base Address: 0x7FFAB02C0000 Size: 476672
sfc_os.DLL Base Address: 0x7FFA8C8A0000 Size: 28672
AcGenral.DLL Base Address: 0x7FFA94FA0000 Size: 243200
ole32.dll Base Address: 0x7FFAB00A0000 Size: 833024
USERENV.dll Base Address: 0x7FFAAF150000 Size: 108032
MPR.dll Base Address: 0x7FFA9E450000 Size: 71168
SspiCli.dll Base Address: 0x7FFAAF180000 Size: 123904
IMM32.DLL Base Address: 0x7FFAB12F0000 Size: 125440
PSAPI.DLL Base Address: 0x7FFAAFC20000 Size: 2048
WS2_32.dll Base Address: 0x7FFAB1B40000 Size: 275456
CRYPT32.dll Base Address: 0x7FFAAF2A0000 Size: 1094656
VERSION.dll Base Address: 0x7FFAA94F0000 Size: 10752
WINTRUST.dll Base Address: 0x7FFAAF600000 Size: 293888
OLEAUT32.dll Base Address: 0x7FFAB1220000 Size: 608768
WININET.dll Base Address: 0x7FFA9F1F0000 Size: 2019840
WINMM.dll Base Address: 0x7FFAA61F0000 Size: 81408
MF.dll Base Address: 0x7FFA781A0000 Size: 340992
MFPlat.DLL Base Address: 0x7FFA8E0B0000 Size: 1409024
cfgmgr32.dll Base Address: 0x7FFAAF700000 Size: 219136
msdmo.dll Base Address: 0x7FFAA3F20000 Size: 13312
MFReadWrite.dll Base Address: 0x7FFA88360000 Size: 918016
PROPSYS.dll Base Address: 0x7FFAAA840000 Size: 631296
DSOUND.dll Base Address: 0x7FFA92E00000 Size: 380928
WTSAPI32.dll Base Address: 0x7FFAAAB30000 Size: 37888
d3d9.dll Base Address: 0x7FFA78340000 Size: 1371648
D3DCOMPILER_43.dll Base Address: 0x7FFA796C0000 Size: 2423296
DINPUT8.dll Base Address: 0x7FFA92BC0000 Size: 169472
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFAAFC30000 Size: 887808
IPHLPAPI.DLL Base Address: 0x7FFAAE650000 Size: 166400
powrprof.dll Base Address: 0x7FFAAF100000 Size: 70656
winmmbase.dll Base Address: 0x7FFA9F9E0000 Size: 95232
kernel.appcore.dll Base Address: 0x7FFAADB00000 Size: 16384
dwmapi.dll Base Address: 0x7FFAACCC0000 Size: 98816
windows.storage.dll Base Address: 0x7FFAAD140000 Size: 5853184
Wldp.dll Base Address: 0x7FFAAEC00000 Size: 96768
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFA82BA0000 Size: 96256
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFAA3440000 Size: 48128
d3dx9_43.dll Base Address: 0x7FFA83090000 Size: 2280960
OPENGL32.dll Base Address: 0x7FFA91760000 Size: 909312
GLU32.dll Base Address: 0x7FFA92A20000 Size: 122880
bink2w64.dll Base Address: 0x7FFA8DA80000 Size: 307712
MFCORE.DLL Base Address: 0x7FFA82220000 Size: 3960320
ksuser.dll Base Address: 0x7FFAA1660000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFAAEB70000 Size: 10752
UMPDC.dll Base Address: 0x7FFAAF0E0000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFAAF670000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFA8E360000 Size: 105472
MSASN1.dll Base Address: 0x7FFAAED90000 Size: 34816
inputhost.dll Base Address: 0x7FFAA3180000 Size: 976384
wintypes.dll Base Address: 0x7FFAABAA0000 Size: 487424
CoreMessaging.dll Base Address: 0x7FFAAC4D0000 Size: 607744
CoreUIComponents.dll Base Address: 0x7FFAAC170000 Size: 1795072
ntmarta.dll Base Address: 0x7FFAAE3B0000 Size: 140288
dbghelp.dll Base Address: 0x7FFAAD8E0000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFA967C0000 Size: 136704
CRYPTSP.dll Base Address: 0x7FFAAEB50000 Size: 46080
uxtheme.dll Base Address: 0x7FFAAC9D0000 Size: 382976
rsaenh.dll Base Address: 0x7FFAAE290000 Size: 142336
clbcatq.dll Base Address: 0x7FFAB10A0000 Size: 437760
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFA7D910000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFAB1AE0000 Size: 269312
Normaliz.dll Base Address: 0x7FFAB1150000 Size: 512
WINHTTP.dll Base Address: 0x7FFAA8DC0000 Size: 845312
Secur32.dll Base Address: 0x7FFA9EEC0000 Size: 11264
VCRUNTIME140.dll Base Address: 0x7FFAAABF0000 Size: 73728
MSVCP140.dll Base Address: 0x7FFA94520000 Size: 340480
VCRUNTIME140_1.dll Base Address: 0x7FFAAC7E0000 Size: 15360
NSI.dll Base Address: 0x7FFAB01D0000 Size: 7680
dhcpcsvc6.DLL Base Address: 0x7FFAA8FD0000 Size: 23552
dhcpcsvc.DLL Base Address: 0x7FFAA9650000 Size: 61440
amsi.dll Base Address: 0x7FFA9C150000 Size: 62464
profapi.dll Base Address: 0x7FFAAF1D0000 Size: 88064
MpOav.dll Base Address: 0x7FFA9BFE0000 Size: 212992
mswsock.dll Base Address: 0x7FFAAE960000 Size: 331776
napinsp.dll Base Address: 0x7FFA9F790000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFAA3CD0000 Size: 66048
wshbth.dll Base Address: 0x7FFA93280000 Size: 43008
NLAapi.dll Base Address: 0x7FFAAAB50000 Size: 68608
DNSAPI.dll Base Address: 0x7FFAAE690000 Size: 600576
winrnr.dll Base Address: 0x7FFAA6180000 Size: 32768
dxcore.dll Base Address: 0x7FFAA6670000 Size: 150016
D3D11.DLL Base Address: 0x7FFAAACC0000 Size: 1853440
dxgi.dll Base Address: 0x7FFAADB50000 Size: 614912
DEVOBJ.dll Base Address: 0x7FFAAEF60000 Size: 132608
D3D10_1.DLL Base Address: 0x7FFAA3390000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFAA66D0000 Size: 7680
MSCTF.dll Base Address: 0x7FFAB19C0000 Size: 864768
textinputframework.dll Base Address: 0x7FFAA3BD0000 Size: 722944
WINSTA.dll Base Address: 0x7FFAAF080000 Size: 190976
aticfx64.dll Base Address: 0x7FFAA6370000 Size: 1123840
atiuxp64.dll Base Address: 0x7FFAA5F50000 Size: 190464
atidxx64.dll Base Address: 0x7FFAA3F80000 Size: 11699712
amdihk64.dll Base Address: 0x7FFAA27A0000 Size: 117248
rasadhlp.dll Base Address: 0x7FFAA1BF0000 Size: 7168
fwpuclnt.dll Base Address: 0x7FFAA2270000 Size: 283648
D3DSCache.dll Base Address: 0x7FFAA15C0000 Size: 94208
twinapi.appcore.dll Base Address: 0x7FFAA8780000 Size: 1457664
HID.DLL Base Address: 0x7FFAADAD0000 Size: 20480
MMDevApi.dll Base Address: 0x7FFAA84C0000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFA8D7A0000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFA9CD30000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFAACA90000 Size: 31744
Windows.UI.dll Base Address: 0x7FFAA3DA0000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFAA8990000 Size: 450048
avrt.dll Base Address: 0x7FFAA9560000 Size: 5632
imagehlp.dll Base Address: 0x7FFAB1800000 Size: 45056
gpapi.dll Base Address: 0x7FFAADB20000 Size: 69120
cryptnet.dll Base Address: 0x7FFAA6630000 Size: 135168
WINNSI.DLL Base Address: 0x7FFAAA790000 Size: 11776
socialclub.dll Base Address: 0x7FFA87A50000 Size: 2692608
chrome_elf.dll Base Address: 0x7FFA876E0000 Size: 901120
libcef.dll Base Address: 0x7FFA52830000 Size: 151009280
COMDLG32.dll Base Address: 0x7FFAB01E0000 Size: 684032
NETAPI32.dll Base Address: 0x7FFA9E2D0000 Size: 47616
UIAutomationCore.DLL Base Address: 0x7FFA8E640000 Size: 2040832
OLEACC.dll Base Address: 0x7FFA9F8D0000 Size: 260608
DWrite.dll Base Address: 0x7FFA98260000 Size: 1601024
ncrypt.dll Base Address: 0x7FFAAEC70000 Size: 102400
urlmon.dll Base Address: 0x7FFAA2320000 Size: 1281536
USP10.dll Base Address: 0x7FFAA60D0000 Size: 512
dxva2.dll Base Address: 0x7FFA8FBA0000 Size: 96256
wevtapi.dll Base Address: 0x7FFAAA470000 Size: 296960
CRYPTUI.dll Base Address: 0x7FFA794C0000 Size: 246272
ESENT.dll Base Address: 0x7FFAA0DD0000 Size: 2585088
COMCTL32.dll Base Address: 0x7FFAA6840000 Size: 560128
srvcli.dll Base Address: 0x7FFAA22F0000 Size: 54272
iertutil.dll Base Address: 0x7FFAA2A30000 Size: 551424
netutils.dll Base Address: 0x7FFAAE760000 Size: 19456
credui.dll Base Address: 0x7FFA8FB80000 Size: 55808
DSROLE.DLL Base Address: 0x7FFAAAAF0000 Size: 7680
WKSCLI.DLL Base Address: 0x7FFAAE3F0000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFA9D6C0000 Size: 61440
NTASN1.dll Base Address: 0x7FFAAEC30000 Size: 81408
FirewallAPI.dll Base Address: 0x7FFAADE80000 Size: 329728
fwbase.dll Base Address: 0x7FFAADE40000 Size: 151552
FWPolicyIOMgr.dll Base Address: 0x7FFAA0020000 Size: 205824
wdmaud.drv Base Address: 0x7FFAA3F30000 Size: 193024
msacm32.drv Base Address: 0x7FFAAA1D0000 Size: 17920
MSACM32.dll Base Address: 0x7FFAA60B0000 Size: 74240
midimap.dll Base Address: 0x7FFAA7E80000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFA93CC0000 Size: 42496
wbemprox.dll Base Address: 0x7FFA9E470000 Size: 27648
wbemcomn.dll Base Address: 0x7FFAA0CA0000 Size: 328704
wbemsvc.dll Base Address: 0x7FFA9CB10000 Size: 7168
fastprox.dll Base Address: 0x7FFA9CF90000 Size: 708608
mfsrcsnk.dll Base Address: 0x7FFA86590000 Size: 1873408
CompPkgSup.DLL Base Address: 0x7FFAA2520000 Size: 152576
Windows.Media.dll Base Address: 0x7FFA66B70000 Size: 5271040
Windows.ApplicationModel.dll Base Address: 0x7FFA98840000 Size: 556544
mp3dmod.dll Base Address: 0x7FFAA34B0000 Size: 58880
AppXDeploymentClient.dll Base Address: 0x7FFAA9370000 Size: 658432
TextShaping.dll Base Address: 0x7FFAA0490000 Size: 304640
YimMenu.dll Base Address: 0x7FFA7CF00000 Size: 7955968
D3DCOMPILER_47.dll Base Address: 0x7FFAAAF30000 Size: 3396608
MSVCP140_2.dll Base Address: 0x7FFAA0B90000 Size: 196096
winbrand.dll Base Address: 0x7FFAAAC40000 Size: 161280
xinput1_4.dll Base Address: 0x7FFAA3460000 Size: 30208
schannel.DLL Base Address: 0x7FFAAE1A0000 Size: 486400
mskeyprotect.dll Base Address: 0x7FFA9A0D0000 Size: 44544
ncryptsslp.dll Base Address: 0x7FFA9A3A0000 Size: 78848
toxmod.dll Base Address: 0x7FFAA3480000 Size: 106496
opusenc.dll Base Address: 0x7FFAAA1C0000 Size: 32768
fvad.dll Base Address: 0x7FFAA7360000 Size: 14848
libcurl.dll Base Address: 0x7FFA9E0B0000 Size: 367616
opus.dll Base Address: 0x7FFA99200000 Size: 311296
zlib1.dll Base Address: 0x7FFAA3370000 Size: 54784
Dumping registers:
RAX: 0x0
RCX: 0x1EC8B250000
RDX: 0x7FF7CBAC8DA0
RBX: 0x9E6EB4D3C8
RSI: 0x7FF7CBAC5DD0
RDI: 0x12
RSP: 0x9E6EB4CBA8
RBP: 0x7FF7CBAC8DA0
R8:  0x7FF7CBAC5DD0
R9:  0x5DD
R10: 0x1EC8C315C80
R11: 0x7FF7CBAC8DA0
R12: 0x7FF7CBADB8F0
R13: 0x0
R14: 0x1EC8B364D60
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x1A2CF8 0x7FFA7D0A2CF8
[1]	GTA5.exe+0x16D79BA 0x7FF7CA8279BA
[2]	GTA5.exe+0x16CF250 0x7FF7CA81F250
[3]	GTA5.exe+0x16D490C 0x7FF7CA82490C
[4]	GTA5.exe+0x13FCC39 0x7FF7CA54CC39
[5]	GTA5.exe+0x16D4A39 0x7FF7CA824A39
[6]	GTA5.exe+0x13FD016 0x7FF7CA54D016
[7]	YimMenu.dll+0x1A1B90 0x7FFA7D0A1B90
[8]	GTA5.exe+0x13FD0C9 0x7FF7CA54D0C9
[9]	GTA5.exe+0x13FCDE2 0x7FF7CA54CDE2
[10]	GTA5.exe+0x1427AB7 0x7FF7CA577AB7
[11]	GTA5.exe+0x10C6D98 0x7FF7CA216D98
[12]	GTA5.exe+0x162FA85 0x7FF7CA77FA85
[13]	GTA5.exe+0x162F2B7 0x7FF7CA77F2B7
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x7FFA005D8FD1
RCX: 0x1ED64F4CFD8
RDX: 0x9E703FF768
RBX: 0x9E703FF738
RSI: 0x9E703FF768
RDI: 0x1ED64F4CFA8
RSP: 0x9E703FF6D0
RBP: 0x0
R8:  0x1ECEC4F1E00
R9:  0x1
R10: 0x8000
R11: 0x9E703FF670
R12: 0x1B0
R13: 0x0
R14: 0x1ECB8314040
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x1631F0 0x7FFA7D0631F0
[1]	YimMenu.dll+0x5369D5 0x7FFA7D4369D5
[2]	YimMenu.dll+0x161FEF 0x7FFA7D061FEF
[3]	YimMenu.dll+0x17B5B3 0x7FFA7D07B5B3
[4]	GTA5.exe+0x139671E 0x7FF7CA4E671E
[5]	GTA5.exe+0x7EDF51 0x7FF7C993DF51
[6]	GTA5.exe+0x167B7FD 0x7FF7CA7CB7FD
[7]	GTA5.exe+0x167B71A 0x7FF7CA7CB71A
[8]	GTA5.exe+0x1655EE5 0x7FF7CA7A5EE5
[9]	GTA5.exe+0x1656856 0x7FF7CA7A6856
[10]	GTA5.exe+0x165F832 0x7FF7CA7AF832
[11]	GTA5.exe+0x130E95A 0x7FF7CA45E95A
[12]	KERNEL32.DLL BaseThreadInitThunk
[13]	ntdll.dll RtlUserThreadStart
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x1
RCX: 0x7FFA005D8FD1
RDX: 0x9E703FF768
RBX: 0x1ED64F4CF80
RSI: 0x1ED64F4F2C0
RDI: 0x1ED64F516C0
RSP: 0x9E703FF710
RBP: 0x0
R8:  0x1ECEC4F1E00
R9:  0x1
R10: 0x8000
R11: 0x9E703FF670
R12: 0x1B0
R13: 0x0
R14: 0x1ECB8314040
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x536AC2 0x7FFA7D436AC2
[1]	YimMenu.dll+0x161FEF 0x7FFA7D061FEF
[2]	YimMenu.dll+0x17B5B3 0x7FFA7D07B5B3
[3]	GTA5.exe+0x139671E 0x7FF7CA4E671E
[4]	GTA5.exe+0x7EDF51 0x7FF7C993DF51
[5]	GTA5.exe+0x167B7FD 0x7FF7CA7CB7FD
[6]	GTA5.exe+0x167B71A 0x7FF7CA7CB71A
[7]	GTA5.exe+0x1655EE5 0x7FF7CA7A5EE5
[8]	GTA5.exe+0x1656856 0x7FF7CA7A6856
[9]	GTA5.exe+0x165F832 0x7FF7CA7AF832
[10]	GTA5.exe+0x130E95A 0x7FF7CA45E95A
[11]	KERNEL32.DLL BaseThreadInitThunk
[12]	ntdll.dll RtlUserThreadStart
[13]	ntdll.dll RtlUserThreadStart
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x1
RCX: 0x7FFA005D8FD1
RDX: 0x9E703FF701
RBX: 0x1ED64F4CF80
RSI: 0x1ED64F4F2C0
RDI: 0x1ED64F516C0
RSP: 0x9E703FF710
RBP: 0x0
R8:  0x1ECEC4F1E00
R9:  0x1
R10: 0x8000
R11: 0x9E703FF670
R12: 0x1B0
R13: 0x0
R14: 0x1ECB8314040
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x536AC8 0x7FFA7D436AC8
[1]	YimMenu.dll+0x161FEF 0x7FFA7D061FEF
[2]	YimMenu.dll+0x17B5B3 0x7FFA7D07B5B3
[3]	GTA5.exe+0x139671E 0x7FF7CA4E671E
[4]	GTA5.exe+0x7EDF51 0x7FF7C993DF51
[5]	GTA5.exe+0x167B7FD 0x7FF7CA7CB7FD
[6]	GTA5.exe+0x167B71A 0x7FF7CA7CB71A
[7]	GTA5.exe+0x1655EE5 0x7FF7CA7A5EE5
[8]	GTA5.exe+0x1656856 0x7FF7CA7A6856
[9]	GTA5.exe+0x165F832 0x7FF7CA7AF832
[10]	GTA5.exe+0x130E95A 0x7FF7CA45E95A
[11]	KERNEL32.DLL BaseThreadInitThunk
[12]	ntdll.dll RtlUserThreadStart
[13]	ntdll.dll RtlUserThreadStart
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------

[08:28:06.4030945][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF7C9150000 Size: 67215872
ntdll.dll Base Address: 0x7FFAB1BF0000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFAB1160000 Size: 513536
KERNELBASE.dll Base Address: 0x7FFAAF750000 Size: 1255936
apphelp.dll Base Address: 0x7FFAAC830000 Size: 319488
AcLayers.DLL Base Address: 0x7FFA8B760000 Size: 175104
msvcrt.dll Base Address: 0x7FFAB07F0000 Size: 477184
USER32.dll Base Address: 0x7FFAB1820000 Size: 584704
win32u.dll Base Address: 0x7FFAAF5D0000 Size: 42496
GDI32.dll Base Address: 0x7FFAB07C0000 Size: 57856
gdi32full.dll Base Address: 0x7FFAAF400000 Size: 672768
msvcp_win.dll Base Address: 0x7FFAAFB50000 Size: 344064
ucrtbase.dll Base Address: 0x7FFAAFA50000 Size: 735744
SHELL32.dll Base Address: 0x7FFAB0890000 Size: 5921280
SHLWAPI.dll Base Address: 0x7FFAB16F0000 Size: 182784
ADVAPI32.dll Base Address: 0x7FFAB1750000 Size: 434176
sechost.dll Base Address: 0x7FFAB1000000 Size: 422400
RPCRT4.dll Base Address: 0x7FFAB15C0000 Size: 922624
bcrypt.dll Base Address: 0x7FFAAFBF0000 Size: 102912
sfc.dll Base Address: 0x1ECEC4A0000 Size: 0
WINSPOOL.DRV Base Address: 0x7FFA9EED0000 Size: 389632
combase.dll Base Address: 0x7FFAB0460000 Size: 2324480
shcore.dll Base Address: 0x7FFAB02C0000 Size: 476672
sfc_os.DLL Base Address: 0x7FFA8C8A0000 Size: 28672
AcGenral.DLL Base Address: 0x7FFA94FA0000 Size: 243200
ole32.dll Base Address: 0x7FFAB00A0000 Size: 833024
USERENV.dll Base Address: 0x7FFAAF150000 Size: 108032
MPR.dll Base Address: 0x7FFA9E450000 Size: 71168
SspiCli.dll Base Address: 0x7FFAAF180000 Size: 123904
IMM32.DLL Base Address: 0x7FFAB12F0000 Size: 125440
PSAPI.DLL Base Address: 0x7FFAAFC20000 Size: 2048
WS2_32.dll Base Address: 0x7FFAB1B40000 Size: 275456
CRYPT32.dll Base Address: 0x7FFAAF2A0000 Size: 1094656
VERSION.dll Base Address: 0x7FFAA94F0000 Size: 10752
WINTRUST.dll Base Address: 0x7FFAAF600000 Size: 293888
OLEAUT32.dll Base Address: 0x7FFAB1220000 Size: 608768
WININET.dll Base Address: 0x7FFA9F1F0000 Size: 2019840
WINMM.dll Base Address: 0x7FFAA61F0000 Size: 81408
MF.dll Base Address: 0x7FFA781A0000 Size: 340992
MFPlat.DLL Base Address: 0x7FFA8E0B0000 Size: 1409024
cfgmgr32.dll Base Address: 0x7FFAAF700000 Size: 219136
msdmo.dll Base Address: 0x7FFAA3F20000 Size: 13312
MFReadWrite.dll Base Address: 0x7FFA88360000 Size: 918016
PROPSYS.dll Base Address: 0x7FFAAA840000 Size: 631296
DSOUND.dll Base Address: 0x7FFA92E00000 Size: 380928
WTSAPI32.dll Base Address: 0x7FFAAAB30000 Size: 37888
d3d9.dll Base Address: 0x7FFA78340000 Size: 1371648
D3DCOMPILER_43.dll Base Address: 0x7FFA796C0000 Size: 2423296
DINPUT8.dll Base Address: 0x7FFA92BC0000 Size: 169472
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFAAFC30000 Size: 887808
IPHLPAPI.DLL Base Address: 0x7FFAAE650000 Size: 166400
powrprof.dll Base Address: 0x7FFAAF100000 Size: 70656
winmmbase.dll Base Address: 0x7FFA9F9E0000 Size: 95232
kernel.appcore.dll Base Address: 0x7FFAADB00000 Size: 16384
dwmapi.dll Base Address: 0x7FFAACCC0000 Size: 98816
windows.storage.dll Base Address: 0x7FFAAD140000 Size: 5853184
Wldp.dll Base Address: 0x7FFAAEC00000 Size: 96768
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFA82BA0000 Size: 96256
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFAA3440000 Size: 48128
d3dx9_43.dll Base Address: 0x7FFA83090000 Size: 2280960
OPENGL32.dll Base Address: 0x7FFA91760000 Size: 909312
GLU32.dll Base Address: 0x7FFA92A20000 Size: 122880
bink2w64.dll Base Address: 0x7FFA8DA80000 Size: 307712
MFCORE.DLL Base Address: 0x7FFA82220000 Size: 3960320
ksuser.dll Base Address: 0x7FFAA1660000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFAAEB70000 Size: 10752
UMPDC.dll Base Address: 0x7FFAAF0E0000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFAAF670000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFA8E360000 Size: 105472
MSASN1.dll Base Address: 0x7FFAAED90000 Size: 34816
inputhost.dll Base Address: 0x7FFAA3180000 Size: 976384
wintypes.dll Base Address: 0x7FFAABAA0000 Size: 487424
CoreMessaging.dll Base Address: 0x7FFAAC4D0000 Size: 607744
CoreUIComponents.dll Base Address: 0x7FFAAC170000 Size: 1795072
ntmarta.dll Base Address: 0x7FFAAE3B0000 Size: 140288
dbghelp.dll Base Address: 0x7FFAAD8E0000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFA967C0000 Size: 136704
CRYPTSP.dll Base Address: 0x7FFAAEB50000 Size: 46080
uxtheme.dll Base Address: 0x7FFAAC9D0000 Size: 382976
rsaenh.dll Base Address: 0x7FFAAE290000 Size: 142336
clbcatq.dll Base Address: 0x7FFAB10A0000 Size: 437760
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFA7D910000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFAB1AE0000 Size: 269312
Normaliz.dll Base Address: 0x7FFAB1150000 Size: 512
WINHTTP.dll Base Address: 0x7FFAA8DC0000 Size: 845312
Secur32.dll Base Address: 0x7FFA9EEC0000 Size: 11264
VCRUNTIME140.dll Base Address: 0x7FFAAABF0000 Size: 73728
MSVCP140.dll Base Address: 0x7FFA94520000 Size: 340480
VCRUNTIME140_1.dll Base Address: 0x7FFAAC7E0000 Size: 15360
NSI.dll Base Address: 0x7FFAB01D0000 Size: 7680
dhcpcsvc6.DLL Base Address: 0x7FFAA8FD0000 Size: 23552
dhcpcsvc.DLL Base Address: 0x7FFAA9650000 Size: 61440
amsi.dll Base Address: 0x7FFA9C150000 Size: 62464
profapi.dll Base Address: 0x7FFAAF1D0000 Size: 88064
MpOav.dll Base Address: 0x7FFA9BFE0000 Size: 212992
mswsock.dll Base Address: 0x7FFAAE960000 Size: 331776
napinsp.dll Base Address: 0x7FFA9F790000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFAA3CD0000 Size: 66048
wshbth.dll Base Address: 0x7FFA93280000 Size: 43008
NLAapi.dll Base Address: 0x7FFAAAB50000 Size: 68608
DNSAPI.dll Base Address: 0x7FFAAE690000 Size: 600576
winrnr.dll Base Address: 0x7FFAA6180000 Size: 32768
dxcore.dll Base Address: 0x7FFAA6670000 Size: 150016
D3D11.DLL Base Address: 0x7FFAAACC0000 Size: 1853440
dxgi.dll Base Address: 0x7FFAADB50000 Size: 614912
DEVOBJ.dll Base Address: 0x7FFAAEF60000 Size: 132608
D3D10_1.DLL Base Address: 0x7FFAA3390000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFAA66D0000 Size: 7680
MSCTF.dll Base Address: 0x7FFAB19C0000 Size: 864768
textinputframework.dll Base Address: 0x7FFAA3BD0000 Size: 722944
WINSTA.dll Base Address: 0x7FFAAF080000 Size: 190976
aticfx64.dll Base Address: 0x7FFAA6370000 Size: 1123840
atiuxp64.dll Base Address: 0x7FFAA5F50000 Size: 190464
atidxx64.dll Base Address: 0x7FFAA3F80000 Size: 11699712
amdihk64.dll Base Address: 0x7FFAA27A0000 Size: 117248
rasadhlp.dll Base Address: 0x7FFAA1BF0000 Size: 7168
fwpuclnt.dll Base Address: 0x7FFAA2270000 Size: 283648
D3DSCache.dll Base Address: 0x7FFAA15C0000 Size: 94208
twinapi.appcore.dll Base Address: 0x7FFAA8780000 Size: 1457664
HID.DLL Base Address: 0x7FFAADAD0000 Size: 20480
MMDevApi.dll Base Address: 0x7FFAA84C0000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFA8D7A0000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFA9CD30000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFAACA90000 Size: 31744
Windows.UI.dll Base Address: 0x7FFAA3DA0000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFAA8990000 Size: 450048
avrt.dll Base Address: 0x7FFAA9560000 Size: 5632
imagehlp.dll Base Address: 0x7FFAB1800000 Size: 45056
gpapi.dll Base Address: 0x7FFAADB20000 Size: 69120
cryptnet.dll Base Address: 0x7FFAA6630000 Size: 135168
WINNSI.DLL Base Address: 0x7FFAAA790000 Size: 11776
socialclub.dll Base Address: 0x7FFA87A50000 Size: 2692608
chrome_elf.dll Base Address: 0x7FFA876E0000 Size: 901120
libcef.dll Base Address: 0x7FFA52830000 Size: 151009280
COMDLG32.dll Base Address: 0x7FFAB01E0000 Size: 684032
NETAPI32.dll Base Address: 0x7FFA9E2D0000 Size: 47616
UIAutomationCore.DLL Base Address: 0x7FFA8E640000 Size: 2040832
OLEACC.dll Base Address: 0x7FFA9F8D0000 Size: 260608
DWrite.dll Base Address: 0x7FFA98260000 Size: 1601024
ncrypt.dll Base Address: 0x7FFAAEC70000 Size: 102400
urlmon.dll Base Address: 0x7FFAA2320000 Size: 1281536
USP10.dll Base Address: 0x7FFAA60D0000 Size: 512
dxva2.dll Base Address: 0x7FFA8FBA0000 Size: 96256
wevtapi.dll Base Address: 0x7FFAAA470000 Size: 296960
CRYPTUI.dll Base Address: 0x7FFA794C0000 Size: 246272
ESENT.dll Base Address: 0x7FFAA0DD0000 Size: 2585088
COMCTL32.dll Base Address: 0x7FFAA6840000 Size: 560128
srvcli.dll Base Address: 0x7FFAA22F0000 Size: 54272
iertutil.dll Base Address: 0x7FFAA2A30000 Size: 551424
netutils.dll Base Address: 0x7FFAAE760000 Size: 19456
credui.dll Base Address: 0x7FFA8FB80000 Size: 55808
DSROLE.DLL Base Address: 0x7FFAAAAF0000 Size: 7680
WKSCLI.DLL Base Address: 0x7FFAAE3F0000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFA9D6C0000 Size: 61440
NTASN1.dll Base Address: 0x7FFAAEC30000 Size: 81408
FirewallAPI.dll Base Address: 0x7FFAADE80000 Size: 329728
fwbase.dll Base Address: 0x7FFAADE40000 Size: 151552
FWPolicyIOMgr.dll Base Address: 0x7FFAA0020000 Size: 205824
wdmaud.drv Base Address: 0x7FFAA3F30000 Size: 193024
msacm32.drv Base Address: 0x7FFAAA1D0000 Size: 17920
MSACM32.dll Base Address: 0x7FFAA60B0000 Size: 74240
midimap.dll Base Address: 0x7FFAA7E80000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFA93CC0000 Size: 42496
wbemprox.dll Base Address: 0x7FFA9E470000 Size: 27648
wbemcomn.dll Base Address: 0x7FFAA0CA0000 Size: 328704
wbemsvc.dll Base Address: 0x7FFA9CB10000 Size: 7168
fastprox.dll Base Address: 0x7FFA9CF90000 Size: 708608
mfsrcsnk.dll Base Address: 0x7FFA86590000 Size: 1873408
CompPkgSup.DLL Base Address: 0x7FFAA2520000 Size: 152576
Windows.Media.dll Base Address: 0x7FFA66B70000 Size: 5271040
Windows.ApplicationModel.dll Base Address: 0x7FFA98840000 Size: 556544
mp3dmod.dll Base Address: 0x7FFAA34B0000 Size: 58880
AppXDeploymentClient.dll Base Address: 0x7FFAA9370000 Size: 658432
TextShaping.dll Base Address: 0x7FFAA0490000 Size: 304640
YimMenu.dll Base Address: 0x7FFA7CF00000 Size: 7955968
D3DCOMPILER_47.dll Base Address: 0x7FFAAAF30000 Size: 3396608
MSVCP140_2.dll Base Address: 0x7FFAA0B90000 Size: 196096
winbrand.dll Base Address: 0x7FFAAAC40000 Size: 161280
xinput1_4.dll Base Address: 0x7FFAA3460000 Size: 30208
schannel.DLL Base Address: 0x7FFAAE1A0000 Size: 486400
mskeyprotect.dll Base Address: 0x7FFA9A0D0000 Size: 44544
ncryptsslp.dll Base Address: 0x7FFA9A3A0000 Size: 78848
toxmod.dll Base Address: 0x7FFAA3480000 Size: 106496
opusenc.dll Base Address: 0x7FFAAA1C0000 Size: 32768
fvad.dll Base Address: 0x7FFAA7360000 Size: 14848
libcurl.dll Base Address: 0x7FFA9E0B0000 Size: 367616
opus.dll Base Address: 0x7FFA99200000 Size: 311296
zlib1.dll Base Address: 0x7FFAA3370000 Size: 54784
Dumping registers:
RAX: 0x0
RCX: 0x1EC8B250000
RDX: 0x7FF7CBAC8DA0
RBX: 0x9E6EB4D3C8
RSI: 0x7FF7CBAC5DD0
RDI: 0x12
RSP: 0x9E6EB4CBA8
RBP: 0x7FF7CBAC8DA0
R8:  0x7FF7CBAC5DD0
R9:  0x5DD
R10: 0x1EC8C315C80
R11: 0x7FF7CBAC8DA0
R12: 0x7FF7CBADB8F0
R13: 0x0
R14: 0x1EC8B364D60
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x1A2CF8 0x7FFA7D0A2CF8
[1]	GTA5.exe+0x16D79BA 0x7FF7CA8279BA
[2]	GTA5.exe+0x16CF250 0x7FF7CA81F250
[3]	GTA5.exe+0x16D490C 0x7FF7CA82490C
[4]	GTA5.exe+0x13FCC39 0x7FF7CA54CC39
[5]	GTA5.exe+0x16D4A39 0x7FF7CA824A39
[6]	GTA5.exe+0x13FD016 0x7FF7CA54D016
[7]	YimMenu.dll+0x1A1B90 0x7FFA7D0A1B90
[8]	GTA5.exe+0x13FD0C9 0x7FF7CA54D0C9
[9]	GTA5.exe+0x13FCDE2 0x7FF7CA54CDE2
[10]	GTA5.exe+0x1427AB7 0x7FF7CA577AB7
[11]	GTA5.exe+0x10C6D98 0x7FF7CA216D98
[12]	GTA5.exe+0x162FA85 0x7FF7CA77FA85
[13]	GTA5.exe+0x162F2B7 0x7FF7CA77F2B7
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x7FFA005D8FD1
RCX: 0x1ED64F4CFD8
RDX: 0x9E703FF768
RBX: 0x9E703FF738
RSI: 0x9E703FF768
RDI: 0x1ED64F4CFA8
RSP: 0x9E703FF6D0
RBP: 0x0
R8:  0x1ECEC4F1E00
R9:  0x1
R10: 0x8000
R11: 0x9E703FF670
R12: 0x1B0
R13: 0x0
R14: 0x1ECB8314040
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x1631F0 0x7FFA7D0631F0
[1]	YimMenu.dll+0x5369D5 0x7FFA7D4369D5
[2]	YimMenu.dll+0x161FEF 0x7FFA7D061FEF
[3]	YimMenu.dll+0x17B5B3 0x7FFA7D07B5B3
[4]	GTA5.exe+0x139671E 0x7FF7CA4E671E
[5]	GTA5.exe+0x7EDF51 0x7FF7C993DF51
[6]	GTA5.exe+0x167B7FD 0x7FF7CA7CB7FD
[7]	GTA5.exe+0x167B71A 0x7FF7CA7CB71A
[8]	GTA5.exe+0x1655EE5 0x7FF7CA7A5EE5
[9]	GTA5.exe+0x1656856 0x7FF7CA7A6856
[10]	GTA5.exe+0x165F832 0x7FF7CA7AF832
[11]	GTA5.exe+0x130E95A 0x7FF7CA45E95A
[12]	KERNEL32.DLL BaseThreadInitThunk
[13]	ntdll.dll RtlUserThreadStart
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x1
RCX: 0x7FFA005D8FD1
RDX: 0x9E703FF768
RBX: 0x1ED64F4CF80
RSI: 0x1ED64F4F2C0
RDI: 0x1ED64F516C0
RSP: 0x9E703FF710
RBP: 0x0
R8:  0x1ECEC4F1E00
R9:  0x1
R10: 0x8000
R11: 0x9E703FF670
R12: 0x1B0
R13: 0x0
R14: 0x1ECB8314040
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x536AC2 0x7FFA7D436AC2
[1]	YimMenu.dll+0x161FEF 0x7FFA7D061FEF
[2]	YimMenu.dll+0x17B5B3 0x7FFA7D07B5B3
[3]	GTA5.exe+0x139671E 0x7FF7CA4E671E
[4]	GTA5.exe+0x7EDF51 0x7FF7C993DF51
[5]	GTA5.exe+0x167B7FD 0x7FF7CA7CB7FD
[6]	GTA5.exe+0x167B71A 0x7FF7CA7CB71A
[7]	GTA5.exe+0x1655EE5 0x7FF7CA7A5EE5
[8]	GTA5.exe+0x1656856 0x7FF7CA7A6856
[9]	GTA5.exe+0x165F832 0x7FF7CA7AF832
[10]	GTA5.exe+0x130E95A 0x7FF7CA45E95A
[11]	KERNEL32.DLL BaseThreadInitThunk
[12]	ntdll.dll RtlUserThreadStart
[13]	ntdll.dll RtlUserThreadStart
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x1
RCX: 0x7FFA005D8FD1
RDX: 0x9E703FF701
RBX: 0x1ED64F4CF80
RSI: 0x1ED64F4F2C0
RDI: 0x1ED64F516C0
RSP: 0x9E703FF710
RBP: 0x0
R8:  0x1ECEC4F1E00
R9:  0x1
R10: 0x8000
R11: 0x9E703FF670
R12: 0x1B0
R13: 0x0
R14: 0x1ECB8314040
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x536AC8 0x7FFA7D436AC8
[1]	YimMenu.dll+0x161FEF 0x7FFA7D061FEF
[2]	YimMenu.dll+0x17B5B3 0x7FFA7D07B5B3
[3]	GTA5.exe+0x139671E 0x7FF7CA4E671E
[4]	GTA5.exe+0x7EDF51 0x7FF7C993DF51
[5]	GTA5.exe+0x167B7FD 0x7FF7CA7CB7FD
[6]	GTA5.exe+0x167B71A 0x7FF7CA7CB71A
[7]	GTA5.exe+0x1655EE5 0x7FF7CA7A5EE5
[8]	GTA5.exe+0x1656856 0x7FF7CA7A6856
[9]	GTA5.exe+0x165F832 0x7FF7CA7AF832
[10]	GTA5.exe+0x130E95A 0x7FF7CA45E95A
[11]	KERNEL32.DLL BaseThreadInitThunk
[12]	ntdll.dll RtlUserThreadStart
[13]	ntdll.dll RtlUserThreadStart
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------
EXCEPTION_ACCESS_VIOLATION
Dumping registers:
RAX: 0x7FFA005D8FD1
RCX: 0x1ED64F4CFD8
RDX: 0xA7
RBX: 0x1ED64F4CFA8
RSI: 0x0
RDI: 0x1ED64F4CFA8
RSP: 0x9E703FF7A0
RBP: 0x0
R8:  0x4
R9:  0xA8
R10: 0x8
R11: 0x9E703FF798
R12: 0x1B0
R13: 0x0
R14: 0x1ECB8314040
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x534EE4 0x7FFA7D434EE4
[1]	YimMenu.dll+0x161FF9 0x7FFA7D061FF9
[2]	YimMenu.dll+0x17B5B3 0x7FFA7D07B5B3
[3]	GTA5.exe+0x139671E 0x7FF7CA4E671E
[4]	GTA5.exe+0x7EDF51 0x7FF7C993DF51
[5]	GTA5.exe+0x167B7FD 0x7FF7CA7CB7FD
[6]	GTA5.exe+0x167B71A 0x7FF7CA7CB71A
[7]	GTA5.exe+0x1655EE5 0x7FF7CA7A5EE5
[8]	GTA5.exe+0x1656856 0x7FF7CA7A6856
[9]	GTA5.exe+0x165F832 0x7FF7CA7AF832
[10]	GTA5.exe+0x130E95A 0x7FF7CA45E95A
[11]	KERNEL32.DLL BaseThreadInitThunk
[12]	ntdll.dll RtlUserThreadStart
[13]	ntdll.dll RtlUserThreadStart
[14]	GTA5.exe+0x27B6E 0x7FF7C9177B6E
[15]	GTA5.exe+0x21283 0x7FF7C9171283
[16]	GTA5.exe+0x162EEC0 0x7FF7CA77EEC0
[17]	GTA5.exe+0x1494 0x7FF7C9151494
[18]	GTA5.exe+0x130538F 0x7FF7CA45538F
[19]	GTA5.exe+0x1821344 0x7FF7CA971344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------


>
```

### Store

Epic Games

### Language

Russian

### YimMenu Language

Русский (RU)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by lonelybud**
may fix #2852

### CODE REVIEW

File: src/services/gui/gui_service.hpp [hunk 1]
```diff
@@ -190,4 +190,4 @@ namespace big
 	};
 
 	inline gui_service* g_gui_service{};
-}
\ No newline at end of file
+}
```
Comment (gir489returns) [inline src/services/gui/gui_service.hpp:193]: Fix nonsense whitespace changes. Don't you guys check these changes before pushing?

**Review by gir489returns — CHANGES_REQUESTED** [review]

File: src/services/gui/gui_service.hpp (hunk 1 above)
Comment (lonelybud) [reply src/services/gui/gui_service.hpp:193]: this last one i did not add. i just made the one change on github page itself. I believe github added it.

Comment (lonelybud) [reply src/services/gui/gui_service.hpp]: nvm its github bug. i locally pushed the changes now

**Review by Yimura — APPROVED** [review]
Botched fix of an inherently badly designed component.

Ideally we'd redo the whole thing GUI code.

**Review by gir489returns — APPROVED** [review]
