### PR TITLE
Fix player list crash

### LINKED ISSUE #3075: [Bug]: Player list crash even after pull #3035
Even after https://github.com/YimMenu/YimMenu/pull/3035

### Describe the bug

When having the player list open, sometimes players don't have names (blank) and there are errors in the console and your game freezes.

### Expected Behavior

No errors and players not having a blank name.

### Logs

```
[13:07:19.0506326][INFO/main.cpp:159] Git Info
	Branch:	fixes
	Hash:	04156ebd2ce0af17718b6cd686e49c13f3770743
	Date:	Thu May 9 05:59:21 2024
```
[errors.log](https://github.com/YimMenu/YimMenu/files/15262768/errors.log) (not formatted cuz no pdb :/)

### Additional context

Interesting thing is that the error only came once, then I closed the menu, then I opened it again after a few seconds and multiple errors came and my game froze.

### PR DESCRIPTION
**Pull request by Mr-X-GTA**
Fixes #3075

### CODE REVIEW

File: src/hooks/protections/script_event_handler.cpp [hunk 1]
```diff
@@ -459,8 +459,10 @@ namespace big
 		if (g.debug.logs.script_event.logs
 		    && (!g.debug.logs.script_event.filter_player || g.debug.logs.script_event.player_id == player->m_player_id)) [[unlikely]]
 		{
+			uint64_t rockstar_id = player->get_net_data() == nullptr ? 0 : player->get_net_data()->m_gamer_handle.m_rockstar_id;
```
Comment (gir489returns) [inline src/hooks/protections/script_event_handler.cpp:462]: Can you move this to inside the player.cpp class? That way, it will enforce OOP and not expect the caller to handle this, as the caller doesn't care about the net data (well they do just not directly) they only want their Rockstar ID if we have it.

File: src/util/chat.hpp [hunk 2]
```diff
@@ -155,8 +155,9 @@ namespace big::chat
 		    g_file_manager.get_project_file(spam_reason != SpamReason::NOT_A_SPAMMER ? "./spam.log" : "./chat.log").get_path(),
 		    std::ios::app);
 
-		auto& data = *player->get_net_data();
-		auto ip    = player->get_ip_address();
+		uint64_t rockstar_id = player->get_net_data() == nullptr ? 0 : player->get_net_data()->m_gamer_handle.m_rockstar_id;
```
Comment (gir489returns) [inline src/util/chat.hpp:158]: Ditto.

**Review by gir489returns — CHANGES_REQUESTED** [review]

**Review by gir489returns — APPROVED** [review]

**Review by Yimura — DISMISSED** [review]
