### PR TITLE
Fix crash in transition

### LINKED ISSUE #3089: [Bug]: Crashed while joining the session from session browser
### Describe the bug

Was joining the session and got crashed before host started broadcasting data

### Steps To Reproduce

Not really sure how to reproduce this. I will attach RID of the host I was trying to join though I can't find a player with such RID.

### Expected Behavior

Do not get crashed

### Logs

[crash.log](https://github.com/YimMenu/YimMenu/files/15280664/crash.log)

### Screenshots / Video

crasher

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by Mr-X-GTA**
Fixes https://github.com/YimMenu/YimMenu/issues/3089

### CODE REVIEW

File: src/services/players/player.cpp [hunk 1]
```diff
@@ -133,7 +133,7 @@ namespace big
 
 	uint8_t player::id() const
 	{
-		if (*g_pointers->m_gta.m_is_session_started)
+		if (gta_util::get_network_player_mgr()->m_player_count > 0)
```
Comment (Yimura) [inline src/services/players/player.cpp:136]: This is a _possible_ nullptr deref crash waiting to happen, however I'm pretty sure the CNetworkPlayerMgr always exists (never deallocated and instantiated once).

Comment (Mr-X-GTA) [reply src/services/players/player.cpp:136]: It's never nullptr as it's a static instance

**Review by Yimura — APPROVED** [review]
