### PR TITLE
fix(FontMgr): also keep in mind game language when generating font texture

### LINKED ISSUE #1409: [Request]: Enforce spaces / line ending in a commit checker
### Problem

the clang format use tabs, not sure why? I propose https://github.com/YimMenu/YimMenu/blob/master/.clang-format#L67

UseTab: Never

### Solution

A simple github action that check for any `\t` and make the pr not mergeable would be a great thing imo

### Reason

incoming pr / whats on the repo always differ, which break git diffs / make them much more annoying to read

### Additional context

_No response_

### LINKED ISSUE #2871: [Bug]: Unreadable text
### Describe the bug

Switching the menu to English, I noticed that some of the inscriptions became unreadable, although everything is fine in Russian. I've tried set game language to English in Yim settings too. No results.

### Steps To Reproduce

1. Open GTA
2. Inject YimMenu
3. Change language Russian to English
4. Go to LSC tab

### Expected Behavior

Readable text

### Logs and/or screenshots

```
<[01:10:38.5854830][INFO/main.cpp:156] Settings Loaded and logger initialized.
[01:10:38.5855801][INFO/main.cpp:158] Yim's Menu Initializing
[01:10:38.5863399][INFO/main.cpp:159] Git Info
	Branch:	master
	Hash:	7e7bcb155a5594a6e5955894cc2b8f05d063b31c
	Date:	Sat Mar 23 17:37:51 2024
[01:10:38.5864462][INFO/main.cpp:171] Windows 10 Pro Version 22H2 (OS Build 19045.4170)
[01:10:38.5907298][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[01:10:38.5918990][INFO/main.cpp:179] Thread pool initialized.
[01:10:38.6033628][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[01:10:38.6033811][INFO/pointers.cpp:1838] Loading pointers instance from cache
[01:10:38.6033834][INFO/pointers.cpp:1847] Pointers cache: Loading 217 fields from the cache
[01:10:38.6034062][DEBUG/module.cpp:55] Waiting for socialclub.dll...
[01:10:38.6145587][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[01:10:38.6145703][INFO/pointers.cpp:1838] Loading pointers instance from cache
[01:10:38.6145723][INFO/pointers.cpp:1847] Pointers cache: Loading 5 fields from the cache
[01:10:38.6146168][INFO/main.cpp:182] Pointers initialized.
[01:10:38.6146213][INFO/main.cpp:189] Disabled anticheat gameskeleton.
[01:10:38.6147424][INFO/main.cpp:192] Byte Patch Manager initialized.
[01:10:38.6153986][INFO/main.cpp:195] Renderer initialized.
[01:10:38.6985467][INFO/main.cpp:199] Fiber pool initialized.
[01:10:38.7059936][INFO/main.cpp:202] HTTP Client initialized.
[01:10:39.0881683][DEBUG/thread_pool.cpp:96] Thread 7064 executing font_mgr.cpp:103
[01:10:39.0893525][INFO/main.cpp:205] Translation Service initialized.
[01:10:39.2142101][INFO/main.cpp:208] Hooking initialized.
[01:10:39.2487743][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[01:10:39.2487855][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[01:10:39.2491657][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[01:10:39.2495461][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[01:10:39.2495495][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[01:10:39.2495783][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[01:10:39.2522327][DEBUG/thread_pool.cpp:96] Thread 7064 executing player_database_service.cpp:285
[01:10:39.2523728][INFO/main.cpp:228] Registered service instances...
[01:10:39.2523853][INFO/main.cpp:231] Finished initialising services.
[01:10:39.2525112][INFO/main.cpp:252] Scripts registered.
[01:10:39.2835159][INFO/main.cpp:255] Hooking enabled.
[01:10:39.2872752][INFO/main.cpp:258] Dynamic native hooker initialized.
[01:10:39.4455774][INFO/lua_module.cpp:330] Loaded Extras-Addon.lua
[01:10:39.4619822][INFO/lua_module.cpp:330] Loaded json.lua
[01:10:39.4943174][INFO/lua_module.cpp:330] Loaded minigamehack.lua
[01:10:39.4948325][INFO/main.cpp:262] Lua manager initialized.
[01:10:47.6188729][INFO/backend.cpp:53] Starting script: Self
[01:10:47.6188926][INFO/backend.cpp:78] Starting script: Weapons
[01:10:47.6189036][INFO/backend.cpp:101] Starting script: Vehicles
[01:10:47.6189249][INFO/backend.cpp:117] Starting script: Miscellaneous
[01:10:47.6189479][INFO/backend.cpp:138] Starting script: Remote
[01:10:47.6189546][INFO/backend.cpp:153] Starting script: Ls customs
[01:10:47.6189591][INFO/backend.cpp:165] Starting script: Rainbow paint
[01:10:47.6189614][INFO/backend.cpp:177] Starting script: Disable Control Action
[01:10:47.6189638][INFO/backend.cpp:190] Starting script: World
[01:10:47.6439051][INFO/tunables_service.cpp:36] Loading tunables from cache
[01:11:20.5123565][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: MM; DATA: "mmList":"417070584465706C6F796D656E74436C69656E742E646C6C00|475441352E65786500|"
[01:11:53.0595422][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[01:11:53.0597180][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":427987127,"type":3136273443,"cat":654913086,"pt":621280113,"slot":0
[01:11:57.3601606][INFO/queue_dependency.cpp:63] Blocking AC Verifier 5ca880
[01:11:57.3644298][INFO/queue_dependency.cpp:63] Blocking AC Verifier 9621f0
[01:11:57.3644866][INFO/queue_dependency.cpp:63] Blocking AC Verifier a668ec
[01:11:57.3659571][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f774
[01:11:57.3660012][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f6fc
[01:12:12.3615323][INFO/queue_dependency.cpp:63] Blocking AC Verifier 318b98
[01:12:12.3629361][INFO/queue_dependency.cpp:63] Blocking AC Verifier 45acf4
[01:12:12.3637016][INFO/queue_dependency.cpp:63] Blocking AC Verifier 459f38
[01:12:12.3701036][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f724
[01:12:12.3701643][INFO/queue_dependency.cpp:63] Blocking AC Verifier 66f74c
[01:12:12.3752879][INFO/queue_dependency.cpp:63] Blocking AC Verifier 335458
[01:12:12.3753120][INFO/queue_dependency.cpp:63] Blocking AC Verifier 335430
[01:12:12.3753438][INFO/queue_dependency.cpp:63] Blocking AC Verifier 4012b8
[01:15:20.5393274][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[01:16:13.1427665][DEBUG/thread_pool.cpp:96] Thread 7680 executing view_settings.cpp:54
[01:16:13.9743825][DEBUG/thread_pool.cpp:96] Thread 376 executing font_mgr.cpp:103
[01:16:37.0154694][DEBUG/thread_pool.cpp:96] Thread 376 executing view_settings.cpp:54
[01:16:37.2375670][DEBUG/thread_pool.cpp:96] Thread 376 executing font_mgr.cpp:103
[01:17:02.3252056][DEBUG/thread_pool.cpp:96] Thread 376 executing translation_service.cpp:95
[01:17:02.3340420][DEBUG/thread_pool.cpp:96] Thread 5656 executing font_mgr.cpp:103
[01:17:25.7046752][DEBUG/thread_pool.cpp:96] Thread 5656 executing translation_service.cpp:95
[01:17:25.7082300][DEBUG/thread_pool.cpp:96] Thread 7680 executing font_mgr.cpp:103
[01:26:48.7188938][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":31,"char":{"slot":0,"cash":582744814,"bank":2145126641,"evc":2727871455,"pvc":0,"pxr":0.00000,"nonce":638470131364789551},"c":[-2026.04626,-1031.27600,5.88197],"pt":622164404,"vct":0,"vcp":0,"mid":0,"action":"PICKUP","cat":"PICKED_UP","ctx":{}
[01:26:48.7189604][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":31,"char":{"slot":0,"cash":582744814,"bank":2145126641,"evc":2727871455,"pvc":0,"pxr":0.00000,"nonce":638470131364789551},"c":[-2026.04626,-1031.27600,5.88197],"pt":622164404,"vct":0,"vcp":0,"mid":0,"action":"PICKUP","cat":"PICKED_UP","ctx":{}
[01:27:07.6199497][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":25,"char":{"slot":0,"cash":582744839,"bank":2145126641,"evc":2727871480,"pvc":0,"pxr":0.00000,"nonce":638470131553696192},"c":[-2054.56787,-1026.58691,2.59215],"pt":622174421,"vct":0,"vcp":0,"mid":0,"action":"PICKUP","cat":"PICKED_UP","ctx":{}
[01:27:07.6199891][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":25,"char":{"slot":0,"cash":582744839,"bank":2145126641,"evc":2727871480,"pvc":0,"pxr":0.00000,"nonce":638470131553696192},"c":[-2054.56787,-1026.58691,2.59215],"pt":622174421,"vct":0,"vcp":0,"mid":0,"action":"PICKUP","cat":"PICKED_UP","ctx":{}
[01:27:15.4122084][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":24,"char":{"slot":0,"cash":582744896,"bank":2145126641,"evc":2727871537,"pvc":0,"pxr":0.00000,"nonce":638470131632818348},"c":[-2068.13208,-1022.91278,3.06083],"pt":622184440,"vct":0,"vcp":0,"mid":0,"action":"PICKUP","cat":"PICKED_UP","ctx":{}
[01:27:15.4122441][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":24,"char":{"slot":0,"cash":582744896,"bank":2145126641,"evc":2727871537,"pvc":0,"pxr":0.00000,"nonce":638470131632818348},"c":[-2068.13208,-1022.91278,3.06083],"pt":622184440,"vct":0,"vcp":0,"mid":0,"action":"PICKUP","cat":"PICKED_UP","ctx":{}
[01:27:47.9465581][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":33,"char":{"slot":0,"cash":582744929,"bank":2145126641,"evc":2727871570,"pvc":0,"pxr":0.00000,"nonce":638470131959946801},"c":[-2050.29419,-1035.86206,5.88242],"pt":622223734,"vct":0,"vcp":0,"mid":0,"action":"PICKUP","cat":"PICKED_UP","ctx":{}
[01:27:47.9465965][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":33,"char":{"slot":0,"cash":582744929,"bank":2145126641,"evc":2727871570,"pvc":0,"pxr":0.00000,"nonce":638470131959946801},"c":[-2050.29419,-1035.86206,5.88242],"pt":622223734,"vct":0,"vcp":0,"mid":0,"action":"PICKUP","cat":"PICKED_UP","ctx":{}
[01:28:32.1453354][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":2131309714,"pt":622154390,"slot":0
[01:28:32.1453573][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":2131309714,"pt":622154390,"slot":0
[01:28:32.1453623][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":2131309714,"pt":622154390,"slot":0
[01:28:32.1453667][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":2131309714,"pt":622154390,"slot":0
[01:28:32.1453933][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":2131309714,"pt":622164404,"slot":0
[01:28:32.1453976][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":2131309714,"pt":622174421,"slot":0
[01:28:32.1454017][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":2131309714,"pt":622184440,"slot":0
[01:28:32.1454059][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":2131309714,"pt":622184440,"slot":0
[01:28:32.1454102][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":70407654,"pt":622194454,"slot":0
[01:28:32.1454150][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":2131309714,"pt":622203717,"slot":0
[01:28:32.1454346][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":70407654,"pt":622213720,"slot":0
[01:31:49.4298536][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":13200,"char":{"slot":0,"cash":582758157,"bank":2145126641,"evc":2727884798,"pvc":0,"pxr":0.00000,"nonce":638470134373292200},"c":[302.28641,138.10570,104.83740],"pt":622464026,"vct":0,"vcp":0,"mid":0,"action":"CHICKEN","cat":"SETUP","ctx":{
[01:31:49.4298886][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":13200,"char":{"slot":0,"cash":582758157,"bank":2145126641,"evc":2727884798,"pvc":0,"pxr":0.00000,"nonce":638470134373292200},"c":[302.28641,138.10570,104.83740],"pt":622464026,"vct":0,"vcp":0,"mid":0,"action":"CHICKEN","cat":"SETUP","ctx":{
[01:32:05.6226537][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":31,"type":2435321038,"cat":2131309714,"pt":622303848,"slot":0
[01:32:05.6226732][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":25,"type":2435321038,"cat":2131309714,"pt":622313868,"slot":0
[01:32:05.6227083][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":31,"type":2435321038,"cat":2131309714,"pt":622333886,"slot":0
[01:32:05.6227136][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":31,"type":2435321038,"cat":2131309714,"pt":622343903,"slot":0
[01:32:05.6227182][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":31,"type":2435321038,"cat":2131309714,"pt":622343903,"slot":0
[01:32:05.6227223][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":31,"type":2435321038,"cat":2131309714,"pt":622373950,"slot":0
[01:32:05.6228061][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2658791846,"cat":70407654,"pt":622434003,"slot":0
[01:32:05.6229146][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":2035,"type":2658791846,"cat":2053762773,"pt":622464026,"slot":0
[01:32:05.6229195][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2658791846,"cat":2053762773,"pt":622464026,"slot":0
[01:32:05.6229239][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":250,"type":2435321038,"cat":2131309714,"pt":622464026,"slot":0
[01:32:07.8566671][WARN/reaction.cpp:60] Received Modder Detection from 1QAYAQ1 (200587004)
[01:32:49.6761704][WARN/interloper_reaction.cpp:30] Received Spectate Others from Sayuto_03 (238777839), victim is BeniiKiLLER
[01:32:55.5726933][WARN/reaction.cpp:60] Received Modder Detection from franticAndrei (226997866)
[01:33:37.4545146][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[01:33:37.4548130][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[01:35:07.5132254][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":0,"type":2658791846,"cat":3041509490,"pt":622603680,"slot":0
[01:36:24.8756367][WARN/reaction.cpp:60] Received Modder Detection from Sabaka-cyka (83583801)
[01:37:29.0404305][WARN/reaction.cpp:60] Received Modder Detection from Istak- (243168890)
[01:38:03.3967844][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: RDEV; DATA: "g":"SC 243168890"
[01:40:08.8221750][WARN/reaction.cpp:60] Received Modder Detection from OmaeKaito (249164879)
[01:40:25.6465664][WARN/reaction.cpp:60] Received Remote Ragdoll from OmaeKaito (249164879)
[01:41:22.5453271][WARN/reaction.cpp:60] Received Force Mission from OmaeKaito (249164879)
[01:41:36.4212924][WARN/reaction.cpp:60] Received Force Mission from OmaeKaito (249164879)
[01:41:39.9153073][WARN/reaction.cpp:60] Received Force Mission from OmaeKaito (249164879)
[01:41:42.2750961][WARN/reaction.cpp:60] Received End Session Kick from OmaeKaito (249164879)
[01:41:42.2751346][WARN/reaction.cpp:45] OmaeKaito has been timed out
[01:42:19.8652391][WARN/reaction.cpp:60] Received Modder Detection from StanChrist (100512325)
[02:02:24.5127774][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":427990267,"type":3136273443,"cat":654913086,"pt":624289351,"slot":0
[02:06:01.1378488][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: W_L; DATA: "c":[-1114.12,-2882.50,13.95],"wantedlvl":3
[02:06:01.1379483][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":624399485,"slot":0
[02:06:01.1380061][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: W_L; DATA: "c":[-836.05,-2014.40,305.35],"wantedlvl":0
[02:06:01.1380723][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":624462084,"slot":0
[02:09:07.9533813][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":624522110,"slot":0
[02:09:07.9535305][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":624582171,"slot":0
[02:09:07.9537141][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":624652269,"slot":0
[02:11:37.3028101][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":624712367,"slot":0
[02:11:37.3030306][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":624822509,"slot":0
[02:11:37.3030363][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":1000,"type":2658791846,"cat":1652271427,"pt":624822509,"slot":0
[02:13:08.0077622][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":624882606,"slot":0
[02:15:44.6249081][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":10000,"char":{"slot":0,"cash":582767657,"bank":2145126641,"evc":2727894298,"pvc":0,"pxr":0.00000,"nonce":638470160725936738},"c":[755.13245,-2946.09668,6.28004],"pt":625083381,"vct":0,"vcp":0,"mid":0,"action":"WAGE","cat":"WAGE_PAYMENT","ctx":{}
[02:15:44.6249711][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":10000,"char":{"slot":0,"cash":582767657,"bank":2145126641,"evc":2727894298,"pvc":0,"pxr":0.00000,"nonce":638470160725936738},"c":[755.13245,-2946.09668,6.28004],"pt":625083381,"vct":0,"vcp":0,"mid":0,"action":"WAGE","cat":"WAGE_PAYMENT","ctx":{}
[02:15:55.5598322][WARN/reaction.cpp:60] Received GTA Banner from BeniiKiLLER (227057543)
[02:15:55.7695029][WARN/reaction.cpp:60] Received GTA Banner from BeniiKiLLER (227057543)
[02:17:08.0381694][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":624942690,"slot":0
[02:17:08.0383494][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":625013318,"slot":0
[02:17:08.0383881][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":625073379,"slot":0
[02:17:08.0385358][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":625123675,"slot":0
[02:19:15.9836407][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":625193781,"slot":0
[02:19:15.9837437][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: RDEV; DATA: "g":"SC 191388078"
[02:25:06.4903798][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":625454084,"slot":0
[02:25:06.4905526][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":100,"type":2658791846,"cat":2113013421,"pt":625514131,"slot":0
[02:25:06.4905585][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":625514131,"slot":0
[02:25:06.4906372][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":625595739,"slot":0
[02:25:06.4906658][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":100,"type":2658791846,"cat":2113013421,"pt":625625746,"slot":0
[02:27:24.6064442][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":625665786,"slot":0
[02:27:24.6066279][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: W_L; DATA: "c":[6.72,-674.34,16.10],"wantedlvl":5
[02:27:47.4486373][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":27,"char":{"slot":0,"cash":582767684,"bank":2145126141,"evc":2727893825,"pvc":0,"pxr":0.00000,"nonce":638470167956185909},"c":[-1.24522,-705.12256,16.13127],"pt":625788811,"vct":0,"vcp":0,"mid":314634032912674993,"action":"PICKUP","cat":"PICKED_UP"
[02:27:47.4488107][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":27,"char":{"slot":0,"cash":582767684,"bank":2145126141,"evc":2727893825,"pvc":0,"pxr":0.00000,"nonce":638470167956185909},"c":[-1.24522,-705.12256,16.13127],"pt":625788811,"vct":0,"vcp":0,"mid":314634032912674993,"action":"PICKUP","cat":"PICKED_UP"
[02:32:06.5851800][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: W_L; DATA: "c":[8.41,-662.51,33.45],"wantedlvl":4
[02:32:06.5852276][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: W_L; DATA: "c":[8.35,-662.46,33.45],"wantedlvl":3
[02:32:06.5852359][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: ESVCS; DATA: "c":[7.91,-662.09,33.45],"name":353883353,"cd":[7,-662],"wlvl":3
[02:32:06.5853396][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: ESVCS; DATA: "c":[-151.25,-620.68,31.85],"name":353883353,"cd":[-151,-620],"wlvl":5
[02:32:06.5853585][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: W_L; DATA: "c":[-151.25,-620.68,31.85],"wantedlvl":5
[02:32:06.5853966][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":625918982,"slot":0
[02:32:06.5854016][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":50,"type":2892279813,"cat":1924582434,"pt":625938991,"slot":0
[02:32:06.5854097][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: ESVCS; DATA: "c":[-1308.62,-726.20,10.50],"name":353883353,"cd":[-1308,-726],"wlvl":5
[02:32:06.5854173][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: ESVCS; DATA: "c":[-1376.36,-748.30,10.42],"name":353883353,"cd":[-1376,-748],"wlvl":5
[02:32:06.5854224][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":600,"type":3455376767,"cat":2563418546,"pt":625969025,"slot":0
[02:32:06.5854565][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":625979046,"slot":0
[02:32:06.5854610][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":50,"type":2892279813,"cat":1924582434,"pt":625999060,"slot":0
[02:35:24.3443951][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":10000,"char":{"slot":0,"cash":582777684,"bank":2145126141,"evc":2727903825,"pvc":0,"pxr":0.00000,"nonce":638470172522178375},"c":[-2683.81079,2424.44531,16.08336],"pt":626229333,"vct":0,"vcp":0,"mid":314634032912674993,"action":"WAGE","cat":"WAGE_PA
[02:35:24.3444578][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":10000,"char":{"slot":0,"cash":582777684,"bank":2145126141,"evc":2727903825,"pvc":0,"pxr":0.00000,"nonce":638470172522178375},"c":[-2683.81079,2424.44531,16.08336],"pt":626229333,"vct":0,"vcp":0,"mid":314634032912674993,"action":"WAGE","cat":"WAGE_PA
[02:36:30.9115001][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":626049110,"slot":0
[02:36:30.9115372][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: ESVCS; DATA: "c":[-2739.07,402.19,135.13],"name":353883353,"cd":[-2739,402],"wlvl":5
[02:36:30.9115473][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":50,"type":2892279813,"cat":1924582434,"pt":626059129,"slot":0
[02:36:30.9115813][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: W_L; DATA: "c":[-2668.18,509.28,169.50],"wantedlvl":0
[02:36:30.9116395][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":626109182,"slot":0
[02:36:30.9116738][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":626169263,"slot":0
[02:36:30.9116941][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":626239344,"slot":0
[02:36:45.5179610][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":626299395,"slot":0
[02:36:45.5179890][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":3391,"type":2658791846,"cat":2053762773,"pt":626307122,"slot":0
[02:36:45.5179937][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":150,"type":2435321038,"cat":2131309714,"pt":626307122,"slot":0
[02:36:51.3879616][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":55000,"char":{"slot":0,"cash":582832684,"bank":2145126141,"evc":2727958825,"pvc":0,"pxr":0.00000,"nonce":638470173396231103},"c":[-2211.07251,4276.94580,48.92230],"pt":626307122,"vct":0,"vcp":0,"mid":0,"action":"FINALE","cat":"TUNER_ROB","ctx":{
[02:36:51.3880000][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":55000,"char":{"slot":0,"cash":582832684,"bank":2145126141,"evc":2727958825,"pvc":0,"pxr":0.00000,"nonce":638470173396231103},"c":[-2211.07251,4276.94580,48.92230],"pt":626307122,"vct":0,"vcp":0,"mid":0,"action":"FINALE","cat":"TUNER_ROB","ctx":{
[02:37:09.0573612][WARN/reaction.cpp:60] Received Modder Detection from BLVCK_PINK (53455972)
[02:40:08.6993901][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[02:40:08.6996608][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[02:40:08.7006080][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: DUPE_DETECT; DATA: "a":1,"b":3,"c":758895617,"d":0,"e":1,"f":73,"g":80,"h":0,"i":0,"j":true,"k":0,"l":0
[02:40:08.7006260][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":626491997,"slot":0
[02:40:55.5261545][WARN/reaction.cpp:60] Received Modder Detection from waveyyy24 (248091968)
[02:42:43.1448920][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":626552060,"slot":0
[02:42:43.1451636][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":626612161,"slot":0
[02:44:06.5669299][WARN/reaction.cpp:60] Received Modder Detection from i-Snowy (239809156)
[02:44:13.7603896][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":626682233,"slot":0
[02:47:20.9616589][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":626882486,"slot":0
[02:50:49.4214768][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":626936341,"slot":0
[02:50:49.4215625][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":627006462,"slot":0
[02:50:49.4217141][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":627066506,"slot":0
[02:50:49.4217659][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2435321038,"cat":3741565104,"pt":627126561,"slot":0
[02:51:42.5344507][DEBUG/script_function.cpp:35] Found pattern RSD in script PauseMenu_Multiplayer
[02:51:44.5721759][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":600,"type":2658791846,"cat":4052905182,"pt":627186591,"slot":0
[02:53:20.9471533][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[02:53:58.1956738][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":428002958,"type":3136273443,"cat":654913086,"pt":627218681,"slot":0
[02:54:06.1234063][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[02:54:28.7103304][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF63A600000 Size: 67215872
ntdll.dll Base Address: 0x7FFAB1BF0000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFAB1160000 Size: 513536
KERNELBASE.dll Base Address: 0x7FFAAF750000 Size: 1255936
apphelp.dll Base Address: 0x7FFAAC830000 Size: 319488
AcLayers.DLL Base Address: 0x7FFA839A0000 Size: 175104
msvcrt.dll Base Address: 0x7FFAB07F0000 Size: 477184
USER32.dll Base Address: 0x7FFAB1820000 Size: 584704
win32u.dll Base Address: 0x7FFAAF5D0000 Size: 42496
GDI32.dll Base Address: 0x7FFAB07C0000 Size: 57856
gdi32full.dll Base Address: 0x7FFAAF400000 Size: 672768
msvcp_win.dll Base Address: 0x7FFAAFB50000 Size: 344064
ucrtbase.dll Base Address: 0x7FFAAFA50000 Size: 735744
SHELL32.dll Base Address: 0x7FFAB0890000 Size: 5921280
SHLWAPI.dll Base Address: 0x7FFAB16F0000 Size: 182784
ADVAPI32.dll Base Address: 0x7FFAB1750000 Size: 434176
sechost.dll Base Address: 0x7FFAB1000000 Size: 422400
RPCRT4.dll Base Address: 0x7FFAB15C0000 Size: 922624
bcrypt.dll Base Address: 0x7FFAAFBF0000 Size: 102912
sfc.dll Base Address: 0x1A57FD30000 Size: 0
WINSPOOL.DRV Base Address: 0x7FFA9EED0000 Size: 389632
combase.dll Base Address: 0x7FFAB0460000 Size: 2324480
shcore.dll Base Address: 0x7FFAB02C0000 Size: 476672
sfc_os.DLL Base Address: 0x7FFA8C8A0000 Size: 28672
AcGenral.DLL Base Address: 0x7FFA98440000 Size: 243200
ole32.dll Base Address: 0x7FFAB00A0000 Size: 833024
USERENV.dll Base Address: 0x7FFAAF150000 Size: 108032
MPR.dll Base Address: 0x7FFA9E450000 Size: 71168
SspiCli.dll Base Address: 0x7FFAAF180000 Size: 123904
IMM32.DLL Base Address: 0x7FFAB12F0000 Size: 125440
PSAPI.DLL Base Address: 0x7FFAAFC20000 Size: 2048
WS2_32.dll Base Address: 0x7FFAB1B40000 Size: 275456
CRYPT32.dll Base Address: 0x7FFAAF2A0000 Size: 1094656
VERSION.dll Base Address: 0x7FFAA94F0000 Size: 10752
WINTRUST.dll Base Address: 0x7FFAAF600000 Size: 293888
OLEAUT32.dll Base Address: 0x7FFAB1220000 Size: 608768
WININET.dll Base Address: 0x7FFA9F1F0000 Size: 2019840
WINMM.dll Base Address: 0x7FFAA61F0000 Size: 81408
MF.dll Base Address: 0x7FFA8F850000 Size: 340992
MFPlat.DLL Base Address: 0x7FFA8E0B0000 Size: 1409024
cfgmgr32.dll Base Address: 0x7FFAAF700000 Size: 219136
DSOUND.dll Base Address: 0x7FFA97760000 Size: 380928
msdmo.dll Base Address: 0x7FFAA6A30000 Size: 13312
MFReadWrite.dll Base Address: 0x7FFA8F740000 Size: 918016
PROPSYS.dll Base Address: 0x7FFAAA840000 Size: 631296
WTSAPI32.dll Base Address: 0x7FFAAAB30000 Size: 37888
d3d9.dll Base Address: 0x7FFA760A0000 Size: 1371648
D3DCOMPILER_43.dll Base Address: 0x7FFA87E60000 Size: 2423296
DINPUT8.dll Base Address: 0x7FFAA2F20000 Size: 169472
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFAAFC30000 Size: 887808
IPHLPAPI.DLL Base Address: 0x7FFAAE650000 Size: 166400
powrprof.dll Base Address: 0x7FFAAF100000 Size: 70656
winmmbase.dll Base Address: 0x7FFA9F9E0000 Size: 95232
kernel.appcore.dll Base Address: 0x7FFAADB00000 Size: 16384
dwmapi.dll Base Address: 0x7FFAACCC0000 Size: 98816
windows.storage.dll Base Address: 0x7FFAAD140000 Size: 5853184
Wldp.dll Base Address: 0x7FFAAEC00000 Size: 96768
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFAA6300000 Size: 48128
OPENGL32.dll Base Address: 0x7FFA894D0000 Size: 909312
GLU32.dll Base Address: 0x7FFAA62D0000 Size: 122880
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFA7F120000 Size: 96256
d3dx9_43.dll Base Address: 0x7FFA83730000 Size: 2280960
bink2w64.dll Base Address: 0x7FFA982A0000 Size: 307712
MFCORE.DLL Base Address: 0x7FFA7E830000 Size: 3960320
ksuser.dll Base Address: 0x7FFAA6360000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFAAEB70000 Size: 10752
UMPDC.dll Base Address: 0x7FFAAF0E0000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFAAF670000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFA8E360000 Size: 105472
MSASN1.dll Base Address: 0x7FFAAED90000 Size: 34816
inputhost.dll Base Address: 0x7FFAA3180000 Size: 976384
wintypes.dll Base Address: 0x7FFAABAA0000 Size: 487424
CoreMessaging.dll Base Address: 0x7FFAAC4D0000 Size: 607744
CoreUIComponents.dll Base Address: 0x7FFAAC170000 Size: 1795072
ntmarta.dll Base Address: 0x7FFAAE3B0000 Size: 140288
dbghelp.dll Base Address: 0x7FFAAD8E0000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFA967C0000 Size: 136704
CRYPTSP.dll Base Address: 0x7FFAAEB50000 Size: 46080
uxtheme.dll Base Address: 0x7FFAAC9D0000 Size: 382976
rsaenh.dll Base Address: 0x7FFAAE290000 Size: 142336
clbcatq.dll Base Address: 0x7FFAB10A0000 Size: 437760
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFA7DE10000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFAB1AE0000 Size: 269312
Normaliz.dll Base Address: 0x7FFAB1150000 Size: 512
WINHTTP.dll Base Address: 0x7FFAA8DC0000 Size: 845312
Secur32.dll Base Address: 0x7FFA9EEC0000 Size: 11264
MSVCP140.dll Base Address: 0x7FFA983B0000 Size: 340480
VCRUNTIME140.dll Base Address: 0x7FFAA80B0000 Size: 73728
VCRUNTIME140_1.dll Base Address: 0x7FFAAA1D0000 Size: 15360
NSI.dll Base Address: 0x7FFAB01D0000 Size: 7680
dhcpcsvc6.DLL Base Address: 0x7FFAA8FD0000 Size: 23552
dhcpcsvc.DLL Base Address: 0x7FFAA9650000 Size: 61440
amsi.dll Base Address: 0x7FFA9C150000 Size: 62464
profapi.dll Base Address: 0x7FFAAF1D0000 Size: 88064
MpOav.dll Base Address: 0x7FFA9BFE0000 Size: 212992
mswsock.dll Base Address: 0x7FFAAE960000 Size: 331776
napinsp.dll Base Address: 0x7FFA9F790000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFAA3CD0000 Size: 66048
wshbth.dll Base Address: 0x7FFA93280000 Size: 43008
NLAapi.dll Base Address: 0x7FFAAAB50000 Size: 68608
DNSAPI.dll Base Address: 0x7FFAAE690000 Size: 600576
winrnr.dll Base Address: 0x7FFAA6180000 Size: 32768
dxcore.dll Base Address: 0x7FFAA6670000 Size: 150016
D3D11.DLL Base Address: 0x7FFAAACC0000 Size: 1853440
dxgi.dll Base Address: 0x7FFAADB50000 Size: 614912
DEVOBJ.dll Base Address: 0x7FFAAEF60000 Size: 132608
D3D10_1.DLL Base Address: 0x7FFAA3A50000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFAA5F90000 Size: 7680
MSCTF.dll Base Address: 0x7FFAB19C0000 Size: 864768
textinputframework.dll Base Address: 0x7FFAA3BD0000 Size: 722944
rasadhlp.dll Base Address: 0x7FFAA1BF0000 Size: 7168
WINSTA.dll Base Address: 0x7FFAAF080000 Size: 190976
fwpuclnt.dll Base Address: 0x7FFAA2270000 Size: 283648
aticfx64.dll Base Address: 0x7FFAA6370000 Size: 1123840
atiuxp64.dll Base Address: 0x7FFAA5F50000 Size: 190464
atidxx64.dll Base Address: 0x7FFAA3F80000 Size: 11699712
amdihk64.dll Base Address: 0x7FFAA27A0000 Size: 117248
D3DSCache.dll Base Address: 0x7FFAA15C0000 Size: 94208
twinapi.appcore.dll Base Address: 0x7FFAA8780000 Size: 1457664
HID.DLL Base Address: 0x7FFAADAD0000 Size: 20480
MMDevApi.dll Base Address: 0x7FFAA84C0000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFA8E2D0000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFA9CD30000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFAACA90000 Size: 31744
Windows.UI.dll Base Address: 0x7FFAA3DA0000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFAA8990000 Size: 450048
avrt.dll Base Address: 0x7FFAA9560000 Size: 5632
imagehlp.dll Base Address: 0x7FFAB1800000 Size: 45056
gpapi.dll Base Address: 0x7FFAADB20000 Size: 69120
cryptnet.dll Base Address: 0x7FFAA6630000 Size: 135168
WINNSI.DLL Base Address: 0x7FFAAA790000 Size: 11776
socialclub.dll Base Address: 0x7FFA82A40000 Size: 2692608
chrome_elf.dll Base Address: 0x7FFA8B9B0000 Size: 901120
libcef.dll Base Address: 0x7FFA52830000 Size: 151009280
COMCTL32.dll Base Address: 0x7FFAA6840000 Size: 560128
COMDLG32.dll Base Address: 0x7FFAB01E0000 Size: 684032
OLEACC.dll Base Address: 0x7FFA9F8D0000 Size: 260608
NETAPI32.dll Base Address: 0x7FFA9E2D0000 Size: 47616
DWrite.dll Base Address: 0x7FFA97F80000 Size: 1601024
ncrypt.dll Base Address: 0x7FFAAEC70000 Size: 102400
UIAutomationCore.DLL Base Address: 0x7FFA8EA00000 Size: 2040832
USP10.dll Base Address: 0x7FFAA39F0000 Size: 512
urlmon.dll Base Address: 0x7FFAA2320000 Size: 1281536
CRYPTUI.dll Base Address: 0x7FFAA2970000 Size: 246272
credui.dll Base Address: 0x7FFAA3300000 Size: 55808
ESENT.dll Base Address: 0x7FFAA0DD0000 Size: 2585088
wevtapi.dll Base Address: 0x7FFAAA470000 Size: 296960
iertutil.dll Base Address: 0x7FFAA2A30000 Size: 551424
netutils.dll Base Address: 0x7FFAAE760000 Size: 19456
dxva2.dll Base Address: 0x7FFAA3710000 Size: 96256
srvcli.dll Base Address: 0x7FFAA22F0000 Size: 54272
DSROLE.DLL Base Address: 0x7FFAAAAF0000 Size: 7680
WKSCLI.DLL Base Address: 0x7FFAAE3F0000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFA9D6C0000 Size: 61440
NTASN1.dll Base Address: 0x7FFAAEC30000 Size: 81408
FirewallAPI.dll Base Address: 0x7FFAADE80000 Size: 329728
fwbase.dll Base Address: 0x7FFAADE40000 Size: 151552
FWPolicyIOMgr.dll Base Address: 0x7FFAA0020000 Size: 205824
wdmaud.drv Base Address: 0x7FFAA0A20000 Size: 193024
msacm32.drv Base Address: 0x7FFAA3CF0000 Size: 17920
MSACM32.dll Base Address: 0x7FFAA36F0000 Size: 74240
midimap.dll Base Address: 0x7FFAA3900000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFA93CC0000 Size: 42496
wbemprox.dll Base Address: 0x7FFA9E470000 Size: 27648
wbemcomn.dll Base Address: 0x7FFAA0CA0000 Size: 328704
wbemsvc.dll Base Address: 0x7FFA9CB10000 Size: 7168
fastprox.dll Base Address: 0x7FFA9CF90000 Size: 708608
mfsrcsnk.dll Base Address: 0x7FFA83100000 Size: 1873408
CompPkgSup.DLL Base Address: 0x7FFAA2520000 Size: 152576
Windows.Media.dll Base Address: 0x7FFA61C70000 Size: 5271040
Windows.ApplicationModel.dll Base Address: 0x7FFA98840000 Size: 556544
mp3dmod.dll Base Address: 0x7FFAA3140000 Size: 58880
AppXDeploymentClient.dll Base Address: 0x7FFAA9370000 Size: 658432
TextShaping.dll Base Address: 0x7FFAA0490000 Size: 304640
YimMenu.dll Base Address: 0x7FFA7D3F0000 Size: 8017920
D3DCOMPILER_47.dll Base Address: 0x7FFAAAF30000 Size: 3396608
MSVCP140_2.dll Base Address: 0x7FFAA0A80000 Size: 196096
winbrand.dll Base Address: 0x7FFA94720000 Size: 161280
xinput1_4.dll Base Address: 0x7FFAA7C00000 Size: 30208
schannel.DLL Base Address: 0x7FFAAE1A0000 Size: 486400
mskeyprotect.dll Base Address: 0x7FFA9A0D0000 Size: 44544
ncryptsslp.dll Base Address: 0x7FFA9A3A0000 Size: 78848
toxmod.dll Base Address: 0x7FFAA66B0000 Size: 106496
opusenc.dll Base Address: 0x7FFAA8050000 Size: 32768
fvad.dll Base Address: 0x7FFAA7360000 Size: 14848
libcurl.dll Base Address: 0x7FFAA2F90000 Size: 367616
opus.dll Base Address: 0x7FFAA0B10000 Size: 311296
zlib1.dll Base Address: 0x7FFAA6340000 Size: 54784
Dumping registers:
RAX: 0x0
RCX: 0x1A50D650000
RDX: 0x7FF63CF76100
RBX: 0x2DD5BDD698
RSI: 0x7FF63CF75DD0
RDI: 0x12
RSP: 0x2DD5BDCE78
RBP: 0x7FF63CF76100
R8:  0x7FF63CF75DD0
R9:  0x0
R10: 0x1A50E71DC00
R11: 0x7FF63CF76100
R12: 0x7FF63CF8B8F0
R13: 0x0
R14: 0x1A50D764D60
R15: 0x0
Dumping stacktrace:
[0]	YimMenu.dll+0x1A84A8 0x7FFA7D5984A8
[1]	GTA5.exe+0x16D79BA 0x7FF63BCD79BA
[2]	GTA5.exe+0x16CF250 0x7FF63BCCF250
[3]	GTA5.exe+0x16D490C 0x7FF63BCD490C
[4]	GTA5.exe+0x13FCC39 0x7FF63B9FCC39
[5]	GTA5.exe+0x16D4A39 0x7FF63BCD4A39
[6]	GTA5.exe+0x13FD016 0x7FF63B9FD016
[7]	YimMenu.dll+0x1A71F8 0x7FFA7D5971F8
[8]	GTA5.exe+0x13FD0C9 0x7FF63B9FD0C9
[9]	GTA5.exe+0x13FCDE2 0x7FF63B9FCDE2
[10]	GTA5.exe+0x1427AB7 0x7FF63BA27AB7
[11]	GTA5.exe+0x10C6D98 0x7FF63B6C6D98
[12]	GTA5.exe+0x162FA85 0x7FF63BC2FA85
[13]	GTA5.exe+0x162F2B7 0x7FF63BC2F2B7
[14]	GTA5.exe+0x27B6E 0x7FF63A627B6E
[15]	GTA5.exe+0x21283 0x7FF63A621283
[16]	GTA5.exe+0x162EEC0 0x7FF63BC2EEC0
[17]	GTA5.exe+0x1494 0x7FF63A601494
[18]	GTA5.exe+0x130538F 0x7FF63B90538F
[19]	GTA5.exe+0x1821344 0x7FF63BE21344
[20]	KERNEL32.DLL BaseThreadInitThunk
[21]	ntdll.dll RtlUserThreadStart
--------End of exception--------

[02:54:39.3464283][WARN/reaction.cpp:60] Received Modder Detection from SpongebZZRAPPER (92241767)
[02:54:47.6509625][WARN/reaction.cpp:60] Received Modder Detection from GTA768768JFDH464 (147386438)
[02:55:14.9210004][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[02:55:14.9211526][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":428002958,"type":3136273443,"cat":654913086,"pt":627259146,"slot":0
[02:56:15.0430549][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[02:56:15.0431342][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":428002958,"type":3136273443,"cat":654913086,"pt":627297208,"slot":0
>
```

Screenshot_9

### Store

Epic Games

### Language

Russian

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by Yimura**
With this PR users can have the game set in a different language than the menu and still have the vehicle list properly be rendered.

image

Closes #2871 
Closes #1409

### CODE REVIEW

**Comment by gir489returns** [comment]
@Yimura What is the status of this branch?

File: src/views/network/view_session_browser.cpp [hunk 1]
```diff
@@ -55,11 +56,17 @@ namespace big
...
-						    "SESSION_BROWSER_DISCRIMINATOR"_T, session.attributes.discriminator);
+						auto tool_tip = std::format("{}: {}\n{}: {}\n{}: {}\n{}: {}\n{}: {:X}",
+						    "SESSION_BROWSER_NUM_PLAYERS"_T,
+						    session.attributes.player_count,
+						    "REGION"_T,
+						    regions[session.attributes.region].name,
+						    "LANGUAGE"_T,
+						    languages.at((eGameLanguage)session.attributes.language),
+						    "SESSION_BROWSER_HOST_RID"_T,
+						    session.info.m_net_player_data.m_gamer_handle.m_rockstar_id, // TODO: this is not accurate
```
Comment (gir489returns) [inline src/views/network/view_session_browser.cpp:67]: @maybegreat48 Why is this not accurate?

**Review by gir489returns — APPROVED** [review]
