### PR TITLE
fix: ped body clean up logic

### LINKED ISSUE #2579: [Improvement]: remove clean loop and fix current clean logic
### Which feature

whenever player gets damaged it has blood decals, dirt, water & scars etc.
One can use clean button to clean player. It will not clean scars. Same is with clean loop bcz both use same function.

### remove clean loop
Clean loop purpose is to continuously clean player and so no need to manually open menu and hit the clean button. I think one can clean themselves by simply hitting clean button as necessary rather than running bunch of natives every frame.

### How to clean scars?
well one can add modify the clean function as -

```c++
	inline void clean_ped()
	{
		PED::CLEAR_PED_BLOOD_DAMAGE(ped);
		PED::CLEAR_PED_ENV_DIRT(ped);

                // https://forum.cfx.re/t/information-needed-to-clear-visible-player-damage-scars-etc/283216 
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 0, "ALL");
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 1, "ALL");
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 2, "ALL");
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 3, "ALL");
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 4, "ALL");
 		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 5, "ALL");
	}
```

i also removed `PED::CLEAR_PED_WETNESS(player_ped);` though its a decision one can make. It just removes water when you are wet.

### Reason

- clean loop is not such required. cleaning can be done as required.
- scars did not cleaned up. The above code guarantees one's beauty back.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lonelybud**
fixes #2579

### CODE REVIEW

File: src/util/entity.cpp [hunk 1]
```diff
@@ -12,12 +12,19 @@ namespace big::entity
...
-		PED::CLEAR_PED_ENV_DIRT(player_ped);
-		PED::RESET_PED_VISIBLE_DAMAGE(player_ped);
+		PED::CLEAR_PED_BLOOD_DAMAGE(ped);
+		PED::CLEAR_PED_WETNESS(ped);
+		PED::CLEAR_PED_ENV_DIRT(ped);
+		PED::RESET_PED_VISIBLE_DAMAGE(ped);
+			
+		// https://forum.cfx.re/t/information-needed-to-clear-visible-player-damage-scars-etc/283216
+		// https://docs.fivem.net/natives/?_0x397C38AA7B4A5F83
+		PED::CLEAR_PED_DAMAGE_DECAL_BY_ZONE(ped, 0, "ALL");
```
Comment (xiaoxiao921) [inline src/util/entity.cpp]: Use a loop

**Review by xiaoxiao921 — CHANGES_REQUESTED** [review]

File: src/util/entity.cpp (hunk 1 above)
Comment (lonelybud) [reply src/util/entity.cpp]: done

**Review by xiaoxiao921 — APPROVED** [review]
