### PR TITLE
Start Script Activity Session Check

### LINKED ISSUE #3042: [Bug]: YimMenu Appears to Block Some Valid Start Script Events
### Describe the bug

YimMenu appears to be blocking some valid start script events even with protections disabled.
Behavior is consistent with https://github.com/YimMenu/YimMenu/issues/3001

image

image

Events launch fine if I'm host, but when I'm not, the following behavior occurs:
1) Quick Job launches and I am able to select a vehicle/loadout and proceed through the setup screens until "Ready to Play"
2) Once the event is launched by the host, the game appears to try to load for a few seconds
3) Fly-up freemode transition screen begins, and I'm placed back into freemode

Not all events seem to be affected, but it's been difficult to verify every event since people don't even play some of them anymore.

Series Events I've tested this with (I was not host in any of these sessions):
Open Wheel Series (didn't work, returned to freemode)
Drift Series (didn't work, returned to freemode)
Community Series (go kart race, worked, 2-person lobby and the other was host)
Stunt Series (didn't work, returned to freemode)

### Steps To Reproduce

1. Disable all protections
2. Enter a Series Mode event
3. Validate that you are not host
4. Wait for event to begin - notice YimMenu issues a Blocked Script notification in the event lobby (see screenshot)
5. Confirm that you get booted out back into freemode

### Expected Behavior

Event launches normally.

### Logs

Names redacted to protect the innocent.

```
[20:36:01.0295195][WARN/reaction.cpp:60] Received Start Script from [PLAYER] (1448XXXX)
[20:38:54.2340446][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[20:38:54.2342704][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[20:42:49.4592443][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[20:42:49.4593573][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":6934549,"type":3136273443,"cat":654913086,"pt":3274731811,"slot":0
[20:45:15.8930801][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[20:45:33.4695242][WARN/reaction.cpp:60] Received Start Script from [PLAYER] (14987XXXX)
[20:52:37.1679157][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[20:52:37.1680768][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
```

### Screenshots / Video

https://github.com/YimMenu/YimMenu/assets/13259220/f25d9673-80c4-406c-ad80-4ac510af32da

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by rkwapisz**
Checks if the player is in an activity session (meaning a lobby for races, events, etc. -- not freemode) and prevents script protection from blocking legitimate event launch scripts defined in bad_script_ids. Script protection is still in place outside of activity sessions.

Probably no need for a Start Script protection toggle (yet).

Closes https://github.com/YimMenu/YimMenu/issues/3042 and https://github.com/YimMenu/YimMenu/issues/3001

### CODE REVIEW

**Review by gir489returns — CHANGES_REQUESTED** [review]
Seperate out the scripts from malicious to required. There is obviously no reason in hell someone should attempt to start fm_intro on us or AM_PI_MENU at all. There might be legitamiate reasons for the rest of the scripts.

**Comment by gir489returns** [comment]
SCTV, fm_intro, AM_PI_MENU and Pilot_School_MP are malicious, always reject.

ggsm_arcade, wizard_arcade, road_arcade, grid_arcade_cabinet, scroll_arcade_cabinet are sus at best, but should be considered legit for the moment, as you could easily close them if encountered, and we can escilate them later if required.

Anything with FM_ in front of it should be rejected during missions but allowed in freemode explicily as they are freemode scripts.

**Comment by rkwapisz** [comment]
Separated out the script IDs providing full blocking, blocking in activity, and notify only for the iffy ones.

**Comment by rkwapisz** [comment]
After some testing it appears 221 /*FM_Race_Controler*/ is required inside the activity session for it to properly launch. Haven't yet tested the other FM scripts.

**Comment by rkwapisz** [comment]
We'll be using a different notification from the default start_script reaction that says "Blocked Start Script" when issuing notifications to the player without actually blocking the script.

The following change will be made to the Translations repo:
`"REACTION_START_SCRIPT_ALLOWED": "Allowed Start Script from {}",`

File: src/backend/reactions/reaction.cpp [hunk 1]
```diff
@@ -71,10 +71,34 @@ namespace big
 
 		if (notify)
 		{
+
```
Comment (gir489returns) [inline src/backend/reactions/reaction.cpp:74]: Unncessary whitespace change.

**Review by gir489returns — CHANGES_REQUESTED** [review]
Run the CMake auto formatter.

File: src/backend/reactions/reaction.cpp (hunk 1 above)
Comment (rkwapisz) [reply src/backend/reactions/reaction.cpp]: Applied clang formatting

File: src/hooks/protections/script_event_handler.cpp [hunk 2]
```diff
@@ -420,18 +420,52 @@ namespace big
...
-			break;
+
+			// IDs to be blocked inside an activity session (basically anything FM)
+			static const std::unordered_set<int> block_in_activity_ids = {
+			    216 /*FM_Impromptu_DM_Controler*/,
+			    218 /*fm_deathmatch_controler*/,
+			    222 /*FM_Horde_Controler*/,
+			};
+
+			if (NETWORK::NETWORK_IS_ACTIVITY_SESSION() && block_in_activity_ids.contains(script_id))
```
Comment (maybegreat48) [inline src/hooks/protections/script_event_handler.cpp]: The logic is flipped: activity sessions are mission sessions, and these scripts shouldn't be blocked here

Comment (rkwapisz) [reply src/hooks/protections/script_event_handler.cpp]: This tracks with my observations of 221 /*FM_Race_Controler*/, but I was confused by the FM_ prefix.

File: src/hooks/protections/script_event_handler.cpp [hunk 3]
```diff
@@ -420,18 +420,52 @@ namespace big
...
+
+			if (always_block_ids.contains(script_id))
 			{
 				g.reactions.start_script.process(plyr);
 				return true;
 			}
-			break;
+
+			// IDs to be blocked inside a freemode session (don't get tricked by the fm_ prefix)
+			static const std::unordered_set<int> block_in_freemode_ids = {
```
Comment (maybegreat48) [inline src/hooks/protections/script_event_handler.cpp]: Check the toxic features tab for more IDs to block (there are more missions and activities like darts too). I'd also recommend refactoring this to another file since the IDs change every update, and easier to have them all in one place. The golf and arcade machine scripts can be blocked unconditionally. But LGTM otherwise

Comment (rkwapisz) [reply src/hooks/protections/script_event_handler.cpp]: I can get started on some of these ideas, but I'm having trouble understanding the best way to map script IDs to their names. I want to make sure we're using up-to-date IDs for now.

Comment (rkwapisz) [reply src/hooks/protections/script_event_handler.cpp]: Found the answer to my own question:
https://github.com/root-cause/v-decompiled-scripts/blob/master/am_launcher.c

**Comment by rkwapisz** [comment]
Let's try this. We'll maintain a list of potentially troublesome scripts inside script_database.hpp
Keeping an ordered list can let us make adjustments easily in case we want to reclassify a script in the future.

I've also updated start_script.cpp with what I believe to be up-to-date script IDs.

**Comment by lonelybud** [comment]
i was wondering whether the code here works. looks like second layer of protection? - 
https://github.com/YimMenu/YimMenu/blob/master/src/native_hooks/am_launcher.hpp

**Comment by rkwapisz** [comment]
> i was wondering whether the code here works. looks like second layer of protection? - https://github.com/YimMenu/YimMenu/blob/master/src/native_hooks/am_launcher.hpp

Hmm I didn't notice this. Looks like this functionality is obsoleted by the script ID checks in the event handler.

**Comment by rkwapisz** [comment]
And now I'm confused why these updates to the script handler worked if the scripts were also being blocked inside the  launcher... ??

File: src/util/script_database.hpp [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+namespace big
+{
+    enum class ProtectionStatus
+    {
+        ALLOWED_NOTIFY,
+        BLOCK_ALWAYS,
+        BLOCK_IN_FREEMODE // Renamed from BLOCK_IN_FM
+    };
+
+    struct ScriptInfo
```
Comment (Yimura) [inline src/util/script_database.hpp]: The YimMenu code base uses `snake_case`, only  the R* classes and enums are an exception to this.

File: src/util/script_database.hpp [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+    {
+        std::string name;
+        ProtectionStatus status;
+    };
+
+    class ScriptProtectionDB
```
Comment (Yimura) [inline src/util/script_database.hpp]: The YimMenu code base uses `snake_case`, only  the R* classes and enums are an exception to this.

File: src/util/script_database.hpp [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+                {214, {"tennis_network_mp", ProtectionStatus::BLOCK_IN_FREEMODE}},
+                {215, {"Pilot_School_MP", ProtectionStatus::BLOCK_ALWAYS}},
+                {216, {"FM_Impromptu_DM_Controler", ProtectionStatus::BLOCK_IN_FREEMODE}},
+                {218, {"fm_deathmatch_controler", ProtectionStatus::BLOCK_IN_FREEMODE}},
+                {221, {"FM_Race_Controler", ProtectionStatus::BLOCK_IN_FREEMODE}},
+                {222, {"FM_Horde_Controler", ProtectionStatus::BLOCK_IN_FREEMODE}},
+                {224, {"am_darts_apartment", ProtectionStatus::BLOCK_ALWAYS}},
+                {226, {"grid_arcade_cabinet", ProtectionStatus::BLOCK_ALWAYS}},
+                {227, {"scroll_arcade_cabinet", ProtectionStatus::BLOCK_ALWAYS}},
+			    {228, {"example_arcade", ProtectionStatus::BLOCK_ALWAYS}},
```
Comment (Yimura) [inline src/util/script_database.hpp]: Random indent.

**Review by Yimura — CHANGES_REQUESTED** [review]
Feel free to mark any comments as resolved once you've gone through them.

File: src/util/script_database.hpp (hunk 4 above)
Comment (rkwapisz) [reply src/util/script_database.hpp]: Fixed with [ddb1e17](https://github.com/YimMenu/YimMenu/pull/3045/commits/ddb1e17a6c438c48d53fc190e7a36fa39999afb3).

File: src/util/script_database.hpp (hunk 5 above)
Comment (rkwapisz) [reply src/util/script_database.hpp]: Fixed with [ddb1e17](https://github.com/YimMenu/YimMenu/pull/3045/commits/ddb1e17a6c438c48d53fc190e7a36fa39999afb3).

File: src/util/script_database.hpp (hunk 6 above)
Comment (rkwapisz) [reply src/util/script_database.hpp]: Fixed with [ddb1e17](https://github.com/YimMenu/YimMenu/pull/3045/commits/ddb1e17a6c438c48d53fc190e7a36fa39999afb3).

Did not see this indent in either VS or NP++. Clang is going to be a lot more useful moving forward than I thought.

**Review by Yimura — APPROVED** [review]
