### PR TITLE
fix nlohmann potential throw in ped outfit

### LINKED ISSUE #2893: [Bug]: Crash with invalid json through self_persist_outfit looped
### Describe the bug

When i open game and go singleplayer or multiplayer and open my mod it crush my game, I tried a few injector and everything looks the same.

### Steps To Reproduce

1.open game 2.go to single/multi 3.open mod 4.see crash log

### Expected Behavior

I expected that my mod will work well not crash.

### Logs and/or screenshots

[crash log.txt](https://github.com/YimMenu/YimMenu/files/14809221/crash.log.txt)

### Store

Rockstar

### Language

Polish

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by xiaoxiao921**
Fix #2893

### CODE REVIEW

File: src/backend/looped/self/persist_outfit.cpp [hunk 1]
```diff
@@ -15,13 +15,13 @@ namespace big
...
-				break;
-			}
-			default: return false; //For non-normal models
+		case "mp_m_freemode_01"_J: break;
+		case "mp_f_freemode_01"_J:
+		{
+			offset = 1;
+			break;
+		}
+		default: return false; //For non-normal models
```
Comment (gir489returns) [inline src/backend/looped/self/persist_outfit.cpp:24]: Unnecessary whitespace change.

File: src/backend/looped/self/persist_outfit.cpp [hunk 2]
```diff
@@ -56,7 +56,14 @@ namespace big
...
 			std::ifstream i(saved_outfit_path.get_file(persisting_outfit).get_path());
 			outfit.clear();
-			i >> outfit;
+			try
+			{
+				i >> outfit;
+			}
+			catch (const std::exception& e)
+			{
+				outfit = {};
```
Comment (gir489returns) [inline src/backend/looped/self/persist_outfit.cpp:65]: LOG(INFO) the exception string, and also zero out g.self.persist_outfit, otherwise it's just going to attempt to try again next frame.

**Review by gir489returns — CHANGES_REQUESTED** [review]

File: src/backend/looped/self/persist_outfit.cpp (hunk 1 above)
Comment (xiaoxiao921) [reply src/backend/looped/self/persist_outfit.cpp:24]: This is just how it should've been since the beginning, my IDE apply the clang format of the YimMenu project when I save the file.

Comment (gir489returns) [reply src/backend/looped/self/persist_outfit.cpp:24]: I think it looks stupid. The cases should be indented to the switches, since they belong to the switch's scope, not the other way around.

Comment (xiaoxiao921) [reply src/backend/looped/self/persist_outfit.cpp:24]: I agree, but this is how the clang-format file was defined a long time ago now, any change to it would mean we'd need to do a PR that fix the files to the new formatting

**Review by gir489returns — APPROVED** [review]

**Review by Yimura — APPROVED** [review]
