### PR TITLE
Fixed player getting ejected from nightclub while holding weapon.

### LINKED ISSUE #2095: [Bug]: Allow Weapon In Interior hard conflict with night club spawn point
### Describe the bug

I am not sure of the exact cause of the bug, but while the menu is loaded, after joining a session and finishing swoopdown, the game is left with a black screen and the loading text "Initializing" and is unable to continue.

### Steps To Reproduce

1. Escape Menu > Online >Join New Session
2. Wait approx. 20 minutes for the lobby to load (it never completes)
3. This can be cancelled with the use of an external tool (eg. Kiddion) to Leave Online. The other option is to alt+f4 out of the game or kill the process, which unloads the menu.
4. Repeating the escape menu method, or switching from your SP character to Online does not change the result.
5. Leave Online again.
6. In singleplayer, unload Yimmenu.
7. Go online by joining a session or switching character again.
8. A session may now be successfully joined.
9. Reinject Yim from here.

### Expected Behavior

There should not be a hitch when joining a new session. I should not need to unload the menu to continue to a new session.

### Logs and/or screenshots

```
[21:42:22.6282057][INFO/main.cpp:65] Yim's Menu Initializing
[21:42:22.6282206][INFO/main.cpp:66] Git Info
	Branch:	master
	Hash:	1594ee1f7680731dd20c0aa194bc61137b9ebf72
	Date:	Sat Sep 2 20:58:13 2023
[21:42:22.6282264][DEBUG/thread_pool.cpp:21] Resizing thread pool from 0 to 4
[21:42:22.6282983][INFO/main.cpp:69] Thread pool initialized.
[21:42:22.6294480][INFO/main.cpp:72] Settings Loaded.
[21:42:22.6294503][DEBUG/thread_pool.cpp:95] Thread 21868 executing settings.cpp:18
[21:42:22.6295395][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[21:42:22.6295428][INFO/pointers.cpp:1697] Loading pointers instance from cache
[21:42:22.6295436][INFO/pointers.cpp:1706] Pointers cache: Loading 202 fields from the cache
[21:42:22.6295470][DEBUG/module.cpp:50] Waiting for socialclub.dll...
[21:42:22.6295702][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[21:42:22.6295713][INFO/pointers.cpp:1697] Loading pointers instance from cache
[21:42:22.6295720][INFO/pointers.cpp:1706] Pointers cache: Loading 5 fields from the cache
[21:42:22.6295822][INFO/main.cpp:75] Pointers initialized.
[21:42:22.6296377][INFO/main.cpp:78] Byte Patch Manager initialized.
[21:42:22.9112058][INFO/main.cpp:81] Renderer initialized.
[21:42:23.0638082][INFO/main.cpp:85] Fiber pool initialized.
[21:42:23.2029552][INFO/main.cpp:88] Translation Service initialized.
[21:42:23.2146680][INFO/main.cpp:91] Hooking initialized.
[21:42:23.2164257][DEBUG/gta_data_service.cpp:159] Loading data from cache.
[21:42:23.2164304][INFO/gta_data_service.cpp:171] Loading 1029 peds from cache.
[21:42:23.2166479][INFO/gta_data_service.cpp:189] Loading 810 vehicles from cache.
[21:42:23.2168381][INFO/gta_data_service.cpp:206] Loading 117 weapons from cache.
[21:42:23.2168399][INFO/gta_data_service.cpp:207] Loading 378 weapon components from cache.
[21:42:23.2168479][DEBUG/gta_data_service.cpp:165] Loaded all data from cache.
[21:42:23.2171993][INFO/main.cpp:111] Registered service instances...
[21:42:23.2172605][INFO/main.cpp:132] Scripts registered.
[21:42:23.2361260][INFO/main.cpp:135] Hooking enabled.
[21:42:23.2368803][INFO/main.cpp:138] Dynamic native hooker initialized.
[21:42:23.2369728][INFO/main.cpp:141] Lua manager initialized.
[21:42:23.2369879][DEBUG/thread_pool.cpp:95] Thread 16036 executing player_database_service.cpp:276
[21:42:23.2999882][INFO/backend.cpp:51] Starting script: Self
[21:42:23.3000000][INFO/backend.cpp:76] Starting script: Weapons
[21:42:23.3000055][INFO/backend.cpp:99] Starting script: Vehicles
[21:42:23.3000125][INFO/backend.cpp:115] Starting script: Miscellaneous
[21:42:23.3000176][INFO/backend.cpp:135] Starting script: Remote
[21:42:23.3000265][INFO/backend.cpp:150] Starting script: Ls customs
[21:42:23.3000286][INFO/backend.cpp:162] Starting script: Rainbow paint
[21:42:23.3000298][INFO/backend.cpp:174] Starting script: Disable Control Action
[21:42:23.3000315][INFO/backend.cpp:187] Starting script: World
[21:42:23.3109476][INFO/tunables_service.cpp:36] Loading tunables from cache
[21:49:35.5843479][WARN/reaction.cpp:25] Received Modder Detection from Danielx_Nx (172705451)
[21:58:43.8685611][WARN/notify.hpp:30] Blocked sound spam crash from Chrissywarrior (181011055)
[21:58:43.8685750][WARN/reaction.cpp:25] Received Crash from Chrissywarrior (181011055)
[21:59:42.9687460][WARN/reaction.cpp:25] Received Modder Detection from jaceway0 (235747980)
[22:09:02.1203388][WARN/notify.hpp:30] Blocked sound spam crash from xcacasca (234407633)
[22:09:02.1203528][WARN/reaction.cpp:25] Received Crash from xcacasca (234407633)
[22:09:03.1451462][WARN/notify.hpp:30] Blocked sound spam crash from xcacasca (234407633)
[22:09:03.1451593][WARN/reaction.cpp:25] Received Crash from xcacasca (234407633)
[22:09:04.3449003][WARN/notify.hpp:30] Blocked sound spam crash from xcacasca (234407633)
[22:09:04.3449157][WARN/reaction.cpp:25] Received Crash from xcacasca (234407633)
[22:09:05.3562993][WARN/notify.hpp:30] Blocked sound spam crash from xcacasca (234407633)
[22:09:05.3563141][WARN/reaction.cpp:25] Received Crash from xcacasca (234407633)
[22:09:06.3815189][WARN/notify.hpp:30] Blocked sound spam crash from xcacasca (234407633)
[22:09:06.3815322][WARN/reaction.cpp:25] Received Crash from xcacasca (234407633)
[22:09:08.1817885][WARN/notify.hpp:30] Blocked sound spam crash from xcacasca (234407633)
[22:09:08.1818029][WARN/reaction.cpp:25] Received Crash from xcacasca (234407633)
[22:09:09.2063263][WARN/notify.hpp:30] Blocked sound spam crash from xcacasca (234407633)
[22:09:09.2063398][WARN/reaction.cpp:25] Received Crash from xcacasca (234407633)
[22:09:10.4308935][WARN/notify.hpp:30] Blocked sound spam crash from xcacasca (234407633)
[22:09:10.4309105][WARN/reaction.cpp:25] Received Crash from xcacasca (234407633)[22:09:49.7113636][INFO/main.cpp:152] Scripts unregistered.
[22:09:49.7113766][INFO/main.cpp:155] Lua manager uninitialized.
[22:09:49.7347461][INFO/main.cpp:158] Hooking disabled.
[22:09:49.7348237][INFO/main.cpp:161] Dynamic native hooker uninitialized.
[22:09:49.7348301][DEBUG/thread_pool.cpp:108] Thread 16036 exiting...
[22:09:49.7348322][DEBUG/thread_pool.cpp:108] Thread 7220 exiting...
[22:09:49.7348342][DEBUG/thread_pool.cpp:108] Thread 18812 exiting...
[22:09:49.7572219][DEBUG/thread_pool.cpp:108] Thread 21868 exiting...
[22:09:49.7576873][INFO/main.cpp:169] Destroyed thread pool.
[22:09:49.7577125][INFO/main.cpp:172] Script Connection Service reset.
[22:09:49.7587130][INFO/main.cpp:174] Tunables Service reset.
[22:09:49.7587235][INFO/main.cpp:176] Hotkey Service reset.
[22:09:49.7587265][INFO/main.cpp:178] Matchmaking Service reset.
[22:09:49.7587495][INFO/main.cpp:180] Player Database Service reset.
[22:09:49.7587518][INFO/main.cpp:182] API Service reset.
[22:09:49.7590023][INFO/main.cpp:184] Script Patcher Service reset.
[22:09:49.7590100][INFO/main.cpp:186] Gui Service reset.
[22:09:49.7592473][INFO/main.cpp:188] GTA Data Service reset.
[22:09:49.7592499][INFO/main.cpp:190] Vehicle Service reset.
[22:09:49.7592518][INFO/main.cpp:192] Model Preview Service reset.
[22:09:49.7592533][INFO/main.cpp:194] Mobile Service reset.
[22:09:49.7592559][INFO/main.cpp:196] Player Service reset.
[22:09:49.7592579][INFO/main.cpp:198] Pickup Service reset.
[22:09:49.7592620][INFO/main.cpp:200] Custom Text Service reset.
[22:09:49.7592694][INFO/main.cpp:202] Context Service reset.
[22:09:49.7592709][INFO/main.cpp:204] Xml Vehicles Service reset.
[22:09:49.7592713][INFO/main.cpp:205] Services uninitialized.
[22:09:49.7592937][INFO/main.cpp:208] Hooking uninitialized.
[22:09:49.7592972][INFO/main.cpp:211] Fiber pool uninitialized.
[22:09:49.7815775][INFO/main.cpp:214] Renderer uninitialized.
[22:09:49.7816867][INFO/main.cpp:217] Byte Patch Manager uninitialized.
[22:09:49.7816916][INFO/main.cpp:220] Pointers uninitialized.
[22:09:49.7816962][INFO/main.cpp:223] Thread pool uninitialized.
[22:09:49.7816977][INFO/main.cpp:225] Farewell!
```

### Store

Rockstar

### Additional context

If it helps, my Spawn Location is set to my Nightclub.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #2445: [Bug]: Using Allow Weapons in Interiors causes you to get ejected from nightclub.
### Describe the bug

If you use Allow Weapons in Interiors and are holding a weapon in your nightclub, you will be ejected.

### Steps To Reproduce

1. Enable Allow Weapons in Interior.
2. Go to your nightclub.
3. Take out a weapon.
4. Bug appears.

### Expected Behavior

You should be able to use your weapon inside the nightclub.

### Logs and/or screenshots

_No response_

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by gir489returns**
Closes #2095
Closes #2445

### CODE REVIEW

File: src/backend/looped/tunables/allow_weapons_in_interiors.cpp [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+		virtual void on_disable() override
+		{
+			if (auto tunable = g_tunables_service->get_tunable<PBOOL>(-298441869))
+			{
+				*tunable = TRUE;
+			}
+		}
+	};
+
+	allow_weapons_in_interiors g_disable_phone("allowwepsinside", "VIEW_WEAPON_ALLOW_WEAPONS_IN_INTERIORS", "", g.weapons.interior_weapon);
```
Comment (maybegreat48) [inline src/backend/looped/tunables/allow_weapons_in_interiors.cpp]: `g_disable_phone`?

**Review by Yimura — APPROVED** [review]
