### PR TITLE
Remove Unknown Player OOM Kick False Positives

### LINKED ISSUE #3169: [Bug]: Possibly false-positive OOM kick protection notification
### Describe the bug

From time to time I get notified about something trying to OOM kick me. Notification doesn't show who exactly is trying to do this as well as nothing appears in the logs. Also nobody is being kicked even though I was the host and enabled kick reaction when somebody is trying to kick me.

### Steps To Reproduce

Not sure how can one reproduce this. Once I mentioned that this occured shortly after a player with spoofed host token joined the session. As per description, nothing appeared in the logs, only notification with empty username.

### Expected Behavior

Player name should be visible/notification should not appear in case it's false-positive.

### Logs

I'm going to attach logs from my last session where this occured. `kyluzzo (38956811)` was the player who joined the session where I was the host and game detected him using spoofed host token.

<details>
<summary>LOGS</summary>

```
[22:13:19.7718437][INFO/main.cpp:156] Settings Loaded and logger initialized.
[22:13:19.7718699][INFO/main.cpp:158] Yim's Menu Initializing
[22:13:19.7718716][INFO/main.cpp:159] Git Info
	Branch:	master
	Hash:	54c7dada828384b96c4bffd3a0d8fd87c98a017d
	Date:	Sun May 19 20:43:20 2024
[22:13:19.7719594][INFO/main.cpp:171] Windows 11 Pro Version 23H2 (OS Build 22631.3593)
[22:13:19.7742164][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[22:13:19.7743277][INFO/main.cpp:179] Thread pool initialized.
[22:13:19.7796486][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[22:13:19.7796611][INFO/pointers.cpp:1851] Loading pointers instance from cache
[22:13:19.7796626][INFO/pointers.cpp:1860] Pointers cache: Loading 221 fields from the cache
[22:13:19.7796723][DEBUG/module.cpp:55] Waiting for socialclub.dll...
[22:13:19.7831991][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[22:13:19.7832081][INFO/pointers.cpp:1851] Loading pointers instance from cache
[22:13:19.7832104][INFO/pointers.cpp:1860] Pointers cache: Loading 5 fields from the cache
[22:13:19.7832406][INFO/main.cpp:182] Pointers initialized.
[22:13:19.7832481][INFO/main.cpp:189] Disabled anticheat gameskeleton.
[22:13:19.7834734][INFO/main.cpp:192] Byte Patch Manager initialized.
[22:13:19.7838073][INFO/main.cpp:195] Renderer initialized.
[22:13:19.7889355][INFO/main.cpp:199] Fiber pool initialized.
[22:13:19.7934651][INFO/main.cpp:202] HTTP Client initialized.
[22:13:20.0825497][INFO/translation_service.cpp:39] Languages outdated, downloading new translations.
[22:13:20.3226282][DEBUG/thread_pool.cpp:96] Thread 26384 executing font_mgr.cpp:104
[22:13:20.3235056][INFO/main.cpp:205] Translation Service initialized.
[22:13:20.3416585][INFO/main.cpp:208] Hooking initialized.
[22:13:20.3587536][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[22:13:20.3587656][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[22:13:20.3590771][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[22:13:20.3592683][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[22:13:20.3592723][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[22:13:20.3592867][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[22:13:20.3678632][DEBUG/thread_pool.cpp:96] Thread 26384 executing player_database_service.cpp:312
[22:13:20.3679726][INFO/main.cpp:228] Registered service instances...
[22:13:20.3679846][INFO/main.cpp:231] Finished initialising services.
[22:13:20.3680860][INFO/main.cpp:252] Scripts registered.
[22:13:20.5004106][INFO/main.cpp:255] Hooking enabled.
[22:13:20.5016708][INFO/main.cpp:258] Dynamic native hooker initialized.
[22:13:20.5019399][INFO/main.cpp:262] Lua manager initialized.
[22:13:20.5693931][INFO/backend.cpp:53] Starting script: Self
[22:13:20.5694134][INFO/backend.cpp:78] Starting script: Weapons
[22:13:20.5694217][INFO/backend.cpp:101] Starting script: Vehicles
[22:13:20.5694352][INFO/backend.cpp:117] Starting script: Miscellaneous
[22:13:20.5694806][INFO/backend.cpp:140] Starting script: Remote
[22:13:20.5694850][INFO/backend.cpp:155] Starting script: Ls customs
[22:13:20.5694887][INFO/backend.cpp:167] Starting script: Rainbow paint
[22:13:20.5694903][INFO/backend.cpp:179] Starting script: Disable Control Action
[22:13:20.5694923][INFO/backend.cpp:192] Starting script: World
[22:13:20.5822024][INFO/tunables_service.cpp:36] Loading tunables from cache
[22:13:58.5914345][DEBUG/script_function.cpp:35] Found pattern RSD in script PauseMenu_Multiplayer
[22:14:31.4171543][WARN/prepare_metric_for_sending.cpp:101] BAD METRIC: RDEV; DATA: "g":"SC 162411256"
[22:14:31.4171723][WARN/prepare_metric_for_sending.cpp:101] BAD METRIC: RQA; DATA: "g":"SC 162411256"
[22:15:43.0115967][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x318D08
[22:15:43.0125109][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x335660
[22:15:43.0125252][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x335638
[22:15:43.0125400][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x4015B8
[22:15:43.0162575][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x45B164
[22:15:43.0163355][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x45A3A8
[22:15:43.0163382][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x5CAA60
[22:15:43.0179174][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x961FBC
[22:15:43.0179341][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0xA66114
[22:15:43.0185478][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F09C
[22:15:43.0185589][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F0C4
[22:15:43.0185687][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F0EC
[22:15:43.0185726][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F074
[22:24:20.0424440][WARN/prepare_metric_for_sending.cpp:101] BAD METRIC: REPORT_INVALIDMODEL; DATA: "a":"SC 165263235","b":959275690,"c":401263359,"d":[-42.61,48.22,71.72],"e":[-1391.06,-187.59,-50.00],"f":-7507643555509098746,"g":6042026991599055260,"h":650612217,"i":1104331669,"n":2752,"op":[-48.00,-6.75,2.00],"or":[0.43,-0.28,-0.44],"os":[1.00,1.00
[22:24:20.0424743][WARN/prepare_metric_for_sending.cpp:101] BAD METRIC: REPORT_INVALIDMODEL; DATA: "a":"SC 165263235","b":959275690,"c":401263359,"d":[-47.26,38.99,71.72],"e":[-1389.40,-200.13,-50.00],"f":-7507643555509098746,"g":6042026991599055260,"h":650612217,"i":1104331669,"n":2753,"op":[-48.00,-6.75,2.00],"or":[-0.04,-0.14,0.65],"os":[1.00,1.00
[22:46:25.1764204][WARN/prepare_metric_for_sending.cpp:101] BAD METRIC: REPORT_INVALIDMODEL; DATA: "a":"SC 44873337","b":959275690,"c":401263359,"d":[-122.06,5.97,255.57],"e":[1314.47,-1339.98,49.76],"f":-7507643555509098746,"g":6042026991599055260,"h":650612217,"i":-269010440,"n":2752,"op":[-47.79,-6.90,-13.60],"or":[0.74,0.09,0.65],"os":[1.00,1.00
[22:52:16.5144674][WARN/reaction.cpp:59] Received Modder Detection from Sjonie_NL (196547442)
[22:57:40.6827249][WARN/reaction.cpp:59] Received Modder Detection from Palemoonlight_ (162577400)
[22:58:29.4846216][WARN/prepare_metric_for_sending.cpp:101] BAD METRIC: RDEV; DATA: "g":"SC 162577400"
[23:12:15.6561820][WARN/interloper_reaction.cpp:29] Received Spectate Others from GXObin (196600109), victim is --SoulTaker--
[23:18:55.8509959][WARN/interloper_reaction.cpp:29] Received Spectate Others from GXObin (196600109), victim is AcTivPlus
[23:19:25.1545611][WARN/interloper_reaction.cpp:29] Received Spectate Others from GXObin (196600109), victim is DIRECTOR1754
[23:19:56.0575062][WARN/reaction.cpp:59] Received Modder Detection from kyluzzo (38956811)
[23:19:56.0636290][WARN/reaction.cpp:59] Received Modder Detection from kyluzzo (38956811)
[23:19:56.4385178][WARN/interloper_reaction.cpp:29] Received Spectate Others from GXObin (196600109), victim is DIRECTOR1754

```
</details>

### Screenshots / Video

Grand Theft Auto V Screenshot 2024 05 22 - 01 58 10 34
Grand Theft Auto V Screenshot 2024 05 16 - 19 25 55 60
Grand Theft Auto V Screenshot 2024 05 05 - 00 38 18 00

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Additional context

While creating this issue and looking over the screenshot I've uploaded I mentioned that they have one thing in common - multiple players joining the session simultaneously. Maybe this is the potential cause.

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by Rxann**
Closes #3169

Thanks @maybegreat48 for the updated values!

### CODE REVIEW

File: src/hooks/protections/receive_net_message.cpp [hunk 1]
```diff
@@ -259,7 +259,7 @@ namespace big
...
+			    (g.debug.logs.packet_logs == 2 && msgType != rage::eNetMessage::MsgCloneSync && msgType != rage::eNetMessage::MsgPackedCloneSyncACKs && msgType != rage::eNetMessage::MsgPackedEvents && msgType != rage::eNetMessage::MsgPackedReliables && msgType != rage::eNetMessage::MsgPackedEventReliablesMsgs && msgType != rage::eNetMessage::MsgNetArrayMgrUpdate && msgType != rage::eNetMessage::MsgNetArrayMgrSplitUpdateAck && msgType != rage::eNetMessage::MsgNetArrayMgrUpdateAck && msgType != rage::eNetMessage::MsgScriptHandshakeAck && msgType != rage::eNetMessage::MsgScriptHandshake && msgType != rage::eNetMessage::MsgScriptJoin && msgType != rage::eNetMessage::MsgScriptJoinAck && msgType != rage::eNetMessage::MsgScriptJoinHostAck && msgType != rage::eNetMessage::MsgRequestObjectIds && msgType != rage::eNetMessage::MsgInformObjectIds && msgType != rage::eNetMessage::MsgNetTimeSync)) //FILTERED
```
Comment (gir489returns) [inline src/hooks/protections/receive_net_message.cpp:262]: Unncessary whitespace change as usual.

**Review by gir489returns — CHANGES_REQUESTED** [review]
OOM_KICK I think has that {} shown in the screenshots. Either pass it nothing which will still make it look weird, or make your own translation.

File: src/hooks/protections/receive_net_message.cpp (hunk 1 above)
Comment (Rxann) [reply src/hooks/protections/receive_net_message.cpp:262]: Per usual, I run the formatter

**Comment by Rxann** [comment]
Updated, depending on https://github.com/YimMenu/Translations/pull/134

File: src/hooks/protections/receive_net_message.cpp (hunk 1 above)
Comment (gir489returns) [reply src/hooks/protections/receive_net_message.cpp:262]: Have you considered not doing that? You know, like everyone else?

Comment (Rxann) [reply src/hooks/protections/receive_net_message.cpp:262]: No, I run the formatter via VS code plugin and it formats the whole file if needed. If it were up to date/formatted in the first place there would be no problems. Also, I did not personally make the change, in fact the formatter did and it follows the instructions that are predefined, so consider editing that if you have a big problem with it.

Comment (lonelybud) [reply src/hooks/protections/receive_net_message.cpp:262]: i think the best practice should be only to format piece of code you work on and not whole file given the existing file which was created unformatted. New files should always be formatted from top to bottom.

**Comment by Rxann** [comment]
@Yimura is this whitespace change permittable?

**Comment by Yimura** [comment]
> @Yimura is this whitespace change permittable?

Yes it is, and as it stands there is no way to not format the whole file. Whenever someone creates a feature they should run the clang-formatter. As to make sure that what they wrote/added follows the formatting style used by the rest of the project.

If somewhere else there's a change because the old code didn't follow the styling / formatting rules then so be it. It should've been formatted to begin with.

**Comment by Rxann** [comment]
> > @Yimura is this whitespace change permittable?
> 
> 
> 
> Yes it is, and as it stands there is no way to not format the whole file. Whenever someone creates a feature they should run the clang-formatter. As to make sure that what they wrote/added follows the formatting style used by the rest of the project.
> 
> 
> 
> If somewhere else there's a change because the old code didn't follow the styling / formatting rules then so be it. It should've been formatted to begin with.

Okay thank you, and I will continue to run the formatted in the future.

**Comment by gir489returns** [comment]
> If somewhere else there's a change because the old code didn't follow the styling / formatting rules then so be it. It should've been formatted to begin with.

I intentionally made it this way with #3139.

Mine:
image

Idiot who can't figure out how to tell Visual Studio to only format the code he works on's:
image

I must detest this idiot's constant weilding of the formatter like he thinks he's doing a god job pumping his line change numbers up because he's formatting the fucking project. Literally ever single PR he's made has done this. If the purpose of the formatter is to make the code look nice, then it fails horribly as you've mentioned before, and there are edge cases where we just manually format it ourselves. If the purpose of the formatter is to make unified code, then just format the entire project, and reject anyone who doesn't use it. But we don't, because neither of those scenarios are realistic or obtainable.

File: src/hooks/protections/receive_net_message.cpp (hunk 1 above)
Comment (Rxann) [reply src/hooks/protections/receive_net_message.cpp:262]: > > i think the best practice should be only to format piece of code you work on and not whole file given the existing file which was created unformatted. New files should always be formatted from top to bottom.
> 
> 
> 
> This is the way literally everyone else including @Yimura does it. 

Yimura said this is permittable, so for the final time I am going to mark it as resolved because it is.

Comment (lonelybud) [reply src/hooks/protections/receive_net_message.cpp:262]: there are two major problems with formatting from my personal experience and god knows if forget something more -
1. you add commit changes for something you only formatted and made no actual contribution to it. When time-travelling back in history to see who added the actual code it becomes mess sometimes?
2. there are sometimes complicated formatted changes which can cause issues related to merge when multiple people work on a given branch i don't remember perfectly there was some issue related to this.

**Comment by Rxann** [comment]
@Yimura is this mergeable?

**Comment by Rxann** [comment]
> I intentionally made it this way with #3139.
> 
> 
> 
> Mine:
> 
> image
> 
> 
> 
> Idiot who can't figure out how to tell Visual Studio to only format the code he works on's:
> 
> image
> 
> 
> 
> I must detest this idiot's constant weilding of the formatter like he thinks he's doing a good job pumping his line change numbers up because he's formatting the fucking project. Literally every single PR he's made has done this. If the purpose of the formatter is to make the code look nice, then it fails horribly as you've mentioned before, and there are edge cases where we just manually format it ourselves. If the purpose of the formatter is to make unified code, then just format the entire project, and reject anyone who doesn't use it. But we don't, because neither of those scenarios are realistic or obtainable.

It sounds to me like you didn't even read the first part of Yimura's comment. Also, I will never be concerned about my line numbers as they mean absolutely nothing to me. I run the formatter because I was instructed to do so when I started contributing, and I will continue to do so.

**Review by Yimura — APPROVED** [review]
