### PR TITLE
Bypass integrity checks

### LINKED ISSUE #2215: [Bug]: Update to Game Version: 3028
### Describe the bug

Rockstar Dropped another update

### Steps To Reproduce

Updating Game 😅

### Expected Behavior

...

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/12791375/cout.log)

### Store

Rockstar

### Additional context

The menu loads fine, prolly the Globals needs to be updated for some stuff to work without triggering anti-cheats

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by maybegreat48**
Might be a good idea to wait before merging this

Fixes #2215

### CODE REVIEW

File: src/hooks/misc/remove_player_from_sender_list.cpp [hunk 1]
```diff
@@ -0,0 +1,11 @@
+#include "hooking.hpp"
+#include "pointers.hpp"
+
+namespace big
+{
+	bool hooks::remove_player_from_sender_list(void* list, uint64_t rockstar_id)
+	{
+		g_pointers->m_gta.m_remove_player_from_sender_list(list, &rockstar_id);
```
Comment (gir489returns) [inline src/hooks/misc/remove_player_from_sender_list.cpp:8]: Incorrectly typed parameter here. rockstar_id should be a uint64_t * since we type m_rockstar_id coming from the player info class as uint64_t, but it is clearly a pointer passed to it, for an unbeknownst reason.

File: src/call_hook.cpp [hunk 2]
```diff
@@ -0,0 +1,62 @@
+#include "common.hpp"
+#include "call_hook.hpp"
+#include "memory/handle.hpp"
+
+namespace
+{
+	big::call_hook_memory g_call_hook_memory;
```
Comment (gir489returns) [inline src/call_hook.cpp:7]: Request the compiler to inline this and remove it from the namespace, this reeks of C. Maybe move it to the header or something.

File: src/call_hook.cpp [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+		VirtualFree(m_memory, 0, MEM_RELEASE);
+	}
+
+	void* call_hook_memory::allocate_jump_sequence(void* func)
+	{
+		m_offset = m_offset + ((16 - (m_offset % 16)) % 16); // align
+
+		*(int16_t*)&m_memory[m_offset] = 0xB848;
+		*(uint64_t*)&m_memory[m_offset+2] = (uint64_t)func;
+		*(int16_t*)&m_memory[m_offset+10] = 0xE0FF;
```
Comment (gir489returns) [inline src/call_hook.cpp:31]: Can't this be made into a class? You're declaring the char* member of m_memory, when you could instead declare the members and have the compiler figure it out. I don't see why all this array shifting math nonsense needs to occur.

**Review by gir489returns — CHANGES_REQUESTED** [review]

File: src/call_hook.cpp (hunk 2 above)
Comment (gir489returns) [reply src/call_hook.cpp:7]: Wait, is this even globally referred to? I don't see anything else using it besides this class file. g_ refers to a global identifier that can be accessed by the entire program. The only function that refers to it is the call_hook constructor.

Comment (maybegreat48) [reply src/call_hook.cpp:6]: > Wait, is this even globally referred to? I don't see anything else using it besides this class file. g_ refers to a global identifier that can be accessed by the entire program. The only function that refers to it is the call_hook constructor.

Yeah, that's why I placed it in the CPP file and not in the header

**Review by gir489returns — APPROVED** [review]
New code looks good to me.

**Comment by yubie-re** [comment]
I think going down this path to deal with integ checks is not going to work out very well in the long run. If I'm reading your code correctly (in the future it might be best to leave a few comments around, esp when you're constructing some machine code) it simply replaces a call or jmp to the function you're trying to hook. What happens if the jmp/call you're replacing is *also* integged? Rockstar has done this in the past with certain sync hooks (to attempt to prevent RID spoofing), and I'm sure they'd do it again. There is a public bypass to defeat most integs somewhere on UC from EinTim; if I understand it correctly (I only skimmed over it), it replaces the function bytes it compares with the backup bytes, so when comparing there is no differences. Might be a better route to go, or even just attacking where a certain integ is coming from might be doable. However, this is a bandaid fix which won't last very long in my opinion.

**Comment by gir489returns** [comment]
@yubie-re Your argument makes no sense. You're trying to say Rockstar could fix this and we should use something else, but they could also fix that just as easily? That's not an argument, dude.

**Comment by yubie-re** [comment]
Harder for R* to change arxan than to add another integ.

**Comment by maybegreat48** [comment]
> Harder for R* to change arxan than to add another integ.

I don't want to give them ideas, but there's a very easy way to break the integ bypass. It has actually been done before too

**Comment by xiaoxiao921** [comment]
I find it much more logical to keep this PR private for the moment ( a bit too late for that ), this way r* just patch the public bypass that everyone use and then once they release their security patch we can right after use whatever you cooked privately without telling anyone, this way we are always one patch ahead of r*, and we all know how slow they are to actually put those patches out.

**Review by xiaoxiao921 — APPROVED** [review]
