### PR TITLE
Desync protection improvements

### LINKED ISSUE #3032: [Bug]: Received Clone Crash
### Describe the bug

Going to be more proactive about reporting crashes since something funky is going on.

Was in a public session for a while until I got hit with this. Game didn't crash, though, and I was able to rejoin the session.

### Steps To Reproduce

Unknown exactly what triggered it, but stack trace suggests cloning.

### Expected Behavior

Clone handling without crashing.

### Logs

Last output before stack trace:
```
[20:24:43.3390424][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":2000,"char":{"slot":0,"cash":2321620,"bank":513712793,"evc":516034413,"pvc":0,"pxr":0.00000,"nonce":638502782779030008},"c":[-137.23596,-585.42725,211.76277],"pt":3197318994,"vct":0,"vcp":0,"mid":0,"action":"BADSPORT","cat":"GOOD_SPORT","ctx":{}
[20:24:43.3390706][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":2000,"char":{"slot":0,"cash":2321620,"bank":513712793,"evc":516034413,"pvc":0,"pxr":0.00000,"nonce":638502782779030008},"c":[-137.23596,-585.42725,211.76277],"pt":3197318994,"vct":0,"vcp":0,"mid":0,"action":"BADSPORT","cat":"GOOD_SPORT","ctx":{}
[20:28:06.9800156][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: DIG; DATA: "gamer":"SC 133384834","action":"RTB","id":-8233441639964578291
[20:28:56.1993699][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
```

Trace

```
[0]     D:\Documents\GitHub\YimMenu\src\hooks\protections\received_clone_remove.cpp L: 8 big::hooks::received_clone_remove
[1]     GTA5.exe+0x16DC4F2 0x7FF643B3C4F2
[2]     GTA5.exe+0x16D3D44 0x7FF643B33D44
[3]     GTA5.exe+0x16D9414 0x7FF643B39414
[4]     GTA5.exe+0x1461FD5 0x7FF6438C1FD5
[5]     GTA5.exe+0x16D9541 0x7FF643B39541
[6]     GTA5.exe+0x1400D52 0x7FF643860D52
[7]     D:\Documents\GitHub\YimMenu\src\hooks\protections\receive_net_message.cpp L: 264 big::hooks::receive_net_message[8]     GTA5.exe+0x1400E05 0x7FF643860E05
```

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by maybegreat48**
* Make our protection harder to detect
* Detect desync kick protections that other menus use
* Fix some crashes

Might fix #3032

### CODE REVIEW

**Review by Yimura — DISMISSED** [review]
I'm fine with the code however I'd like to see some more in-depth testing of the infractions so there aren't any false positives.

**Review by gir489returns — DISMISSED** [review]

File: src/hooks/misc/serialize_join_request_message.cpp [hunk 1]
```diff
@@ -12,7 +13,7 @@ namespace big
 		if (info->unk_0xC0 == 0)
 			info->unk_0xC0 = 1; // TODO: do we need this anymore?
 
-		if (g.protections.desync_kick)
+		if (g.protections.desync_kick && (!*g_pointers->m_gta.m_is_session_started || !g_player_service->get_self()->is_host()))
```
Comment (lonelybud) [inline src/hooks/misc/serialize_join_request_message.cpp]: serialize_join_request_message & serialize_join_request_message2 hooks are both called once before joining session like-

```
[15:29:14.9634776][DEBUG/player_service.cpp](65:4) Created self player
[15:29:56.9487358][INFO/network_player_mgr.cpp](41:3) CNetworkPlayerMgr init
[15:29:57.0869530][INFO/serialize_join_request_message.cpp](25:3) serialize_join_request_message 2
[15:29:57.0899135][DEBUG/player_service.cpp](65:4) Created self player
[15:29:58.2004453][INFO/serialize_join_request_message.cpp](13:3) serialize_join_request_message
[15:30:00.0933630][INFO/assign_physical_index.cpp](43:4) You joined the session.
[15:30:00.1181372][INFO/assign_physical_index.cpp](93:7) Player joined: 'Molot-OvO'(host), slot #0, RID: 219592377, tk: 9262475521841728060
[15:30:00.7425081][INFO/assign_physical_index.cpp](93:7) Player joined: 'SwanLiHong', slot #22, RID: 188695962, tk: 17452440618492821689
[15:30:00.8407558][INFO/assign_physical_index.cpp](93:7) Player joined: 'TuTuGTAV6', slot #23, RID: 234423164, tk: 16175699075157837359
[15:30:00.9668756][INFO/assign_physical_index.cpp](93:7) Player joined: 'LSPZIO2333', slot #8, RID: 110405142, tk: 15216796575502584149
```

if host broadhost our details then our `nat_type=0` will be always broadcasted to others. How these checks help bcz the hooks are only called once and most probably these checks either will not set nat to 0 or will set nat to 0. So there will be 50% probability that yim can be detected with desync protection when checked in `assign_physical_index` hook

File: src/hooks/protections/received_clone_create.cpp [hunk 2]
```diff
@@ -12,6 +13,13 @@ namespace big
 			return;
 		}
 
+		if (*g_pointers->m_gta.m_clone_create_pool && (*g_pointers->m_gta.m_clone_create_pool)->m_size < 2)
+		{
+			// We don't have enough memory to handle this
+			g_notification_service.push_warning("Protections", "Low net object pool size");
```
Comment (lonelybud) [inline src/hooks/protections/received_clone_create.cpp:19]: can we have similar check in `received_clone_sync` just curious?

Comment (Yimura) [reply src/hooks/protections/received_clone_create.cpp:19]: Not necessary as blocking it in create solves the problem already.

File: src/hooks/misc/serialize_join_request_message.cpp (hunk 1 above)
Comment (lonelybud) [reply src/hooks/misc/serialize_join_request_message.cpp]: dont have idea for sure but just thinking out of brain. May close this if not concerning,

Comment (maybegreat48) [reply src/hooks/misc/serialize_join_request_message.cpp]: > if host broadhost our details then our nat_type=0 will be always broadcasted to others

Yeah. There's no way we can stop this

> How these checks help bcz the hooks are only called once and most probably these checks either will not set nat to 0 or will set nat to 0

I don't understand this part

Comment (lonelybud) [reply src/hooks/misc/serialize_join_request_message.cpp]: i mean the checks in `assign_physical_index` will always add infraction for yim users that they have desync protection

> Make our protection harder to detect

☝️ this will not be the case then

Comment (Mr-X-GTA) [reply src/hooks/misc/serialize_join_request_message.cpp]: > I don't understand this part

These functions are only called when we join a session, so these checks are redundant here

Comment (lonelybud) [reply src/hooks/misc/serialize_join_request_message.cpp]: serialize_join_request_message and serialize_join_request_message2 hooks are called before we join session and then other players who see us joining their assign_physical_index hooks will trigger that we have desync protection thats what i meant actually in short

Comment (maybegreat48) [reply src/hooks/misc/serialize_join_request_message.cpp]: > These functions are only called when we join a session, so these checks are redundant here

They are also called when you're the host and are sending player data to other clients. Some menus even play with the NAT types of other clients for absolutely no reason 

> i mean the checks in assign_physical_index will always add infraction for yim users that they have desync protection

Other menus, including P2Cs, use this protection. It's not just YimMenu

Comment (Mr-X-GTA) [reply src/hooks/misc/serialize_join_request_message.cpp]: > They are also called when you're the host and are sending player data to other clients.

I chose these functions for hooking because they do not do that.

> Some menus even play with the NAT types of other clients for absolutely no reason

Stand does this because I used to detect them based on the NAT type, they want to make it harder to detect. And it disables the desync protection of other players

Comment (lonelybud) [reply src/hooks/misc/serialize_join_request_message.cpp]: > They are also called when you're the host and are sending player data to other clients.

so we will always have our nat type spoofed to 0 when not host.

> Make our protection harder to detect

this will only work well when we host the session from starting?

**Review by Yimura — DISMISSED** [review]
Still fine code-wise, I'd like to have people report here if they're getting false positives from running the binary in this PR.

**Comment by snowleopardd** [comment]
i'm currently testing the binary, no false positives, detects desync protections as intended

**Comment by Rxann** [comment]
Binary has been tested, no false positives experienced in my testing.

**Review by gir489returns — DISMISSED** [review]

**Comment by lonelybud** [comment]
its funny that very few users have desync protection on when i joined sessions. May be it is bcz of the fact desync protection is set to off by default.

**Review by gir489returns — APPROVED** [review]
