### PR TITLE
Protection improvements

### LINKED ISSUE #2624: [Bug]: False sound spam crash during the data breachs heist
### Describe the bug

when going into the control center and manning the guns, when the players shoot it detects them as sound spamming

### Steps To Reproduce

start the data breaches heist
proceed to the control rooms and wait for everyone to get in the gun
have the players shoot 

### Expected Behavior

i expect it to be fine and not detect the players as sound spamming

### Logs and/or screenshots

_No response_

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

i was lagging pretty bad so im not sure if that could have something to do with it, but i tested it twice and it happened both times

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #2971: [Bug]: Crash as soon i open the "Hotkeys" Tab
### Describe the bug

Hey, as the title already stated my game crashes as soon as i open the hotkeys tab under settings. 

### Steps To Reproduce

1. Open the menu 2. Click the settings tab 3. Press "Hotkeys" 4. Crash!

### Expected Behavior

That the window with all hotkeys opens and should be configurable.

### Logs and/or screenshots

[13:30:03.4548307][INFO/main.cpp:156] Settings Loaded and logger initialized.
[13:30:03.4550427][INFO/main.cpp:158] Yim's Menu Initializing
[13:30:03.4550552][INFO/main.cpp:159] Git Info
	Branch:	master
	Hash:	ca1e7e6b419d68bfa6673da0e38b9e52721aa4aa
	Date:	Mon Apr 22 19:48:22 2024
[13:30:03.4552015][INFO/main.cpp:171] Windows 10 Pro Version 22H2 (OS Build 19045.4291)
[13:30:03.4609878][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[13:30:03.4612602][INFO/main.cpp:179] Thread pool initialized.
[13:30:03.4713364][INFO/batch.hpp:106] Found 'ISA' GTA5.exe+0xEF2F
[13:30:03.4714796][INFO/batch.hpp:106] Found 'SR' GTA5.exe+0x16C26B
[13:30:03.4735420][INFO/batch.hpp:106] Found 'GS' GTA5.exe+0x2C631C
[13:30:03.4738167][INFO/batch.hpp:106] Found 'GL' GTA5.exe+0x6D8A18
[13:30:03.4741850][INFO/batch.hpp:106] Found 'PF' GTA5.exe+0x7348A8
[13:30:03.4755606][INFO/batch.hpp:106] Found 'SGL' GTA5.exe+0x6D8A0C
[13:30:03.4855733][INFO/batch.hpp:106] Found 'S' GTA5.exe+0x1392219
[13:30:03.4861882][INFO/batch.hpp:106] Found 'FV' GTA5.exe+0x162162C
[13:30:03.4877936][INFO/batch.hpp:106] Found 'NRF' GTA5.exe+0x11DDBF
[13:30:03.4898213][INFO/batch.hpp:106] Found 'ST' GTA5.exe+0x16245FB
[13:30:03.4906558][INFO/batch.hpp:106] Found 'NPM' GTA5.exe+0x10B52A8
[13:30:03.4923364][INFO/batch.hpp:106] Found 'SP' GTA5.exe+0xA4B261
[13:30:03.4974457][INFO/batch.hpp:106] Found 'SG' GTA5.exe+0x1623F4C
[13:30:03.4988633][INFO/batch.hpp:106] Found 'CGSHM' GTA5.exe+0x1628F95
[13:30:03.4993044][INFO/batch.hpp:106] Found 'NH' GTA5.exe+0x16246A5
[13:30:03.4995372][INFO/batch.hpp:106] Found 'TK' GTA5.exe+0xA4F2E4
[13:30:03.4997050][INFO/batch.hpp:106] Found 'GTS' GTA5.exe+0x1624114
[13:30:03.5006340][INFO/batch.hpp:106] Found 'TSE' GTA5.exe+0xD97000
[13:30:03.5015534][INFO/batch.hpp:106] Found 'RBB' GTA5.exe+0x66FE44
[13:30:03.5032054][INFO/batch.hpp:106] Found 'OQ' GTA5.exe+0x57056A
[13:30:03.5051040][INFO/batch.hpp:106] Found 'WBD' GTA5.exe+0x10E408C
[13:30:03.5051913][INFO/batch.hpp:106] Found 'RBS' GTA5.exe+0x13307F4
[13:30:03.5058728][INFO/batch.hpp:106] Found 'WBQ' GTA5.exe+0x133828C
[13:30:03.5092931][INFO/batch.hpp:106] Found 'RBWD' GTA5.exe+0x1624DE1
[13:30:03.5158225][INFO/batch.hpp:106] Found 'WPGSDN' GTA5.exe+0x1188304
[13:30:03.5204155][INFO/batch.hpp:106] Found 'RBA' GTA5.exe+0x13304D0
[13:30:03.5222236][INFO/batch.hpp:106] Found 'PTH' GTA5.exe+0x1628A51
[13:30:03.5232850][INFO/batch.hpp:106] Found 'RC' GTA5.exe+0x1468258
[13:30:03.5255844][INFO/batch.hpp:106] Found 'SEA' GTA5.exe+0x16DF9C9
[13:30:03.5286780][INFO/batch.hpp:106] Found 'WBI64' GTA5.exe+0x1138EF9
[13:30:03.5308446][INFO/batch.hpp:106] Found 'WBI32' GTA5.exe+0x1137DBB
[13:30:03.5312423][INFO/batch.hpp:106] Found 'WBB' GTA5.exe+0x11378BC
[13:30:03.5314351][INFO/batch.hpp:106] Found 'NPMI' GTA5.exe+0x11930BB
[13:30:03.5342066][INFO/batch.hpp:106] Found 'GSCFWC' GTA5.exe+0xA4A314
[13:30:03.5347843][INFO/batch.hpp:106] Found 'GSH' GTA5.exe+0x1629EF8
[13:30:03.5349462][INFO/batch.hpp:106] Found 'CNOM' GTA5.exe+0xB2CD84
[13:30:03.5379401][INFO/batch.hpp:106] Found 'GPR' GTA5.exe+0x1153AD4
[13:30:03.5427190][INFO/batch.hpp:106] Found 'WBA' GTA5.exe+0x16C60B2
[13:30:03.5451973][INFO/batch.hpp:106] Found 'RNM' GTA5.exe+0x1400CD1
[13:30:03.5454230][INFO/batch.hpp:106] Found 'GNED' GTA5.exe+0x1A35050
[13:30:03.5472297][INFO/batch.hpp:106] Found 'REH' GTA5.exe+0x16DBD44
[13:30:03.5477125][INFO/batch.hpp:106] Found 'API' GTA5.exe+0x16E20E8
[13:30:03.5478387][INFO/batch.hpp:106] Found 'MHT' GTA5.exe+0xB26A
[13:30:03.5517347][INFO/batch.hpp:106] Found 'WPGDN' GTA5.exe+0x1188E4C
[13:30:03.5520532][INFO/batch.hpp:106] Found 'NPMS' GTA5.exe+0x11C7D76
[13:30:03.5548978][INFO/batch.hpp:106] Found 'CAD' GTA5.exe+0x119E1F6
[13:30:03.5549631][INFO/batch.hpp:106] Found 'RCS/GSTFT/GNOFP/GNO/GSTI' GTA5.exe+0x119E8F4
[13:30:03.5556229][INFO/batch.hpp:106] Found 'RCC' GTA5.exe+0x119D958
[13:30:03.5629097][INFO/batch.hpp:106] Found 'FR' GTA5.exe+0xCEDD14
[13:30:03.5649475][INFO/batch.hpp:106] Found 'FPFC' GTA5.exe+0x132059E
[13:30:03.5658898][INFO/batch.hpp:106] Found 'GLT' GTA5.exe+0xDB96F7
[13:30:03.5666290][INFO/batch.hpp:106] Found 'GGCC' GTA5.exe+0xA7F60E
[13:30:03.5673143][INFO/batch.hpp:106] Found 'GMI' GTA5.exe+0x167694A
[13:30:03.5676904][INFO/batch.hpp:106] Found 'SCP' GTA5.exe+0x2F4E5C
[13:30:03.5695115][INFO/batch.hpp:106] Found 'FPFD' GTA5.exe+0x1320808
[13:30:03.5698299][INFO/batch.hpp:106] Found 'MCF' GTA5.exe+0x169F0B6
[13:30:03.5703628][INFO/batch.hpp:106] Found 'IMCD' GTA5.exe+0x53F1DD
[13:30:03.5755937][INFO/batch.hpp:106] Found 'SGSBGH' GTA5.exe+0x444120
[13:30:03.5816008][INFO/batch.hpp:106] Found 'N' GTA5.exe+0x107E599
[13:30:03.5846273][INFO/batch.hpp:106] Found 'NC' GTA5.exe+0x4417BD
[13:30:03.5952330][INFO/batch.hpp:106] Found 'JSBI' GTA5.exe+0x111029B
[13:30:03.5961349][INFO/batch.hpp:106] Found 'RBIST' GTA5.exe+0x119DAD8
[13:30:03.5962188][INFO/batch.hpp:106] Found 'FDGD' GTA5.exe+0x1323BFF
[13:30:03.6013249][INFO/batch.hpp:106] Found 'GGOS' GTA5.exe+0x1468170
[13:30:03.6031498][INFO/batch.hpp:106] Found 'VM' GTA5.exe+0x1623F56
[13:30:03.6038659][INFO/batch.hpp:106] Found 'SGSBGH' GTA5.exe+0x147676A
[13:30:03.6062082][INFO/batch.hpp:106] Found 'AFBGH' GTA5.exe+0x10751C8
[13:30:03.6103083][INFO/batch.hpp:106] Found 'IPBGH' GTA5.exe+0x4417D8
[13:30:03.6104041][INFO/batch.hpp:106] Found 'SPBGH' GTA5.exe+0x442C62
[13:30:03.6124182][INFO/batch.hpp:106] Found 'WJRD' GTA5.exe+0x111664F
[13:30:03.6147111][INFO/batch.hpp:106] Found 'C' GTA5.exe+0xCEFD88
[13:30:03.6151620][INFO/batch.hpp:106] Found 'HT' GTA5.exe+0x1468F25
[13:30:03.6188258][INFO/batch.hpp:106] Found 'PMFR' GTA5.exe+0x1481170
[13:30:03.6217377][INFO/batch.hpp:106] Found 'PGI' GTA5.exe+0x1486184
[13:30:03.6227008][INFO/batch.hpp:106] Found 'SGS' GTA5.exe+0x112AA10
[13:30:03.6231371][INFO/batch.hpp:106] Found 'QP' GTA5.exe+0x1425512
[13:30:03.6231925][INFO/batch.hpp:106] Found 'HJR' GTA5.exe+0x11155B8
[13:30:03.6234447][INFO/batch.hpp:106] Found 'PIGI' GTA5.exe+0x10C1583
[13:30:03.6235445][INFO/batch.hpp:106] Found 'SPDM' GTA5.exe+0x11B3DBC
[13:30:03.6241102][INFO/batch.hpp:106] Found 'SJRM' GTA5.exe+0x129CD7A
[13:30:03.6267961][INFO/batch.hpp:106] Found 'RENC' GTA5.exe+0x142D4B6
[13:30:03.6279403][INFO/batch.hpp:106] Found 'SND' GTA5.exe+0xF66977
[13:30:03.6280573][INFO/batch.hpp:106] Found 'GU' GTA5.exe+0x1496282
[13:30:03.6288873][INFO/batch.hpp:106] Found 'GCP' GTA5.exe+0x1407CE8
[13:30:03.6290170][INFO/batch.hpp:106] Found 'SSMA' GTA5.exe+0x1479004
[13:30:03.6305159][INFO/batch.hpp:106] Found 'CD' GTA5.exe+0x18FEB7
[13:30:03.6314215][INFO/batch.hpp:106] Found 'STOPVT' GTA5.exe+0x6A0C00
[13:30:03.6318498][INFO/batch.hpp:106] Found 'IDC' GTA5.exe+0x67D0C0
[13:30:03.6330163][INFO/batch.hpp:106] Found 'SRGC' GTA5.exe+0x121056B
[13:30:03.6330757][INFO/batch.hpp:106] Found 'HRGC' GTA5.exe+0x12091D4
[13:30:03.6341998][INFO/batch.hpp:106] Found 'SPT' GTA5.exe+0xB8E1D4
[13:30:03.6348536][INFO/batch.hpp:106] Found 'RR' GTA5.exe+0xC1F99B
[13:30:03.6351929][INFO/batch.hpp:106] Found 'RC' GTA5.exe+0xF97C74
[13:30:03.6365089][INFO/batch.hpp:106] Found 'LCF' GTA5.exe+0x5DD5F4
[13:30:03.6382721][INFO/batch.hpp:106] Found 'DPI' GTA5.exe+0x1405FEC
[13:30:03.6398731][INFO/batch.hpp:106] Found 'SJD' GTA5.exe+0xA93880
[13:30:03.6399298][INFO/batch.hpp:106] Found 'TAC' GTA5.exe+0xAFB0D8
[13:30:03.6399882][INFO/batch.hpp:106] Found 'SAACF' GTA5.exe+0xA93CDC
[13:30:03.6413501][INFO/batch.hpp:106] Found 'MFO' GTA5.exe+0xA7835F
[13:30:03.6444062][INFO/batch.hpp:106] Found 'DSI' GTA5.exe+0x1478198
[13:30:03.6455048][INFO/batch.hpp:106] Found 'BNA' GTA5.exe+0x16EC13C
[13:30:03.6457184][INFO/batch.hpp:106] Found 'ESI' GTA5.exe+0x1188F6E
[13:30:03.6457991][INFO/batch.hpp:106] Found 'QD' GTA5.exe+0x130EC10
[13:30:03.6470682][INFO/batch.hpp:106] Found 'NT' GTA5.exe+0xCDFDAA
[13:30:03.6476310][INFO/batch.hpp:106] Found 'PMFS' GTA5.exe+0x1464070
[13:30:03.6513706][INFO/batch.hpp:106] Found 'CTP' GTA5.exe+0x1415054
[13:30:03.6514311][INFO/batch.hpp:106] Found 'SP' GTA5.exe+0x1422ED0
[13:30:03.6545810][INFO/batch.hpp:106] Found 'SCI' GTA5.exe+0x1452773
[13:30:03.6546932][INFO/batch.hpp:106] Found 'ICF' GTA5.exe+0xAB308F
[13:30:03.6562421][INFO/batch.hpp:106] Found 'TPO' GTA5.exe+0xBCA04E
[13:30:03.6566296][INFO/batch.hpp:106] Found 'RPI' GTA5.exe+0x6B7C78
[13:30:03.6577159][INFO/batch.hpp:106] Found 'FPC2' GTA5.exe+0x14AA5B3
[13:30:03.6581699][INFO/batch.hpp:106] Found 'GEAT' GTA5.exe+0xA92734
[13:30:03.6589006][INFO/batch.hpp:106] Found 'RAU' GTA5.exe+0x16DD004
[13:30:03.6606053][INFO/batch.hpp:106] Found 'SPCS' GTA5.exe+0x113EEF8
[13:30:03.6606801][INFO/batch.hpp:106] Found 'WPCDN' GTA5.exe+0x117ABAC
[13:30:03.6607186][INFO/batch.hpp:106] Found 'CPTN' GTA5.exe+0xD6A2F4
[13:30:03.6614278][INFO/batch.hpp:106] Found 'SS' GTA5.exe+0x107A8D0
[13:30:03.6645749][INFO/batch.hpp:106] Found 'EAD' GTA5.exe+0x12095EC
[13:30:03.6646344][INFO/batch.hpp:106] Found 'WPADN' GTA5.exe+0x11879DC
[13:30:03.6647112][INFO/batch.hpp:106] Found 'HSR' GTA5.exe+0x1429794
[13:30:03.6647417][INFO/batch.hpp:106] Found 'WVPMDN' GTA5.exe+0x118E55C
[13:30:03.6654027][INFO/batch.hpp:106] Found 'PRP' GTA5.exe+0x118823
[13:30:03.6660125][INFO/batch.hpp:106] Found 'GVOV' GTA5.exe+0x2E7944
[13:30:03.6677163][INFO/batch.hpp:106] Found 'VEP' GTA5.exe+0xD6D145
[13:30:03.6692586][INFO/batch.hpp:106] Found 'MO' GTA5.exe+0x11537D0
[13:30:03.6696832][INFO/batch.hpp:106] Found 'PEP' GTA5.exe+0x9BB84F
[13:30:03.6702266][INFO/batch.hpp:106] Found 'TJC' GTA5.exe+0xB057C8
[13:30:03.6705297][INFO/batch.hpp:106] Found 'HCM' GTA5.exe+0x2D5C40
[13:30:03.6706857][INFO/batch.hpp:106] Found 'AWIV' GTA5.exe+0xF16C4F
[13:30:03.6708242][INFO/batch.hpp:106] Found 'SNT' GTA5.exe+0x142DC69
[13:30:03.6709124][INFO/batch.hpp:106] Found 'WPCDN' GTA5.exe+0x1187EA0
[13:30:03.6722310][INFO/batch.hpp:106] Found 'L&UL' GTA5.exe+0x1A3CD0
[13:30:03.6731340][INFO/batch.hpp:106] Found 'DSCC' GTA5.exe+0x120A715
[13:30:03.6752684][INFO/batch.hpp:106] Found 'AMR&CMTFM' GTA5.exe+0x13F82EC
[13:30:03.6767555][INFO/batch.hpp:106] Found 'RP' GTA5.exe+0x5167E0
[13:30:03.6779005][INFO/batch.hpp:106] Found 'GHAHBI' GTA5.exe+0x1629FCC
[13:30:03.6781478][INFO/batch.hpp:106] Found 'FPCR' GTA5.exe+0x115A737
[13:30:03.6786272][INFO/batch.hpp:106] Found 'TFC' GTA5.exe+0xC257CD
[13:30:03.6795640][INFO/batch.hpp:106] Found 'RE' GTA5.exe+0x512190
[13:30:03.6796789][INFO/batch.hpp:106] Found 'RR' GTA5.exe+0x1E648
[13:30:03.6803143][INFO/batch.hpp:106] Found 'RE' GTA5.exe+0x508E4C
[13:30:03.6828607][INFO/batch.hpp:106] Found 'RBS' GTA5.exe+0x1330AA0
[13:30:03.6831821][INFO/batch.hpp:106] Found 'RMFQ&RMFUR' GTA5.exe+0x141FD9A
[13:30:03.6835023][INFO/batch.hpp:106] Found 'RAI' GTA5.exe+0x128C686
[13:30:03.6846334][INFO/batch.hpp:106] Found 'DHM' GTA5.exe+0x801843
[13:30:03.6865271][INFO/batch.hpp:106] Found 'RBS' GTA5.exe+0x11C4614
[13:30:03.6869615][INFO/batch.hpp:106] Found 'SNPPD' GTA5.exe+0x16E0B52
[13:30:03.6876885][INFO/batch.hpp:106] Found 'ASA' GTA5.exe+0x11529D8
[13:30:03.6891141][INFO/batch.hpp:106] Found 'IPP' GTA5.exe+0x925ADA
[13:30:03.6909305][INFO/batch.hpp:106] Found 'DO' GTA5.exe+0x753AD8
[13:30:03.6910148][INFO/batch.hpp:106] Found 'TCA' GTA5.exe+0xF67A72
[13:30:03.6927377][INFO/batch.hpp:106] Found 'PD' GTA5.exe+0x14525A1
[13:30:03.6928963][INFO/batch.hpp:106] Found 'NEM&CEQ&NEP&GNPI&QNE' GTA5.exe+0x1154B57
[13:30:03.6929634][INFO/batch.hpp:106] Found 'DV' GTA5.exe+0xD98BBC
[13:30:03.6931964][INFO/batch.hpp:106] Found 'CDBE' GTA5.exe+0x113D07C
[13:30:03.6937361][INFO/batch.hpp:106] Found 'DP' GTA5.exe+0xD00D78
[13:30:03.6943126][INFO/batch.hpp:106] Found 'CW' GTA5.exe+0x1666BB
[13:30:03.6948958][INFO/batch.hpp:106] Found 'NHM' GTA5.exe+0x10C777D
[13:30:03.6955456][INFO/batch.hpp:106] Found 'MWL' GTA5.exe+0x5DF38F
[13:30:03.6967590][INFO/batch.hpp:106] Found 'IMSV' GTA5.exe+0x110E3F0
[13:30:03.7010297][INFO/batch.hpp:106] Found 'FRC' GTA5.exe+0x140852F
[13:30:03.7010959][INFO/batch.hpp:106] Found 'EP' GTA5.exe+0xA75343
[13:30:03.7016487][INFO/batch.hpp:106] Found 'BE' GTA5.exe+0xA75243
[13:30:03.7021325][INFO/batch.hpp:106] Found 'BP' GTA5.exe+0x16EC343
[13:30:03.7050299][INFO/batch.hpp:106] Found 'SWL' GTA5.exe+0x1152A50
[13:30:03.7059987][INFO/batch.hpp:106] Found 'SOD' GTA5.exe+0x12B40D5
[13:30:03.7067141][INFO/batch.hpp:106] Found 'WMSB' GTA5.exe+0xD01E9F
[13:30:03.7067447][INFO/batch.hpp:106] Found 'CTSHP' GTA5.exe+0xA48F2E
[13:30:03.7067819][INFO/batch.hpp:106] Found 'DT' GTA5.exe+0x13E4
[13:30:03.7081391][INFO/batch.hpp:106] Found 'DC' GTA5.exe+0x14BA31B
[13:30:03.7099705][INFO/batch.hpp:106] Found 'BLPLST' GTA5.exe+0x2C71D0
[13:30:03.7138444][INFO/batch.hpp:106] Found 'FEE' GTA5.exe+0x16CA371
[13:30:03.7168346][INFO/batch.hpp:106] Found 'GTCE0MB' GTA5.exe+0x132A724
[13:30:03.7192959][INFO/batch.hpp:106] Found 'TCYCL' GTA5.exe+0xE58520
[13:30:03.7193449][INFO/batch.hpp:106] Found 'VEHMMGR' GTA5.exe+0xFD82D5
[13:30:03.7205533][INFO/batch.hpp:106] Found 'ASAP' GTA5.exe+0x114E548
[13:30:03.7208892][INFO/batch.hpp:106] Found 'FPU&FPCA&FPOA&FPM' GTA5.exe+0x805ABA
[13:30:03.7211181][INFO/batch.hpp:106] Found 'GS' GTA5.exe+0x27666
[13:30:03.7212243][INFO/batch.hpp:106] Found 'NS' GTA5.exe+0x2AC2D
[13:30:03.7236141][INFO/batch.hpp:106] Found 'SVM1' GTA5.exe+0x1623447
[13:30:03.7270953][INFO/batch.hpp:106] Found 'GPS' GTA5.exe+0x83BA51
[13:30:03.7287156][INFO/batch.hpp:106] Found 'SVM5&6' GTA5.exe+0x1623555
[13:30:03.7291857][INFO/batch.hpp:106] Found 'SVM3&4' GTA5.exe+0x162340E
[13:30:03.7294662][INFO/batch.hpp:106] Found 'RCR' GTA5.exe+0x119E5BC
[13:30:03.7305680][INFO/batch.hpp:106] Found 'CT' GTA5.exe+0x130CD6C
[13:30:03.7312248][INFO/batch.hpp:106] Found 'SVM2' GTA5.exe+0x16235A2
[13:30:03.7313408][INFO/batch.hpp:106] Found 'E0MB' GTA5.exe+0x13257BA
[13:30:03.7328094][INFO/batch.hpp:106] Found 'FI' GTA5.exe+0x3F1558
[13:30:03.7336155][INFO/batch.hpp:106] Found 'SCM' GTA5.exe+0x10C74CD
[13:30:03.7494706][INFO/batch.hpp:106] Found 'CCV' GTA5.exe+0xF100FC
[13:30:03.7566452][INFO/batch.hpp:106] Found 'CWIM' GTA5.exe+0x103D47A
[13:30:03.7608666][INFO/batch.hpp:106] Found 'ISCOA' GTA5.exe+0x13C0C36
[13:30:03.7730500][INFO/batch.hpp:106] Found 'DCLMGR' GTA5.exe+0xE29900
[13:30:03.7732133][INFO/pointers.hpp:79] Pointers cache: saved 218 fields to the cache
[13:30:03.7741763][DEBUG/module.cpp:55] Waiting for socialclub.dll...
[13:30:03.7961158][INFO/batch.hpp:106] Found 'PD' GTA5.exe+0x14A81A
[13:30:03.7983095][INFO/batch.hpp:106] Found 'SGPA' GTA5.exe+0x1D7DFC
[13:30:03.7989093][INFO/batch.hpp:106] Found 'RAP' GTA5.exe+0x1EECD8
[13:30:03.7996498][INFO/batch.hpp:106] Found 'RAP2' GTA5.exe+0x1EED4A
[13:30:03.7997178][INFO/pointers.hpp:79] Pointers cache: saved 5 fields to the cache
[13:30:03.8018542][INFO/main.cpp:182] Pointers initialized.
[13:30:03.8019354][INFO/main.cpp:189] Disabled anticheat gameskeleton.
[13:30:03.8023345][INFO/main.cpp:192] Byte Patch Manager initialized.
[13:30:03.8043811][INFO/main.cpp:195] Renderer initialized.
[13:30:03.8069981][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF6FE4C0000 Size: 72949760
ntdll.dll Base Address: 0x7FFF065D0000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFF060B0000 Size: 513536
KERNELBASE.dll Base Address: 0x7FFF040A0000 Size: 1256448
apphelp.dll Base Address: 0x7FFEFCE50000 Size: 319488
AcLayers.DLL Base Address: 0x7FFE87EB0000 Size: 175104
msvcrt.dll Base Address: 0x7FFF05BF0000 Size: 477184
USER32.dll Base Address: 0x7FFF048E0000 Size: 586752
win32u.dll Base Address: 0x7FFF03D10000 Size: 42496
GDI32.dll Base Address: 0x7FFF064F0000 Size: 57856
gdi32full.dll Base Address: 0x7FFF04410000 Size: 673792
msvcp_win.dll Base Address: 0x7FFF04530000 Size: 344064
ucrtbase.dll Base Address: 0x7FFF03D40000 Size: 735744
SHELL32.dll Base Address: 0x7FFF052B0000 Size: 5920256
SHLWAPI.dll Base Address: 0x7FFF04600000 Size: 182784
ADVAPI32.dll Base Address: 0x7FFF04B70000 Size: 434176
sechost.dll Base Address: 0x7FFF04660000 Size: 422400
RPCRT4.dll Base Address: 0x7FFF05A20000 Size: 913408
bcrypt.dll Base Address: 0x7FFF045D0000 Size: 102912
sfc.dll Base Address: 0x21951D00000 Size: 0
WINSPOOL.DRV Base Address: 0x7FFEED540000 Size: 389632
combase.dll Base Address: 0x7FFF05C90000 Size: 2325504
shcore.dll Base Address: 0x7FFF04760000 Size: 476672
sfc_os.DLL Base Address: 0x7FFEE4FD0000 Size: 28672
SortWindows61.dll Base Address: 0x7FFEE13B0000 Size: 42496
IMM32.DLL Base Address: 0x7FFF06070000 Size: 125440
PSAPI.DLL Base Address: 0x7FFF06580000 Size: 2048
WS2_32.dll Base Address: 0x7FFF04DD0000 Size: 275456
CRYPT32.dll Base Address: 0x7FFF03F40000 Size: 1098752
VERSION.dll Base Address: 0x7FFEFDC10000 Size: 10752
WINTRUST.dll Base Address: 0x7FFF043A0000 Size: 294912
DSOUND.dll Base Address: 0x7FFE86F50000 Size: 380928
ole32.dll Base Address: 0x7FFF06170000 Size: 833024
OLEAUT32.dll Base Address: 0x7FFF06420000 Size: 608768
WININET.dll Base Address: 0x7FFEEBBE0000 Size: 2019840
WINMM.dll Base Address: 0x7FFEF8970000 Size: 81408
MF.dll Base Address: 0x7FFF000D0000 Size: 340992
MFPlat.DLL Base Address: 0x7FFEFF900000 Size: 1409024
cfgmgr32.dll Base Address: 0x7FFF03EF0000 Size: 219136
msdmo.dll Base Address: 0x7FFEE0DF0000 Size: 13312
MFReadWrite.dll Base Address: 0x7FFE89540000 Size: 918016
PROPSYS.dll Base Address: 0x7FFF01060000 Size: 631296
d3d9.dll Base Address: 0x7FFEDDE10000 Size: 1371648
WTSAPI32.dll Base Address: 0x7FFEFF510000 Size: 37888
D3DCOMPILER_43.dll Base Address: 0x7FFEA1940000 Size: 2423296
DINPUT8.dll Base Address: 0x7FFEC51F0000 Size: 169472
XINPUT1_4.dll Base Address: 0x7FFEED1C0000 Size: 30208
IPHLPAPI.DLL Base Address: 0x7FFF030A0000 Size: 166400
powrprof.dll Base Address: 0x7FFF031C0000 Size: 70656
winmmbase.dll Base Address: 0x7FFEE9330000 Size: 95232
kernel.appcore.dll Base Address: 0x7FFF01B30000 Size: 16384
dwmapi.dll Base Address: 0x7FFF01A20000 Size: 98816
windows.storage.dll Base Address: 0x7FFF01D30000 Size: 5852672
DEVOBJ.dll Base Address: 0x7FFF03A10000 Size: 132608
Wldp.dll Base Address: 0x7FFF036B0000 Size: 96768
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFEE1390000 Size: 48128
OPENGL32.dll Base Address: 0x7FFEA1770000 Size: 909312
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFE8D660000 Size: 96256
GLU32.dll Base Address: 0x7FFEFAF70000 Size: 122880
d3dx9_43.dll Base Address: 0x7FFE8F070000 Size: 2280960
bink2w64.dll Base Address: 0x7FFEE03A0000 Size: 307712
MFCORE.DLL Base Address: 0x7FFEFFBE0000 Size: 3960320
ksuser.dll Base Address: 0x7FFEFFBD0000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFF03600000 Size: 10752
UMPDC.dll Base Address: 0x7FFF03080000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFF03C80000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFEFF7A0000 Size: 105472
MSASN1.dll Base Address: 0x7FFF03840000 Size: 34816
inputhost.dll Base Address: 0x7FFEFA300000 Size: 976384
wintypes.dll Base Address: 0x7FFF005A0000 Size: 493568
CoreMessaging.dll Base Address: 0x7FFEFCB40000 Size: 607744
CoreUIComponents.dll Base Address: 0x7FFEFC3E0000 Size: 1795072
ntmarta.dll Base Address: 0x7FFF02DE0000 Size: 140288
dbghelp.dll Base Address: 0x7FFEF6040000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFEE9270000 Size: 136704
D3D11.DLL Base Address: 0x7FFEFB3E0000 Size: 1853440
dxgi.dll Base Address: 0x7FFE1D590000 Size: 3354624
CRYPTSP.dll Base Address: 0x7FFF03610000 Size: 46080
dxgi.dll Base Address: 0x7FFF02510000 Size: 614912
rsaenh.dll Base Address: 0x7FFF02CC0000 Size: 142336
cryptnet.dll Base Address: 0x7FFEFDBD0000 Size: 135168
drvstore.dll Base Address: 0x7FFEFD8D0000 Size: 979456
imagehlp.dll Base Address: 0x7FFF04810000 Size: 45056
nvspcap64.dll Base Address: 0x7FFE94530000 Size: 2216960
profapi.dll Base Address: 0x7FFF03BB0000 Size: 81920
clbcatq.dll Base Address: 0x2197D3C0000 Size: 437760
amsi.dll Base Address: 0x7FFEEE0C0000 Size: 62464
USERENV.dll Base Address: 0x7FFF03B30000 Size: 108032
MpOav.dll Base Address: 0x7FFEEE030000 Size: 212992
nvapi64.dll Base Address: 0x7FFEF5650000 Size: 5629440
SETUPAPI.dll Base Address: 0x7FFF04E40000 Size: 887808
D3D10_1.DLL Base Address: 0x7FFEE0520000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFEFACA0000 Size: 7680
uxtheme.dll Base Address: 0x7FFF015C0000 Size: 382976
MSCTF.dll Base Address: 0x7FFF062A0000 Size: 864768
textinputframework.dll Base Address: 0x7FFEFA460000 Size: 722944
WINSTA.dll Base Address: 0x7FFF02940000 Size: 190976
nvldumdx.dll Base Address: 0x7FFEF5D20000 Size: 599040
nvgpucomp64.dll Base Address: 0x7FFEF2FE0000 Size: 29256704
NvMessageBus.dll Base Address: 0x7FFEF2680000 Size: 2750976
nvwgf2umx.dll Base Address: 0x7FFEEE2B0000 Size: 20630016
NvCamera64.dll Base Address: 0x7FFE1CD20000 Size: 4241408
HID.DLL Base Address: 0x7FFF024D0000 Size: 20480
XINPUT9_1_0.dll Base Address: 0x7FFEFF190000 Size: 4096
WindowsCodecs.dll Base Address: 0x7FFF01370000 Size: 1328128
nvppex.dll Base Address: 0x7FFEDBFA0000 Size: 728576
dxcore.dll Base Address: 0x7FFEF5DE0000 Size: 150016
d3dcompiler_47_64.dll Base Address: 0x7FFE1C910000 Size: 3922944
nvcuda64.dll Base Address: 0x7FFE77B20000 Size: 6232064
iertutil.dll Base Address: 0x7FFEF86B0000 Size: 551424
SspiCli.dll Base Address: 0x7FFF03B60000 Size: 123904
ondemandconnroutehelper.dll Base Address: 0x7FFEE0CB0000 Size: 42496
winhttp.dll Base Address: 0x7FFEFEE60000 Size: 845312
mswsock.dll Base Address: 0x7FFF03410000 Size: 331776
NSI.dll Base Address: 0x7FFF04A80000 Size: 7680
WINNSI.DLL Base Address: 0x7FFF000C0000 Size: 11776
urlmon.dll Base Address: 0x7FFEF5E50000 Size: 1281536
netutils.dll Base Address: 0x7FFF031B0000 Size: 19456
srvcli.dll Base Address: 0x7FFEF5E20000 Size: 54272
DNSAPI.dll Base Address: 0x7FFF030E0000 Size: 600576
rasadhlp.dll Base Address: 0x7FFEFDBC0000 Size: 7168
fwpuclnt.dll Base Address: 0x7FFEFD200000 Size: 283648
schannel.DLL Base Address: 0x7FFF02BD0000 Size: 486912
mskeyprotect.dll Base Address: 0x7FFEE4C40000 Size: 44544
NTASN1.dll Base Address: 0x7FFF036E0000 Size: 81408
DPAPI.DLL Base Address: 0x7FFF03A70000 Size: 5632
ncrypt.dll Base Address: 0x7FFF03720000 Size: 102400
ncryptsslp.dll Base Address: 0x7FFEE4CF0000 Size: 78848
DiscordHook64.dll Base Address: 0x7FFE75830000 Size: 793600
MMDevApi.dll Base Address: 0x7FFEFCF20000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFEE0310000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFEEA3C0000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFF01730000 Size: 31744
Windows.UI.dll Base Address: 0x7FFEFA610000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFEFA560000 Size: 450048
twinapi.appcore.dll Base Address: 0x7FFEFDF90000 Size: 1457664
avrt.dll Base Address: 0x7FFEFF6E0000 Size: 5632
d3dcompiler_47.dll Base Address: 0x7FFEFB650000 Size: 3396608
MessageBus.dll Base Address: 0x7FFEE37B0000 Size: 5349888
dhcpcsvc.DLL Base Address: 0x7FFEFFB90000 Size: 61440
gpapi.dll Base Address: 0x7FFF024E0000 Size: 69120
nvAIDVCx.dll Base Address: 0x7FFE1C490000 Size: 485888
napinsp.dll Base Address: 0x7FFEDC210000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFED84F0000 Size: 66048
wshbth.dll Base Address: 0x7FFF00CF0000 Size: 43008
NLAapi.dll Base Address: 0x7FFEFF530000 Size: 68608
winrnr.dll Base Address: 0x7FFED84D0000 Size: 32768
socialclub.dll Base Address: 0x7FFE8FFD0000 Size: 2710528
chrome_elf.dll Base Address: 0x7FFE8FE80000 Size: 901120
libcef.dll Base Address: 0x7FFE1DA00000 Size: 151009280
COMDLG32.dll Base Address: 0x7FFF04A90000 Size: 684032
OLEACC.dll Base Address: 0x7FFEED4D0000 Size: 260608
COMCTL32.dll Base Address: 0x7FFEED3D0000 Size: 560128
UIAutomationCore.DLL Base Address: 0x7FFED9500000 Size: 2040832
NETAPI32.dll Base Address: 0x7FFEE6890000 Size: 47616
DWrite.dll Base Address: 0x7FFEF53B0000 Size: 1601024
Secur32.dll Base Address: 0x7FFEEB350000 Size: 11264
USP10.dll Base Address: 0x7FFEE0980000 Size: 512
dxva2.dll Base Address: 0x7FFEDEC60000 Size: 96256
CRYPTUI.dll Base Address: 0x7FFEDEC00000 Size: 246272
credui.dll Base Address: 0x7FFEE6810000 Size: 55808
wevtapi.dll Base Address: 0x7FFF004D0000 Size: 296960
ESENT.dll Base Address: 0x7FFEE9750000 Size: 2585088
DSROLE.DLL Base Address: 0x7FFEFF460000 Size: 7680
WKSCLI.DLL Base Address: 0x7FFF02E20000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFEF2D90000 Size: 61440
wdmaud.drv Base Address: 0x7FFEE76B0000 Size: 193024
msacm32.drv Base Address: 0x7FFEE76A0000 Size: 17920
MSACM32.dll Base Address: 0x7FFEE7680000 Size: 74240
midimap.dll Base Address: 0x7FFEE69F0000 Size: 13312
FirewallAPI.dll Base Address: 0x7FFF02870000 Size: 329728
fwbase.dll Base Address: 0x7FFF02800000 Size: 151552
FWPolicyIOMgr.dll Base Address: 0x7FFEE95D0000 Size: 205824
dhcpcsvc6.DLL Base Address: 0x7FFEFFBB0000 Size: 23552
YimMenu.dll Base Address: 0x7FFE1BA60000 Size: 8075264
VCRUNTIME140.dll Base Address: 0x7FFEE7500000 Size: 73728
MSVCP140.dll Base Address: 0x7FFEE6910000 Size: 340480
VCRUNTIME140_1.dll Base Address: 0x7FFEE6900000 Size: 15360
MSVCP140_2.dll Base Address: 0x7FFECAEB0000 Size: 196096
winbrand.dll Base Address: 0x7FFEE4DF0000 Size: 161280
Dumping registers:
RAX: 0x34
RCX: 0x21963F2CF20
RDX: 0x3
RBX: 0x21963F2EAA0
RSI: 0x21A5384BFFF
RDI: 0x21A53BF82C3
RSP: 0xB23FCFF2D0
RBP: 0xB23FCFF369
R8:  0x7FF7013BA920
R9:  0x21A53840000
R10: 0x2
R11: 0x21963F043E0
R12: 0x8
R13: 0x21A5387ECE0
R14: 0x21963F2CED8
R15: 0x21963394FD8
Dumping stacktrace:
[0]	GTA5.exe+0x1623414 0x7FF6FFAE3414
[1]	GTA5.exe+0x1623F5B 0x7FF6FFAE3F5B
[2]	GTA5.exe+0xA58F60 0x7FF6FEF18F60
[3]	GTA5.exe+0x162463D 0x7FF6FFAE463D
[4]	GTA5.exe+0xA4D8FC 0x7FF6FEF0D8FC
[5]	GTA5.exe+0xA51148 0x7FF6FEF11148
[6]	GTA5.exe+0x1633449 0x7FF6FFAF3449
[7]	GTA5.exe+0x1633449 0x7FF6FFAF3449
[8]	GTA5.exe+0x1632C7F 0x7FF6FFAF2C7F
[9]	GTA5.exe+0x276A4 0x7FF6FE4E76A4
[10]	GTA5.exe+0x20D8B 0x7FF6FE4E0D8B
[11]	GTA5.exe+0x1632888 0x7FF6FFAF2888
[12]	GTA5.exe+0x1494 0x7FF6FE4C1494
[13]	GTA5.exe+0x130904F 0x7FF6FF7C904F
[14]	GTA5.exe+0x1825DCC 0x7FF6FFCE5DCC
[15]	KERNEL32.DLL BaseThreadInitThunk
[16]	ntdll.dll RtlUserThreadStart
--------End of exception--------

[13:30:03.8300325][INFO/main.cpp:199] Fiber pool initialized.
[13:30:03.8379910][INFO/main.cpp:202] HTTP Client initialized.
[13:30:04.0224858][DEBUG/thread_pool.cpp:96] Thread 11148 executing font_mgr.cpp:104
[13:30:04.0406882][INFO/main.cpp:205] Translation Service initialized.
[13:30:04.0742631][INFO/main.cpp:208] Hooking initialized.
[13:30:04.1365295][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[13:30:04.1365574][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[13:30:04.1380236][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[13:30:04.1385843][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[13:30:04.1386012][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[13:30:04.1386888][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[13:30:04.1933481][DEBUG/thread_pool.cpp:96] Thread 11148 executing player_database_service.cpp:285
[13:30:04.1939801][INFO/main.cpp:228] Registered service instances...
[13:30:04.1940387][INFO/main.cpp:231] Finished initialising services.
[13:30:04.1942644][INFO/main.cpp:252] Scripts registered.
[13:30:04.2623042][INFO/main.cpp:255] Hooking enabled.
[13:30:04.2679964][INFO/main.cpp:258] Dynamic native hooker initialized.
[13:30:04.6125210][INFO/lua_module.cpp:330] Loaded Extras-Addon.lua
[13:30:04.6808438][INFO/lua_module.cpp:330] Loaded Extras-data.lua
[13:30:04.6985607][INFO/lua_module.cpp:330] Loaded json.lua
[13:30:04.6987110][INFO/main.cpp:262] Lua manager initialized.
[13:30:12.1462418][INFO/backend.cpp:53] Starting script: Self
[13:30:12.1463972][INFO/backend.cpp:78] Starting script: Weapons
[13:30:12.1465500][INFO/backend.cpp:101] Starting script: Vehicles
[13:30:12.1465820][INFO/backend.cpp:117] Starting script: Miscellaneous
[13:30:12.1469687][INFO/backend.cpp:138] Starting script: Remote
[13:30:12.1470214][INFO/backend.cpp:153] Starting script: Ls customs
[13:30:12.1470319][INFO/backend.cpp:165] Starting script: Rainbow paint
[13:30:12.1470425][INFO/backend.cpp:177] Starting script: Disable Control Action
[13:30:12.1470597][INFO/backend.cpp:190] Starting script: World
[13:30:12.1726115][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 3248. Trying to free some memory
[13:30:12.1994291][INFO/tunables_service.cpp:36] Loading tunables from cache
[13:31:35.5190420][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x5CAA60
[13:31:35.5243342][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x961FBC
[13:31:35.5244919][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0xA66114
[13:31:35.5258796][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F0EC
[13:31:35.5259413][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F074
[13:31:47.5005605][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x318D08
[13:31:47.5237119][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F09C
[13:31:47.5237811][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F0C4
[13:31:47.5284321][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x335660
[13:31:47.5284982][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x335638
[13:31:47.5285896][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x4015B8
[13:31:47.5352251][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x45B164
[13:31:47.5355502][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x45A3A8
[13:32:34.4910740][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[13:33:00.3377070][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":19515098,"type":3136273443,"cat":654913086,"pt":142775304,"slot":0
[13:36:51.3872371][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":2000,"char":{"slot":0,"cash":16557663,"bank":0,"evc":16559613,"pvc":0,"pxr":125000000.00000,"nonce":638495626067519142},"c":[310.05551,-495.51776,42.78284],"pt":142995490,"vct":1712405551,"vcp":1000000,"mid":0,"action":"BADSPORT","cat":"GOOD_SPORT"
[13:36:51.3873461][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":2000,"char":{"slot":0,"cash":16557663,"bank":0,"evc":16559613,"pvc":0,"pxr":125000000.00000,"nonce":638495626067519142},"c":[310.05551,-495.51776,42.78284],"pt":142995490,"vct":1712405551,"vcp":1000000,"mid":0,"action":"BADSPORT","cat":"GOOD_SPORT"
[13:42:17.0471906][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":20000,"char":{"slot":0,"cash":16557663,"bank":20000,"evc":16579613,"pvc":0,"pxr":125000000.00000,"nonce":638495629323685055},"c":[33.80323,-1350.87000,29.33013],"pt":143326716,"vct":1712405551,"vcp":1000000,"mid":0,"action":"AMB_JOB","cat":"JOBS"
[13:42:17.0472936][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: EARN; DATA: "amt":20000,"char":{"slot":0,"cash":16557663,"bank":20000,"evc":16579613,"pvc":0,"pxr":125000000.00000,"nonce":638495629323685055},"c":[33.80323,-1350.87000,29.33013],"pt":143326716,"vct":1712405551,"vcp":1000000,"mid":0,"action":"AMB_JOB","cat":"JOBS"
[13:42:23.1984194][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":2500,"type":2658791846,"cat":404533672,"pt":143325850,"slot":0
[13:42:23.1985951][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":200,"type":2467613365,"cat":1928908688,"pt":143327487,"slot":0
[13:46:02.4345984][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: DUPE_DETECT; DATA: "a":1,"b":3,"c":1447690049,"d":0,"e":1,"f":47,"g":20,"h":0,"i":0,"j":false,"k":0,"l":0
[13:46:02.4352988][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":19517798,"type":3136273443,"cat":654913086,"pt":143549059,"slot":0
[13:49:56.3860563][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":19517798,"type":3136273443,"cat":654913086,"pt":143777753,"slot":0
[13:56:20.0849775][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: DUPE_DETECT; DATA: "a":1,"b":3,"c":4129572538,"d":0,"e":0,"f":47,"g":20,"h":0,"i":0,"j":false,"k":0,"l":0
[14:00:49.2116447][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 0. Trying to free some memory
[14:00:49.2117158][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 9 bytes for reliable message, free space: 0. Trying to free some memory
[14:00:49.2117392][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 9 bytes for reliable message, free space: 0. Failed to free some memory, clearing all messages (including reliables) for connection
[14:00:49.2121265][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 16. Trying to free some memory
[14:00:49.2121623][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 16. Failed to free some memory, clearing all messages (including reliables) for connection
[14:00:49.2126637][WARN/allocate_memory_reliable.cpp:35] Failed to allocate 80 bytes for reliable message, free space: 16. Trying to free some memory
[14:00:49.2126949][WARN/allocate_memory_reliable.cpp:45] Failed to allocate 80 bytes for reliable message, free space: 16. Failed to free some memory, clearing all messages (including reliables) for connection
[14:02:20.1355399][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: DUPE_DETECT; DATA: "a":1,"b":3,"c":741090084,"d":0,"e":0,"f":47,"g":20,"h":0,"i":0,"j":false,"k":0,"l":0
[14:29:24.5018764][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":19517798,"type":3136273443,"cat":654913086,"pt":146141526,"slot":0
[14:33:27.6498224][WARN/reaction.cpp:60] Received Remote Ragdoll from PurPleRusheR (88124202)
[14:33:40.6117358][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":19517798,"type":3136273443,"cat":654913086,"pt":146392404,"slot":0
[14:36:24.8631632][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":19517798,"type":3136273443,"cat":654913086,"pt":146552373,"slot":0
[14:40:40.9445962][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":19517798,"type":3136273443,"cat":654913086,"pt":146803224,"slot":0
[14:46:20.6078699][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: DUPE_DETECT; DATA: "a":1,"b":3,"c":3692679425,"d":0,"e":0,"f":47,"g":20,"h":0,"i":0,"j":false,"k":0,"l":0
[14:46:20.6080408][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: DUPE_DETECT; DATA: "a":1,"b":3,"c":117401876,"d":0,"e":0,"f":47,"g":20,"h":0,"i":0,"j":false,"k":0,"l":0

### Store

Rockstar

### Language

German

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### LINKED ISSUE #3140: [Bug]: Unknown crash can hit Yim
### Describe the bug

This is a crash from the mod menu Infamous, it spawns a 2 peds, and 2 obj it spawns a rat and a this ped="s_m_m_janitor" the obj that spawns its unk i dont have time to grab that hash and the granade seems to be like some normal granade that u can pick it up but u cant , it takes a some secs then u get crashed

### Steps To Reproduce

1. Go online
2. Someone press the crash 13

### Expected Behavior

Block the crash

### Logs

[cout.log](https://github.com/YimMenu/YimMenu/files/15345659/cout.log)

### Store

Rockstar

### Language

English

### YimMenu Language

English (US)

### Additional context

_No response_

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

### PR DESCRIPTION
**Pull request by Mr-X-GTA**
Fixes https://github.com/YimMenu/YimMenu/issues/3140
Fixes https://github.com/YimMenu/YimMenu/issues/2971
Fixes https://github.com/YimMenu/YimMenu/issues/2624

### CODE REVIEW

**Comment by lonelybud** [comment]
sound spam issue is definitely a problem. People are like playing it 1-2 times and it is not detected by rate_limiter or current checks. Only way i found was to log events and identify the mischievous player. Another problem which i saw in my fork is that when i was host and had no control over `am_launcher` someone was able to send me into `fm_intro` despite the `StartScriptBegin` protection

**Comment by lonelybud** [comment]
can we also add `GAME_WEATHER_EVENT` to detect thunder rainstorm.

**Comment by Mr-X-GTA** [comment]
> can we also add `GAME_WEATHER_EVENT` to detect thunder rainstorm.

`GAME_WEATHER_EVENT` no longer actually exists

File: src/hooks/protections/received_event.cpp [hunk 1]
```diff
@@ -751,7 +890,59 @@ namespace big
...
+				{
+					g_pointers->m_gta.m_send_event_ack(event_manager, source_player, target_player, event_index, event_handled_bitset);
+					return;
+				}
+			}
+			else
+			{
+				g_pointers->m_gta.m_send_event_ack(event_manager, source_player, target_player, event_index, event_handled_bitset);
+				return;
+			}
```
Comment (lonelybud) [inline src/hooks/protections/received_event.cpp:886]: `is_local_vehicle` has check for `g_local_player->m_vehicle->m_driver == g_local_player` so if you are passenger and driver change the radio station the `else` case will be called and event is ignored.

Comment (Mr-X-GTA) [reply src/hooks/protections/received_event.cpp:886]: That's exactly how it should be, the event is normally only sent to the driver

Comment (lonelybud) [reply src/hooks/protections/received_event.cpp:886]: so if your friend change the radio and you ignore it, thats bad isn't

Comment (Mr-X-GTA) [reply src/hooks/protections/received_event.cpp:886]: > so if your friend change the radio and you ignore it, thats bad isn't

The event is normally only sent to the driver

**Review by Rxann — COMMENTED** [review]
From what I see, incredibly good job.

File: src/hooks/protections/can_apply_data.cpp [hunk 2]
```diff
@@ -74,6 +75,21 @@
...
 {
+	constexpr uint32_t vehicle_parachutes[] = {
+	    "imp_prop_impexp_para_s"_J,
+	    "sr_prop_specraces_para_s_01"_J,
+	    "gr_prop_gr_para_s_01"_J,
+	};
+
+	inline bool is_valid_vehicle_parachute(rage::joaat_t hash)
+	{
+		for (auto& model : vehicle_parachutes)
```
Comment (gir489returns) [inline src/hooks/protections/can_apply_data.cpp:86]: This could be an unsorted set with a single contains call using O(1).

File: src/hooks/protections/received_event.cpp [hunk 3]
```diff
@@ -376,6 +391,151 @@ namespace big
...
+
+		if (is_entity)
+		{
+			entity_net_id = buffer.Read<uint16_t>(13);
+		}
+		else
+		{
+			position.x = buffer.ReadSignedFloat(19, 1337.0f);
+			position.y = buffer.ReadSignedFloat(19, 1337.0f);
+			position.z = buffer.ReadFloat(19, 1337.0f);
```
Comment (gir489returns) [inline src/hooks/protections/received_event.cpp:408]: I’m guessing this is done to put it somewhere the player can’t hear it? 8000/8000/8000 would be a better location.

File: src/hooks/protections/received_event.cpp [hunk 4]
```diff
@@ -376,6 +391,151 @@ namespace big
...
+		case "DLC_XM_Explosions_Orbital_Cannon"_J:
+		{
+			if (is_entity)
+				return true;
+
+			if (!scr_globals::globalplayer_bd.as<GlobalPlayerBD*>()->Entries[plyr->id()].OrbitalBitset.IsSet(eOrbitalBitset::kOrbitalCannonActive))
+				return true;
+
+			if (script_hash != "am_mp_defunct_base"_J && script_hash != "am_mp_orbital_cannon"_J && script_hash != "fm_mission_controller_2020"_J && script_hash != "fm_mission_controller"_J)
+				return true;
```
Comment (gir489returns) [inline src/hooks/protections/received_event.cpp:437]: Unsorted set use case again.

File: src/hooks/protections/received_event.cpp [hunk 5]
```diff
@@ -376,6 +391,151 @@ namespace big
...
+		case "Phone_SoundSet_Prologue"_J:
+		case "Phone_SoundSet_Franklin"_J:
+		case "Phone_SoundSet_Michael"_J:
+		case "Phone_SoundSet_Trevor"_J:
+		case "PLAYER_SWITCH_CUSTOM_SOUNDSET"_J:
+		case "RESPAWN_ONLINE_SOUNDSET"_J:
+		case "TATTOOIST_SOUNDS"_J:
+		case "WastedSounds"_J:
+		case "WEB_NAVIGATION_SOUNDS_PHONE"_J:
+		{
```
Comment (gir489returns) [inline src/hooks/protections/received_event.cpp:496]: Unsorted set use case again.

File: src/logger/stack_trace.cpp [hunk 6]
```diff
@@ -31,6 +31,9 @@ namespace big
 
 		m_exception_info = exception_info;
 
+		m_dump.str("");
+		m_dump.clear();
```
Comment (gir489returns) [inline src/logger/stack_trace.cpp:35]: Why call str blank and then call clear? Doesn’t it do the same thing?

File: src/util/protection.cpp [hunk 7]
```diff
@@ -4,7 +4,7 @@
...
...low_01"_J, "h4_prop_bush_fern_tall_cc"_J, "h4_prop_bush_mang_ad"_J, "h4_prop_bush_mang_low_aa"_J, "h4_prop_bush_mang_low_ab"_J, "h4_prop_bush_seagrape_low_01"_J, "prop_h4_ground_cover"_J, "h4_prop_weed_groundcover_01"_J, "h4_prop_grass_med_01"_J, "h4_prop_grass_tropical_lush_01"_J, "h4_prop_grass_wiregrass_01"_J, "h4_prop_weed_01_plant"_J, "h4_prop_weed_01_row"_J, "urbanweeds02_l1"_J, "proc_forest_grass01"_J, "prop_small_bushyba"_J, "v_res_d_dildo_a"_J, "v_res_d_dildo_b"_J, "v_res_d_dildo_c"_J, "v_res_d_dildo_d"_J, "v_res_d_dildo_e"_J, "v_res_d_dildo_f"_J, "v_res_skateboard"_J, "prop_battery_01"_J, "prop_barbell_01"_J, "prop_barbell_02"_J, "prop_bandsaw_01"_J, "prop_bbq_3"_J, "v_med_curtainsnewcloth2"_J, "bh1_07_flagpoles"_J, "hash_058a7eb5_deihiws_collision"_J, "proc_dry_plants_01"_J, "proc_leafyplant_01"_J, "proc_grassplantmix_02"_J, "proc_dryplantsgrass_01"_J, "proc_dryplantsgrass_02"_J, "proc_grasses01"_J, "prop_dryweed_002_a"_J, "prop_fernba"_J, "prop_weed_001_aa"_J, "urbangrnfrnds_01"_J, "urbanweeds01"_J, "prop_dandy_b"_J, "v_proc2_temp"_J, "prop_fernbb"_J, "proc_drygrassfronds01"_J, "prop_log_ae"_J, "prop_grass_da"_J, "prop_fragtest_cnst_04"_J, "prop_thindesertfiller_aa"_J};
```
Comment (gir489returns) [inline src/util/protection.cpp:7]: Could probably change this to an unsorted set.

**Review by gir489returns — CHANGES_REQUESTED** [review]

File: src/gta/enums.hpp [hunk 8]
```diff
@@ -485,7 +485,6 @@ enum class eNetworkEvents : uint16_t
 	REQUEST_DETACHMENT_EVENT,
 	KICK_VOTES_EVENT,
 	GIVE_PICKUP_REWARDS_EVENT,
-	NETWORK_CRC_HASH_CHECK_EVENT,
```
Comment (GreySideMM) [inline src/gta/enums.hpp:488]: How up-to-date is this enum as of now?
I a PR two month ago there was a discussion about it being outdated, several values changed. But idk what changed in the meantime: https://github.com/YimMenu/YimMenu/pull/2873#issuecomment-2022222753 and following comments.

Comment (Mr-X-GTA) [reply src/gta/enums.hpp:488]: It's now up to date

File: src/logger/stack_trace.cpp (hunk 6 above)
Comment (Mr-X-GTA) [reply src/logger/stack_trace.cpp:35]: `m_dump.str("")` clears the content and `m_dump.clear()` clears the state flags

File: src/hooks/protections/received_event.cpp (hunk 3 above)
Comment (Mr-X-GTA) [reply src/hooks/protections/received_event.cpp:408]: No, this just reads and unpacks the position from the buffer

File: src/util/math.hpp [hunk 9]
```diff
@@ -63,4 +65,24 @@ namespace big::math
 		SHAPETEST::GET_SHAPE_TEST_RESULT(ray, &hit, &end_coords, &surface_normal, &hit_entity);
 		return end_coords;
 	}
+
+	// [0, max_value)
+	inline int rand(int max_value)
+	{
+		std::random_device seed;
+		std::mt19937 gen{seed()};
```
Comment (Yimura) [inline src/util/math.hpp]: Seeding every time we call rand? Sounds like a bad idea.

Probably best to make `seed` and `gen` static variables, correct me if I'm wrong though.

File: src/util/math.hpp [hunk 10]
```diff
@@ -63,4 +65,24 @@ namespace big::math
...
+		std::uniform_int_distribution<int> dist{0, max_value - 1};
+
+		return dist(gen);
+	}
+
+	// [min_value, max_value]
+	inline int rand(int min_value, int max_value)
+	{
+		std::random_device seed;
+		std::mt19937 gen{seed()};
```
Comment (Yimura) [inline src/util/math.hpp]: Seeding every time we call rand? Sounds like a bad idea.

Probably best to make `seed` and `gen` static variables, correct me if I'm wrong though.

**Review by Yimura — CHANGES_REQUESTED** [review]

File: src/util/math.hpp (hunk 9 above)
Comment (gir489returns) [reply src/util/math.hpp:73]: Could probably use a singleton pattern to initalize the seed.

Comment (Yimura) [reply src/util/math.hpp]: Yeah using static isn't really the best way, but better than the current.

File: src/util/math.hpp (hunk 10 above)
Comment (rkwapisz) [reply src/util/math.hpp]: I can see why, though. I think every YimMenu user's spoofed host token is 41, even though we're seeding rand() already (albeit just once). That makes it easy to detect the menu in particular. That's not necessarily a problem, because who cares, but it's a common pattern I've noticed when observing users' host tokens.

**Review by gir489returns — APPROVED** [review]

**Review by Yimura — APPROVED** [review]
